{
  "hash": "4f0c96fd7afb044478d1fe344181c3e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Unreported Detention: An analysis of ICE detention statistics not included in the FY 2025 annual detention report\"\ndescription: \"Comparing the Deportation Data Project's daily detention counts with ICE's published annual statistics to identify unreported facilities and track population changes\"\nauthor: \"Carwil Bjork-James\"\ndate: last-modified\nimage: ddp-comparison-thumbnail.png\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\nThis page offers an analysis of two forms of data on the population of people held by US Immigration and Customs Enforcement (ICE): summary data on detention published by ICE on its website and a detailed and granular dataset of arrests, removals, and overnight populations under ICE custody, released under the Freedom of Information Act and archived by the Deportation Data Project.\n\nThe former data, is published online the [ICE Detention Management Division](https://www.ice.gov/detain/detention-management). I have also produced a map of reported facilities based on sixteen years of reporting (eight annual reports and two summary sheets) from ICE.\n\nThe newer data covers \"every ICE encounter, detainer request, arrest, book-in to detention, and removal\" between September 1, 2022 and October 15, 2025.\n\nAs becomes clear below, the more extensive data shows that ICE's public reporting is incomplete, and the uncounted population grew massively during 2025, from hundreds of individuals per night in the final months of the Biden administration to as many as forty-five hundred individuals, and frequently in excess of three thousand in summer and early fall 2025. This unreported network includes over ICE-owned holding facilities, nine dedicated ICE detention centers, local jail and state prisons, federal prisons, and over 200 medical facilities.\n\nThe FOIA-supplied data also exceeds ICE's annual reporting in those facilities that do match by 1,038 detainees per night over the course of FY 2025, though this only amounts to 2% of the total population.\n\nIn much oyf this report, facility-level summaries distinguish between facilities with **Average Daily Population** or **ADP ≥ 2** and those with **ADP \\< 2**. Facilities averaging fewer than two detainees per day---typically hospitals, occasional-use hold rooms, and other transient placements---account for many DDP facility codes but negligible population. Separating them keeps attention on facilities with substantive detention activity.\n\n*This page is part of a larger data project to gather, summarize, and analyze public data about immigration enforcement in the United States. The focus here is detention facilities used by US Immigration and Customs Enforcement (ICE).*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(scales)\nlibrary(knitr)\nlibrary(sf)\nlibrary(leaflet)\nlibrary(leafpop)\nlibrary(targets)\nlibrary(kableExtra)\n\nsource(here::here(\"add-carto-tiles.R\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"R/ddp.R\")\nddp_raw            <- tar_read(ddp_raw)\nfacilities_keyed   <- tar_read(facilities_keyed)\ndetloc_lookup      <- tar_read(detloc_lookup)\ndetloc_lookup_full <- tar_read(detloc_lookup_full)\nvera_facilities    <- tar_read(vera_facilities)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Vera type lookup (one row per detloc).\n# Uses corrected types from the pipeline (see vera_type_overrides() in vera-institute.R).\nvera_type_lookup <- vera_facilities |>\n  select(detloc, type_grouped = type_grouped_corrected,\n         type_detailed = type_detailed_corrected, latitude, longitude) |>\n  distinct(detloc, .keep_all = TRUE)\n\n# ICE FY25 from pipeline\nice_fy25 <- facilities_keyed[[\"FY25\"]] |>\n  select(canonical_id, canonical_name, detloc, facility_name, facility_city,\n         facility_state, sum_classification_levels) |>\n  rename(ice_adp = sum_classification_levels)\n\nice_fy25_ids <- unique(ice_fy25$canonical_id)\n\n# DDP facility-level summaries: Oct 1 2024 – Sep 24 2025\n# (matches the ICE FY25 spreadsheet currency date)\nddp_fy25 <- ddp_facility_summary(ddp_raw,\n                                  from = \"2024-10-01\", to = \"2025-09-24\") |>\n  rename(ddp_adp = mean_pop)\n\n# Use detloc_lookup_full to map DDP facility codes to canonical IDs.\n# The 1:1 detloc_lookup picks only one code per canonical facility, but some\n# facilities have multiple DETLOCs across sources (e.g., DMCP vs DDP codes).\n# Using the full lookup ensures all codes contribute ADP to the right facility.\nddp_detloc_map <- detloc_lookup_full |>\n  distinct(detloc, canonical_id)\n\nddp_fy25_keyed <- ddp_fy25 |>\n  left_join(ddp_detloc_map, by = c(\"detention_facility_code\" = \"detloc\")) |>\n  mutate(in_ice_fy25 = !is.na(canonical_id) & canonical_id %in% ice_fy25_ids)\n```\n:::\n\n\nThroughout this report, facility-level summaries distinguish between facilities with **ADP ≥ 2** and those with **ADP < 2**. Facilities averaging fewer than two detainees per day---typically hospitals, occasional-use hold rooms, and other transient placements---account for many DDP facility codes but negligible population. Separating them keeps attention on facilities with substantive detention activity.\n\n## Aggregate comparison\n\nThe DDP (Deportation Data Project) provides daily facility-level detention counts. To compare with the ICE FY25 annual statistics, we average DDP daily counts from October 1, 2024 through September 24, 2025---the date stamp on the FY25 spreadsheet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Source      = c(\"ICE FY25 annual stats\", \"DDP daily average\"),\n  Facilities  = c(nrow(ice_fy25), nrow(ddp_fy25)),\n  `Total ADP` = c(round(sum(ice_fy25$ice_adp, na.rm = TRUE)),\n                   round(sum(ddp_fy25$ddp_adp)))\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Source                | Facilities| Total ADP|\n|:---------------------|----------:|---------:|\n|ICE FY25 annual stats |        189|     47549|\n|DDP daily average     |        853|     50130|\n\n\n:::\n:::\n\n\nThe DDP covers 853 facility codes while the ICE spreadsheet lists 189 facilities. The DDP's higher total reflects the many smaller facilities (hold rooms, federal prisons, medical facilities) not included in the ICE annual statistics.\n\n### Daily population over time\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_totals <- ddp_raw |>\n  group_by(date) |>\n  summarise(total_pop = sum(n_detained, na.rm = TRUE), .groups = \"drop\") |>\n  mutate(fiscal_year = if_else(\n    as.integer(format(date, \"%m\")) >= 10,\n    paste0(\"FY\", as.integer(format(date, \"%Y\")) + 1 - 2000),\n    paste0(\"FY\", as.integer(format(date, \"%Y\")) - 2000)\n  ))\n\nfy_breaks <- as.Date(c(\"2023-10-01\", \"2024-10-01\", \"2025-10-01\"))\nfy_labels <- data.frame(\n  x = as.Date(c(\"2024-04-01\", \"2025-04-01\", \"2025-10-08\")),\n  label = c(\"FY24\", \"FY25\", \"FY26\")\n)\n\nggplot(daily_totals, aes(x = date, y = total_pop)) +\n  geom_line(linewidth = 0.3) +\n  geom_vline(xintercept = fy_breaks, linetype = \"dashed\", alpha = 0.4) +\n  geom_text(data = fy_labels, aes(x = x, y = max(daily_totals$total_pop) * 1.04,\n                                   label = label), inherit.aes = FALSE, size = 3) +\n  scale_y_continuous(labels = comma) +\n  labs(x = NULL, y = \"Total detained population\")\n```\n\n::: {.cell-output-display}\n![Total ICE detained population per day (DDP data, all facilities)](ddp-comparison_files/figure-html/fig-daily-total-1.png){#fig-daily-total width=672}\n:::\n:::\n\n\n## Facility-level matching\n\nWe join the two datasets through canonical facility IDs. Each DDP facility code is mapped to a canonical ID via `detloc_lookup_full`, which preserves all DETLOC variants from every source (DMCP, DDP, hold/ERO, Vera). Some canonical facilities have multiple codes---for example, Central Arizona Florence Correctional Complex uses `CCADCAZ` (DMCP) and `CCAFLAZ` (DDP), and Delaney Hall uses `ESSEXNJ` (DMCP) and `DHDFNJ` (DDP). Using the full lookup ensures all codes contribute ADP to the correct facility.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate DDP by canonical_id for matched facilities.\nddp_by_canonical <- ddp_fy25_keyed |>\n  filter(in_ice_fy25) |>\n  group_by(canonical_id) |>\n  summarise(ddp_adp = sum(ddp_adp), .groups = \"drop\")\n\ncomparison <- ice_fy25 |>\n  # ICE FY25 can have multiple rows per canonical_id (e.g., Adelanto + Desert View Annex)\n  group_by(canonical_id) |>\n  summarise(\n    canonical_name = first(canonical_name),\n    ice_adp = sum(ice_adp, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  full_join(ddp_by_canonical, by = \"canonical_id\") |>\n  mutate(\n    in_ice = !is.na(ice_adp),\n    in_ddp = !is.na(ddp_adp),\n    diff   = ddp_adp - ice_adp,\n    pct_diff = diff / ice_adp * 100\n  )\n\nmatched <- comparison |> filter(in_ice & in_ddp)\n\ntibble(\n  Category = c(\"In both sources\", \"ICE only (no DDP match)\",\n               \"Matched: ICE total ADP\", \"Matched: DDP total ADP\",\n               \"Matched: aggregate difference\"),\n  Value = c(\n    sum(comparison$in_ice & comparison$in_ddp),\n    sum(comparison$in_ice & !comparison$in_ddp),\n    round(sum(matched$ice_adp, na.rm = TRUE)),\n    round(sum(matched$ddp_adp, na.rm = TRUE)),\n    paste0(round(sum(matched$ddp_adp, na.rm = TRUE) -\n                   sum(matched$ice_adp, na.rm = TRUE)),\n           \" (\", round((sum(matched$ddp_adp, na.rm = TRUE) /\n                           sum(matched$ice_adp, na.rm = TRUE) - 1) * 100, 2), \"%)\")\n  )\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Category                      |Value        |\n|:-----------------------------|:------------|\n|In both sources               |189          |\n|ICE only (no DDP match)       |0            |\n|Matched: ICE total ADP        |47549        |\n|Matched: DDP total ADP        |48575        |\n|Matched: aggregate difference |1026 (2.16%) |\n\n\n:::\n:::\n\n\n### Facility-level agreement\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboth_nonzero <- matched |> filter(ice_adp > 0, ddp_adp > 0)\n\nggplot(both_nonzero, aes(x = ice_adp, y = ddp_adp)) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  geom_point(alpha = 0.6) +\n  scale_x_log10(labels = comma) +\n  scale_y_log10(labels = comma) +\n  labs(x = \"ICE FY25 ADP (annual stats)\", y = \"DDP mean daily population\")\n```\n\n::: {.cell-output-display}\n![FY25 ADP comparison by facility (log scale). Dashed line = perfect agreement.](ddp-comparison_files/figure-html/fig-scatter-1.png){#fig-scatter width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  `Agreement band` = c(\"Within 10%\", \"Within 25%\", \"Within 50%\", \">50% difference\"),\n  Facilities = c(\n    sum(abs(both_nonzero$pct_diff) <= 10),\n    sum(abs(both_nonzero$pct_diff) > 10 & abs(both_nonzero$pct_diff) <= 25),\n    sum(abs(both_nonzero$pct_diff) > 25 & abs(both_nonzero$pct_diff) <= 50),\n    sum(abs(both_nonzero$pct_diff) > 50)\n  )\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Agreement band  | Facilities|\n|:---------------|----------:|\n|Within 10%      |        117|\n|Within 25%      |         26|\n|Within 50%      |         30|\n|>50% difference |         16|\n\n\n:::\n:::\n\n\nAmong the 189 matched facilities with nonzero ADP in both sources, 117 agree within 10%. The log-scale correlation is 0.998.\n\n### Absolute ADP differences\n\n\n::: {#tbl-abs-diff .cell tbl-cap='Distribution of absolute ADP differences (DDP − ICE) among matched facilities'}\n\n```{.r .cell-code}\nabs_diff <- abs(both_nonzero$diff)\ntibble(\n  `Difference band` = c(\"< 5\", \"5–25\", \"25–100\", \"100–500\", \"> 500\"),\n  Facilities = c(\n    sum(abs_diff < 5),\n    sum(abs_diff >= 5 & abs_diff < 25),\n    sum(abs_diff >= 25 & abs_diff < 100),\n    sum(abs_diff >= 100 & abs_diff < 500),\n    sum(abs_diff >= 500)\n  ),\n  `Total excess ADP` = c(\n    round(sum(both_nonzero$diff[abs_diff < 5])),\n    round(sum(both_nonzero$diff[abs_diff >= 5 & abs_diff < 25])),\n    round(sum(both_nonzero$diff[abs_diff >= 25 & abs_diff < 100])),\n    round(sum(both_nonzero$diff[abs_diff >= 100 & abs_diff < 500])),\n    round(sum(both_nonzero$diff[abs_diff >= 500]))\n  )\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Difference band | Facilities| Total excess ADP|\n|:---------------|----------:|----------------:|\n|< 5             |        128|              148|\n|5–25            |         53|              420|\n|25–100          |          7|              326|\n|100–500         |          1|              131|\n|> 500           |          0|                0|\n\n\n:::\n:::\n\n\nThe net difference across all 189 matched facilities is 1026 ADP (DDP minus ICE). Positive values indicate DDP counts higher than ICE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Log-modulus transform: sign(x) * log10(|x| + 1)\nlog_mod <- function(x) sign(x) * log10(abs(x) + 1)\nlog_mod_inv <- function(x) sign(x) * (10^abs(x) - 1)\n\nggplot(both_nonzero, aes(x = diff)) +\n  geom_histogram(bins = 50) +\n  scale_x_continuous(\n    transform = scales::new_transform(\"logmod\", log_mod, log_mod_inv),\n    breaks = c(-1000, -100, -10, 0, 10, 100, 1000),\n    labels = comma\n  ) +\n  labs(x = \"ADP difference (DDP \\u2212 ICE)\", y = \"Facilities\")\n```\n\n::: {.cell-output-display}\n![Distribution of facility-level ADP differences (DDP − ICE) among matched facilities (log-modulus scale)](ddp-comparison_files/figure-html/fig-diff-hist-1.png){#fig-diff-hist width=672}\n:::\n:::\n\n\n\n::: {#tbl-ice-only .cell tbl-cap='ICE FY25 facilities with no DDP match'}\n\n```{.r .cell-code}\nice_only <- comparison |> filter(in_ice & !in_ddp)\nif (nrow(ice_only) > 0) {\n  ice_only |>\n    select(canonical_id, canonical_name, ice_adp) |>\n    mutate(ice_adp = round(ice_adp)) |>\n    arrange(desc(ice_adp)) |>\n    kable(col.names = c(\"ID\", \"Facility\", \"ICE ADP\"))\n}\n```\n:::\n\n\nAll ICE FY25 facilities have a matching DDP facility code.\n\n## Unmatched facilities {#sec-unmatched}\n\n**662** of 853 DDP facility codes do not appear in the ICE FY25 annual statistics. These are facilities where ICE holds detainees but which are excluded from the published spreadsheet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunmatched <- ddp_fy25_keyed |>\n  filter(!in_ice_fy25) |>\n  left_join(\n    vera_type_lookup |> select(detloc, type_grouped, type_detailed),\n    by = c(\"detention_facility_code\" = \"detloc\")\n  ) |>\n  mutate(\n    type_grouped = if_else(is.na(type_grouped), \"Unclassified\", type_grouped),\n    adp_class = if_else(ddp_adp >= 2, \"ADP \\u2265 2\", \"ADP < 2\"),\n    peak_class = dplyr::if_else(peak_pop >= 2, \"Peak \\u2265 2\", \"Peak < 2\")\n  )\n```\n:::\n\n\n### By facility type\n\nFacility types are drawn from the Vera Institute's classification system. \"Dedicated\" facilities are purpose-built or contractually dedicated to ICE detention. \"Non-Dedicated\" are county jails and other facilities that also hold ICE detainees. \"Hold/Staging\" are short-term ERO processing rooms. \"Federal\" includes BOP prisons and USMS facilities.\n\n\n::: {#tbl-unmatched-types .cell tbl-cap='DDP facilities not in ICE FY25, by Vera facility type and ADP class'}\n\n```{.r .cell-code}\nunmatched |>\n  group_by(type_grouped, peak_class) |>\n  summarise(\n    Facilities = n(),\n    `FY25 ADP` = round(sum(ddp_adp)),\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(`FY25 ADP`)) |>\n  kable(col.names = c(\"Facility type\", \"Peak class\", \"Facilities\", \"FY25 ADP\"))\n```\n\n::: {.cell-output-display}\n\n\n|Facility type |Peak class | Facilities| FY25 ADP|\n|:-------------|:----------|----------:|--------:|\n|Hold/Staging  |Peak ≥ 2   |        169|     1163|\n|Dedicated     |Peak ≥ 2   |          6|      186|\n|Federal       |Peak ≥ 2   |         41|       80|\n|Medical       |Peak ≥ 2   |         77|       64|\n|Non-Dedicated |Peak ≥ 2   |         57|       45|\n|Other/Unknown |Peak ≥ 2   |          3|        6|\n|Family/Youth  |Peak ≥ 2   |          2|        4|\n|Medical       |Peak < 2   |        151|        4|\n|Non-Dedicated |Peak < 2   |         97|        3|\n|Dedicated     |Peak < 2   |          2|        0|\n|Family/Youth  |Peak < 2   |          3|        0|\n|Federal       |Peak < 2   |         42|        0|\n|Hold/Staging  |Peak < 2   |          9|        0|\n|Other/Unknown |Peak < 2   |          2|        0|\n|Unclassified  |Peak ≥ 2   |          1|        0|\n\n\n:::\n:::\n\n\nThe 662 unmatched facilities account for a full-year ADP of roughly **1,555**. Of those, 560 facility codes average fewer than 2 detainees per day, contributing 136 ADP in total. Of those,  306 facility codes never had more than 1 detainee per day, contributing 8 ADP in total.\n\n\n::: {#tbl-dedicated-unmatched .cell tbl-cap='Dedicated facilities in DDP but absent from ICE FY25'}\n\n```{.r .cell-code}\ndedicated_unmatched <- unmatched |>\n  filter(type_grouped == \"Dedicated\")\n\nif (nrow(dedicated_unmatched) > 0) {\n  dedicated_unmatched |>\n    select(detention_facility_code, detention_facility, state, ddp_adp, peak_class) |>\n    mutate(ddp_adp = round(ddp_adp)) |>\n    arrange(desc(ddp_adp)) |>\n    kable(col.names = c(\"DETLOC\", \"Facility name\", \"State\", \"FY25 ADP\", \"Peak class\"))\n}\n```\n\n::: {.cell-output-display}\n\n\n|DETLOC  |Facility name                     |State | FY25 ADP|Peak class |\n|:-------|:---------------------------------|:-----|--------:|:----------|\n|FLDSSFS |FLORIDA SOFT-SIDED FACILITY-SOUTH |FL    |      170|Peak ≥ 2   |\n|FLBAKCI |BAKER C. I.                       |FL    |       16|Peak ≥ 2   |\n|BERNANM |BERNALILLO COUNTY DET CTR         |NM    |        0|Peak < 2   |\n|BIINCCO |BI INCORORATED, GEO GROUP COMPANY |CO    |        0|Peak ≥ 2   |\n|BPC     |BOSTON SPC                        |MA    |        0|Peak ≥ 2   |\n|CVANXCA |CENTRAL VALLEY ANNEX              |CA    |        0|Peak < 2   |\n|FLDADCI |DADE CORRECTIONAL INST            |FL    |        0|Peak ≥ 2   |\n|LPAPSAZ |LA PALMA CORR CTR APSO            |AZ    |        0|Peak ≥ 2   |\n\n\n:::\n:::\n\n\n8 Dedicated facilities appear in DDP but not in ICE FY25, contributing 186 ADP.\n\n### Daily and monthly detention in unmatched facilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_unmatched <- ddp_raw |>\n  filter(detention_facility_code %in% unmatched$detention_facility_code,\n         date >= as.Date(\"2024-10-01\"), date <= as.Date(\"2025-09-24\")) |>\n  group_by(date) |>\n  summarise(total_pop = sum(n_detained, na.rm = TRUE), .groups = \"drop\")\n\nggplot(daily_unmatched, aes(x = date, y = total_pop)) +\n  geom_line(linewidth = 0.3) +\n  scale_y_continuous(labels = comma) +\n  scale_x_date(date_labels = \"%b %Y\", date_breaks = \"2 months\") +\n  labs(x = NULL, y = \"Detained population (unmatched facilities)\")\n```\n\n::: {.cell-output-display}\n![Daily detained population in facilities not in ICE FY25 annual statistics](ddp-comparison_files/figure-html/fig-daily-unmatched-1.png){#fig-daily-unmatched width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunmatched_codes <- unmatched$detention_facility_code\n\nmonthly_unmatched <- ddp_raw |>\n  filter(detention_facility_code %in% unmatched_codes,\n         date >= as.Date(\"2024-10-01\"), date <= as.Date(\"2025-09-24\")) |>\n  left_join(\n    vera_type_lookup |> select(detloc, type_grouped),\n    by = c(\"detention_facility_code\" = \"detloc\")\n  ) |>\n  mutate(\n    type_grouped = if_else(is.na(type_grouped), \"Unclassified\", type_grouped),\n    month = as.Date(format(date, \"%Y-%m-01\"))\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_totals <- monthly_unmatched |>\n  group_by(month) |>\n  summarise(daily_avg = sum(n_detained) / n_distinct(date), .groups = \"drop\")\n\nggplot(monthly_totals, aes(x = month, y = daily_avg)) +\n  geom_col() +\n  scale_y_continuous(labels = comma) +\n  scale_x_date(date_labels = \"%b %Y\", date_breaks = \"2 months\") +\n  labs(x = NULL, y = \"Average daily population\")\n```\n\n::: {.cell-output-display}\n![Average daily population in unmatched facilities, by month](ddp-comparison_files/figure-html/fig-monthly-total-1.png){#fig-monthly-total width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_by_type <- monthly_unmatched |>\n  group_by(month, type_grouped) |>\n  summarise(daily_avg = sum(n_detained) / n_distinct(date), .groups = \"drop\")\n\nggplot(monthly_by_type, aes(x = month, y = daily_avg, fill = type_grouped)) +\n  geom_col() +\n  scale_y_continuous(labels = comma) +\n  scale_x_date(date_labels = \"%b %Y\", date_breaks = \"2 months\") +\n  labs(x = NULL, y = \"Average daily population\", fill = \"Facility type\")\n```\n\n::: {.cell-output-display}\n![Average daily population in unmatched facilities, by month and type](ddp-comparison_files/figure-html/fig-monthly-by-type-1.png){#fig-monthly-by-type width=672}\n:::\n:::\n\n\n### Last 60 days of FY25\n\nThe final 60 days of the FY25 data window (July 27 -- September 24, 2025) capture the period of peak detention.\n\n\n::: {#tbl-last60 .cell tbl-cap='Average daily population in unmatched facilities, last 60 days of FY25'}\n\n```{.r .cell-code}\nlast60_start <- as.Date(\"2025-07-27\")\nlast60_end   <- as.Date(\"2025-09-24\")\n\nlast60 <- monthly_unmatched |>\n  filter(date >= last60_start, date <= last60_end)\n\nlast60_by_type <- last60 |>\n  group_by(type_grouped) |>\n  summarise(\n    Facilities = n_distinct(detention_facility_code),\n    `Daily avg` = round(sum(n_detained) / n_distinct(date)),\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(`Daily avg`))\n\nlast60_total <- sum(last60_by_type$`Daily avg`)\n\nlast60_by_type |>\n  rename(`Facility type` = type_grouped) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Facility type | Facilities| Daily avg|\n|:-------------|----------:|---------:|\n|Hold/Staging  |        178|      1987|\n|Dedicated     |          8|       787|\n|Federal       |         83|       182|\n|Medical       |        228|        97|\n|Non-Dedicated |        154|        81|\n|Other/Unknown |          5|         8|\n|Family/Youth  |          5|         5|\n|Unclassified  |          1|         0|\n\n\n:::\n:::\n\n\nIn the last 60 days, **3,147** people per day were held in facilities absent from the ICE FY25 annual statistics.\n\n### Peak FY25 population by facility\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_fy25 <- ddp_facility_summary(ddp_raw,\n                                   from = \"2024-10-01\", to = \"2025-09-24\",\n                                   codes = unmatched_codes) |>\n  mutate(\n    mean_pop = round(mean_pop, 1),\n    adp_class = if_else(mean_pop >= 2, \"ADP \\u2265 2\", \"ADP < 2\"),\n    peak_class = dplyr::if_else(peak_pop >= 2, \"Peak \\u2265 2\", \"Peak < 2\")\n  ) |>\n  left_join(\n    vera_type_lookup,\n    by = c(\"detention_facility_code\" = \"detloc\")\n  ) |>\n  mutate(type_grouped = if_else(is.na(type_grouped), \"Unclassified\", type_grouped))\n```\n:::\n\n\n\n::: {#tbl-peak-top20 .cell tbl-cap='Top 20 unmatched facilities by FY25 peak detained population'}\n\n```{.r .cell-code}\npeak_fy25 |>\n  arrange(desc(peak_pop)) |>\n  head(20) |>\n  select(detention_facility, state, type_grouped, peak_pop, peak_date, mean_pop) |>\n  kable(col.names = c(\"Facility\", \"State\", \"Type\", \"Peak\", \"Peak date\", \"Mean ADP\"))\n```\n\n::: {.cell-output-display}\n\n\n|Facility                           |State |Type         | Peak|Peak date  | Mean ADP|\n|:----------------------------------|:-----|:------------|----:|:----------|--------:|\n|EL PASO SOFT SIDED FACILITY        |TX    |Hold/Staging | 1606|2025-08-12 |    243.2|\n|FLORIDA SOFT-SIDED FACILITY-SOUTH  |FL    |Dedicated    | 1482|2025-07-30 |    170.3|\n|KROME HOLD ROOM                    |FL    |Hold/Staging |  600|2025-02-17 |     36.5|\n|URSULA CENTRALIZED PROCESSING CNTR |TX    |Federal      |  463|2025-07-11 |     31.6|\n|LOS CUST CASE                      |CA    |Hold/Staging |  455|2025-07-11 |     58.7|\n|BAKER C. I.                        |FL    |Dedicated    |  294|2025-09-24 |     15.7|\n|RICHMOND SUB-OFFICE HOLD           |VA    |Hold/Staging |  277|2025-09-07 |     16.2|\n|BROADVIEW SERVICE STAGING          |IL    |Hold/Staging |  245|2025-09-20 |     31.7|\n|NYC HOLD ROOM                      |NY    |Hold/Staging |  228|2025-06-05 |     40.9|\n|DALLAS F.O. HOLD                   |TX    |Hold/Staging |  225|2025-09-18 |     53.1|\n|MONTGOMERY HOLD RM                 |TX    |Hold/Staging |  221|2025-08-21 |     50.0|\n|BOSTON HOLDROOM                    |MA    |Hold/Staging |  206|2025-05-13 |     18.6|\n|AZ REM OP COORD CENTER (AROCC)     |AZ    |Hold/Staging |  195|2025-04-30 |     37.4|\n|MIAMI STAGING FACILITY             |FL    |Hold/Staging |  176|2025-01-31 |     16.5|\n|ATLANTA DIST. HOLD RM              |GA    |Hold/Staging |  168|2025-06-25 |     42.1|\n|SANTA ANA DRO HOLDROOM             |CA    |Hold/Staging |  150|2025-06-11 |     11.3|\n|SAN ANTONIO DRO HOLD ROOM          |TX    |Hold/Staging |  145|2025-06-04 |     19.6|\n|INDIANAPOLIS HOLD ROOM             |IN    |Hold/Staging |  130|2025-09-19 |     12.3|\n|WASHINGTON FIELD OFFICE            |VA    |Hold/Staging |  127|2025-08-23 |     17.3|\n|ORLANDO HOLD ROOM                  |FL    |Hold/Staging |  126|2025-06-04 |     19.6|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_fy25 |>\n  filter(peak_pop > 0) |>\n  ggplot(aes(x = peak_pop)) +\n  geom_histogram(bins = 40) +\n  scale_x_log10(labels = comma) +\n  labs(x = \"Peak detained population (FY25)\", y = \"Facilities\")\n```\n\n::: {.cell-output-display}\n![Distribution of FY25 peak population among unmatched facilities (log scale, facilities with peak > 0)](ddp-comparison_files/figure-html/fig-peak-dist-1.png){#fig-peak-dist width=672}\n:::\n:::\n\n\n## Map of unmatched facilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_data <- peak_fy25 |>\n  filter(peak_pop > 0, !is.na(latitude), !is.na(longitude))\n\nmap_sf <- st_as_sf(map_data, coords = c(\"longitude\", \"latitude\"), crs = 4326)\n\ntype_colors <- c(\n  \"Dedicated\"     = \"#e41a1c\",\n  \"Non-Dedicated\" = \"#377eb8\",\n  \"Federal\"       = \"#4daf4a\",\n  \"Hold/Staging\"  = \"#ff7f00\",\n  \"Family/Youth\"  = \"#984ea3\",\n  \"Medical\"       = \"#a65628\",\n  \"Other/Unknown\" = \"#999999\",\n  \"Unclassified\"  = \"#333333\"\n)\n\nmap_sf$type_grouped <- factor(map_sf$type_grouped, levels = names(type_colors))\npresent_levels <- levels(droplevels(map_sf$type_grouped))\npal <- colorFactor(palette = type_colors[present_levels], domain = present_levels)\n\n# sqrt scale for area-proportional circle sizing\nradii <- scales::rescale(sqrt(map_sf$peak_pop), to = c(3, 20))\n\nleaflet(map_sf) |>\n  addCartoTiles(\"CartoDB.Positron\") |> # custom function to send API key\n  addCircleMarkers(\n    radius      = radii,\n    color       = \"black\",\n    weight      = 1,\n    fillColor   = ~pal(type_grouped),\n    fillOpacity = 0.7,\n    label       = ~paste0(detention_facility, \" (\", state, \": peak \", peak_pop, \")\"),\n    popup       = ~paste0(\n      \"<b>\", detention_facility, \"</b><br>\",\n      state, \" | \", type_grouped, \"<br>\",\n      \"Peak: \", peak_pop, \" (\", peak_date, \")<br>\",\n      \"Mean ADP: \", mean_pop\n    )\n  ) |>\n  addLegend(\n    pal = pal, values = ~type_grouped,\n    title = \"Facility type\", position = \"bottomright\"\n  )\n```\n\n::: {#fig-map .cell-output-display}\n\n```{=html}\n<div class=\"leaflet html-widget html-fill-item\" id=\"htmlwidget-44d0bdd4e3f8031150a1\" style=\"width:100%;height:650px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-44d0bdd4e3f8031150a1\">{\"x\":{\"options\":{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}}},\"calls\":[{\"method\":\"addTiles\",\"args\":[\"https://basemaps.cartocdn.com/rastertiles/light_all/{z}/{x}/{y}.png?key=cb1_2xkn_1_fffafcf1ca4d733936bb3206\",null,null,{\"minZoom\":0,\"maxZoom\":18,\"tileSize\":256,\"subdomains\":\"abc\",\"errorTileUrl\":\"\",\"tms\":false,\"noWrap\":false,\"zoomOffset\":0,\"zoomReverse\":false,\"opacity\":1,\"zIndex\":1,\"detectRetina\":false,\"attribution\":\"&copy; <a href=\\\"https://carto.com/attributions\\\">CARTO<\\/a>, &copy; <a href=\\\"https://www.openstreetmap.org/copyright\\\">OpenStreetMap<\\/a> contributors\"}]},{\"method\":\"addCircleMarkers\",\"args\":[[37.413162,35.052654,40.19177,44.011519,35.383374,21.380854,35.768842,13.476607,18.49428,33.820504,47.911344,61.218545,64.834574,61.303929,55.348401,58.361196,61.601371,26.181502,42.753381,38.798612,37.487897,35.222536,61.21838,61.212362,32.76788,32.774357,39.614347,34.076434,33.747313,33.753164,32.204448,30.269638,33.452963,30.88454,39.255423,33.464564,34.191178,18.36813,30.227229,42.331116,32.84109,40.739556,31.057053,35.089343,42.900476,33.479539,42.339818,39.76089,45.783884,33.214606,35.37372,38.049579,36.79791,29.433305,32.241991,43.592766,41.564966,36.226218,42.529248,18.423156,34.676872,34.053536,30.820701,33.832026,32.051673,47.422017,37.177542,32.189687,34.572116,42.482884,42.365668,29.954188,28.4481,26.10273,42.285653,26.115173,27.248275,44.522386,41.868522,32.225131,32.793252,30.563444,42.969805,42.888191,30.741522,41.735155,44.277316,25.904507,47.466362,38.69362,42.875338,35.409321,30.338203,31.021745,38.006686,45.120098,37.413683,32.880542,18.3223,33.297252,32.858631,33.352159,37.37896,41.974839,31.336323,32.846752,40.759299,45.006527,37.513281,36.869194,26.917117,36.717768,32.869878,41.1368,35.162496,35.179783,39.238322,40.759299,28.846057,25.730701,41.504901,39.962334,35.222886,42.998116,35.106032,42.27608,47.407206,34.009224,33.908688,38.440611,34.075744,30.220628,29.158732,37.144768,40.513626,41.975295,27.800583,38.83347,31.336248,42.852072,37.302599,38.474087,35.668096,38.222836,32.823622,34.428756,39.783607,39.767429,42.408815,29.393471,39.727319,32.302904,33.057249,39.372829,31.756534,41.585489,34.47175,37.237142,39.154507,36.21458,42.92631,32.780254,31.81029,39.743074,31.780626,31.758577,31.783763,31.883642,39.777393,40.730608,34.016508,44.052201,36.10463,32.591799,48.846499,37.967657,30.214808,26.197471,26.805735,25.417168,25.86434,29.452338,26.119681,33.07325,26.548906,43.773436,40.001549,40.083661,39.36508,36.732676,28.88813,35.332868,34.740003,35.2675,37.967657,47.935792,39.087429,34.147255,33.751493,42.596402,47.92382,30.614889,40.924152,42.972684,34.937155,39.515051,21.521757,13.504854,43.664802,35.051205,41.793296,41.651255,30.43979,33.176272,38.426799,30.28838,30.284935,44.972765,29.712155,36.072843,46.5935,35.314884,26.760472,35.318807,37.49546,39.56276,29.710657,29.72272,21.299633,27.95822,26.416723,36.765066,26.178023,26.157745,32.471824,29.952045,26.200493,25.773994,43.514758,32.678948,39.76654,35.526239,33.418011,32.287959,30.255532,38.314552,40.649562,40.700537,31.546298,25.792538,36.72385,32.728058,39.268843,28.883485,28.884651,42.97767,35.653064,35.382272,29.311329,35.960303,57.790987,33.425398,25.75434,25.758146,41.422344,41.134753,28.444703,32.31994,44.375136,29.812018,33.58437,29.466674,38.066145,42.484282,38.971014,40.532993,43.149399,34.059058,34.054044,39.075238,38.253202,32.65,33.97028,34.136437,34.723782,27.529078,27.532514,26.021177,25.706271,26.074567,42.29991,36.058347,40.99273,41.864289,27.637592,42.998519,44.891436,29.194381,27.175606,28.719324,26.263994,31.557534,43.652326,41.136423,42.325404,35.373141,40.571953,35.157511,26.019388,39.068602,29.508318,25.715322,44.246005,44.886634,29.441555,29.811721,29.552293,40.26379,29.616223,29.489828,25.919958,31.993732,31.996372,43.047503,42.53528,41.85203,31.994252,39.93288,42.986945,41.978879,41.914749,32.381556,30.695111,40.267897,24.577137,32.374295,34.951752,38.192874,38.510527,45.183193,25.778461,29.513516,30.344436,40.818771,33.391004,41.033987,38.310941,44.164112,30.610685,40.73227,41.515748,26.275409,40.730364,39.541557,29.948091,36.846005,36.876164,39.199842,41.135013,36.167759,40.727216,34.327352,39.198506,40.715422,36.219543,43.457123,43.469763,30.832183,33.753944,41.441918,41.220537,35.42402,28.850774,35.622376,31.85131,41.281294,28.427496,28.295161,26.673062,31.968599,32.480948,31.398176,31.749688,37.953062,39.95995,33.470785,31.590023,40.657477,48.37364,33.041291,40.424825,41.388359,32.812227,41.186932,39.190353,42.055382,34.583194,41.924989,27.882109,43.634917,45.515096,35.240552,40.849412,32.420785,41.726973,35.081794,40.148962,39.126549,38.275545,38.393003,41.096622,32.685367,26.684044,38.751908,21.30847,38.318495,37.542324,40.331254,33.906306,35.789744,40.575012,39.572905,26.172737,26.157941,46.277514,41.509186,37.2926,35.116465,43.19246,41.509186,37.271388,44.099197,33.398085,31.879834,33.748562,38.578139,33.750177,31.421951,15.156223,18.406539,38.410507,40.475462,27.336241,34.10077,34.101547,41.524037,41.826077,32.61965,47.490701,43.548712,37.796309,37.112707,36.181213,43.019269,18.437531,40.684576,30.205984,34.918106,38.301727,28.74804,29.522182,32.590171,32.717307,37.23883,37.266958,44.860123,47.66582,38.217616,30.643524,40.725611,44.801153,29.993323,28.895232,41.114401,32.505634,34.243687,47.245494,29.940298,33.481119,39.746693,37.951128,38.624318,27.453503,32.227443,34.540401,43.122571,27.155589,40.914484,40.720554,28.66272,38.573235,30.295197,42.505131,43.111676,47.259537,30.471947,34.015686,27.959412,32.417921,38.94236,42.563122,25.810088,31.462845,32.834948,32.586731,32.735814,31.770097,31.777644,33.154341,35.408822,40.658568,32.135321,36.139538,29.3528,33.420881,41.788996,41.607584,39.742491,32.75427,41.508148,39.485618,42.115178,42.277503,31.772345,36.161169,42.998116,25.788419,43.19334,42.685396,40.741959,39.288013,35.088206,40.442417,41.985304,42.519464,26.158576,38.032342,29.212368,29.508424,29.373265,26.175246,37.900875,34.206389,36.753146,37.22158,40.728291,44.333316,34.527953,32.513789,33.457023,45.03786,30.196089,30.779179,39.63965,38.880719,31.553515,27.370718,33.75919,37.691512,29.148851,25.678453,25.640998,34.051291,46.618334,41.223906,39.437643,39.30279,43.213232,46.618034,39.987597,34.984899,39.985618,32.682949,32.655799],[-79.14506900000001,-106.629298,-75.91592,-73.163545,-119.020654,-157.75778,-119.247054,144.747679,-67.14212999999999,-117.90963,-97.06914399999999,-149.871,-147.760793,-149.580175,-131.649562,-134.487648,-149.118654,-98.11911499999999,-73.769379,-77.067312,-105.859789,-101.748848,-149.857649,-149.872299,-99.895188,-117.044089,-105.012747,-117.352826,-84.395391,-84.393159,-95.853981,-97.738978,-112.025979,-87.77476900000001,-76.680689,-112.057366,-84.77741,-66.1545,-85.561969,-85.177847,-97.133092,-73.976083,-97.463733,-106.651437,-78.865104,-86.79116,-71.104465,-104.849106,-108.509563,-111.565624,-119.01121,-77.346647,-97.30005,-98.49244299999999,-110.947171,-116.286069,-75.420385,-86.626766,-71.613805,-66.11220899999999,-120.499816,-118.238159,-92.640691,-112.168389,-82.874059,-122.301633,-93.323273,-110.857821,-117.38012,-71.20893700000001,-71.05154,-82.108705,-80.781796,-80.141167,-85.58029999999999,-80.142769,-98.12584699999999,-87.930723,-87.86562000000001,-101.514653,-96.77215200000001,-97.68462,-85.66515,-78.878101,-98.25304800000001,-111.836168,-105.509858,-97.490999,-111.380434,-121.152411,-78.849655,-80.578035,-97.677288,-97.47588500000001,-122.132851,-95.046244,-79.16870400000001,-111.708726,-64.9637,-111.874651,-80.00879500000001,-104.505543,-77.50788900000001,-87.890021,-94.74212199999999,-80.01977100000001,-73.19064899999999,-73.45282899999999,-77.526054,-87.49082300000001,-82.043435,-76.251591,-96.942042,-104.8199,-107.827011,-107.907649,-84.380325,-73.19064899999999,-82.47752699999999,-80.3856,-81.69178100000001,-83.00218,-80.83784300000001,-78.187517,-85.29781800000001,-88.40139600000001,-120.321549,-81.038982,-84.58092000000001,-105.157937,-80.979724,-82.643575,-98.174764,-93.28035800000001,-107.544964,-91.670085,-97.39638100000001,-104.81751,-94.740863,-106.324898,-78.40404100000001,-77.99668800000001,-119.228991,-78.123706,-96.872156,-85.760138,-104.848777,-104.864252,-83.037998,-100.899841,-104.991198,-106.807471,-80.221052,-104.860137,-106.349506,-93.62325300000001,-117.297825,-107.874147,-75.487951,-116.024888,-78.832166,-115.568591,-106.253194,-121.850049,-106.476018,-106.483474,-106.474224,-106.440946,-86.184605,-74.13574199999999,-86.012396,-123.089385,-94.178449,-116.923984,-122.591006,-100.875929,-82.372325,-80.133263,-81.90372499999999,-80.502088,-80.89795599999999,-81.25613300000001,-80.126777,-111.485449,-81.80836499999999,-88.449685,-77.64440999999999,-104.98429,-77.41508,-119.785296,-99.10973300000001,-94.38782500000001,-97.222229,-81.18208799999999,-100.875929,-97.055851,-108.585533,-118.249215,-84.38266299999999,-72.61246,-97.034978,-97.680628,-98.343144,-85.670052,-82.241882,-107.323402,-77.781167,144.774507,-116.681682,-85.132546,-72.66005800000001,-72.603666,-89.054704,-99.721789,-78.848388,-81.601333,-95.467788,-93.26245,-95.374527,-115.030473,-111.974176,-82.456379,-81.436646,-82.468082,-76.861121,-104.90765,-95.39382999999999,-95.38754299999999,-157.863124,-82.373091,-98.12773799999999,-78.930114,-97.714124,-97.67513,-99.732563,-95.311156,-97.705624,-80.195019,-112.033754,-115.498883,-86.15328599999999,-97.58504000000001,-111.836757,-90.06042600000001,-81.59002599999999,-88.902535,-73.782718,-73.816226,-97.067347,-80.213994,-81.912301,-97.32747999999999,-94.67554800000001,-97.91184800000001,-97.91529800000001,-78.879949,-119.107939,-118.969998,-100.418034,-83.91677300000001,-152.40583,-111.821629,-80.48913,-80.350939,-75.647865,-104.820095,-99.23665800000001,-106.763654,-103.729316,-95.311969,-101.845109,-82.64112799999999,-84.544855,-71.205243,-90.96348,-105.039886,-78.706205,-118.231341,-118.239721,-77.54492500000001,-85.761072,-111.59,-118.277969,-114.28534,-92.307733,-99.44792,-99.47798299999999,-80.180662,-80.29266699999999,-97.512181,-71.10634,-115.225127,-75.175347,-87.847157,-82.53995500000001,-71.466598,-122.957279,-82.174886,-80.239852,-100.459986,-98.19820900000001,-97.133016,-93.37318,-96.040333,-122.876967,-119.027145,-122.395233,-89.88253,-80.180009,-108.574044,-98.57189700000001,-80.336037,-85.38972,-93.326622,-98.49118,-95.43038300000001,-98.348291,-76.676598,-98.474386,-98.547528,-80.154961,-102.076911,-102.099482,-87.907819,-113.791809,-71.398006,-102.074372,-74.9575,-82.429739,-91.65540900000001,-83.398858,-86.298258,-88.041554,-74.286962,-81.751524,-86.30510700000001,-120.413661,-79.011619,-90.381379,-93.36866000000001,-80.19313200000001,-98.576718,-95.449219,-77.842624,-111.609914,-78.45010499999999,-77.48332600000001,-93.984712,-81.631404,-73.553488,-74.111023,-80.09863799999999,-74.174986,-119.698078,-90.077862,-76.28316599999999,-76.22287,-78.145078,-100.759979,-86.77927800000001,-73.554062,-77.895749,-78.14630200000001,-74.003839,-115.982801,-73.432728,-73.428887,-92.63684000000001,-117.833027,-74.368094,-112.018854,-97.596734,-97.878198,-95.974236,-92.28482,-95.898764,-81.333814,-81.35229,-80.09224500000001,-99.901813,-84.982792,-103.521451,-106.486786,-91.785217,-75.16547,-112.07309,-84.158208,-74.22792800000001,-99.977576,-111.376034,-79.96081100000001,-75.072108,-96.83561,-85.101465,-94.68371500000001,-104.952706,-118.144625,-83.387856,-81.819138,-70.25004199999999,-122.676329,-101.6673,-73.93306200000001,-97.19690199999999,-71.457116,-106.634933,-111.659712,-94.786749,-104.610556,-105.116869,-85.109729,-117.082074,-80.252606,-77.47775900000001,-157.853858,-77.471987,-77.433933,-75.95110699999999,-98.501355,-78.779608,-122.362639,-119.80945,-97.70071299999999,-97.35047,-119.27602,-90.580731,-80.061161,-101.866116,-77.58635599999999,-90.580731,-79.947238,-103.264685,-104.524837,-106.574609,-117.875155,-121.499567,-117.880487,-100.464032,145.703679,-66.106714,-75.571609,-96.960804,-82.52978899999999,-117.297624,-117.271651,-90.57943,-103.660462,-117.023264,-122.291143,-96.72369,-122.401505,-113.579872,-115.317586,-96.07687300000001,-66.00470300000001,-111.961248,-95.45867800000001,-120.444791,-76.62949500000001,-81.300144,-98.39182700000001,-116.921245,-117.165183,-121.774294,-93.129413,-93.23067500000001,-117.418183,-77.495723,-86.97432000000001,-73.24052399999999,-73.07364200000001,-90.502053,-99.12123800000001,-80.6575,-84.960688,-119.020104,-122.448,-81.33879899999999,-112.079308,-104.971246,-121.289949,-90.19991,-80.409992,-111.000179,-117.264687,-77.62568,-80.212243,-72.670754,-111.478368,-82.10854399999999,-121.468553,-82.985855,-96.404939,-76.123955,-122.452902,-84.354361,-90.39033999999999,-82.372276,-99.767905,-105.153945,-114.479099,-80.311679,-100.440089,-97.124387,-97.316894,-97.338915,-106.500055,-106.480896,-94.970619,-89.550034,-74.214218,-110.926022,-95.86430900000001,-98.545312,-94.043166,-87.60358100000001,-87.65960699999999,-104.841405,-117.166135,-81.188562,-87.40695100000001,-75.958203,-71.761617,-106.434949,-115.16756,-78.187517,-80.21634299999999,-77.70550799999999,-96.682676,-74.19050900000001,-76.62484499999999,-106.618968,-79.960791,-91.660432,-96.405974,-98.269651,-78.498284,-99.782787,-98.57765999999999,-100.847867,-97.67025599999999,-76.87912300000001,-119.077197,-76.060064,-76.618652,-74.00627,-72.75174199999999,-117.293781,-93.74919800000001,-112.026183,-92.80171199999999,-84.376921,-86.10411000000001,-77.761816,-77.22918,-97.133522,-99.490385,-117.991922,-97.339591,-98.157763,-80.45547000000001,-80.42234000000001,-118.217121,-120.559359,-77.071806,-77.96108,-78.647008,-70.87424,-120.557991,-76.66360299999999,-81.20403399999999,-76.758593,-114.635879,-114.612181],[5.547570236667276,5.483420118779979,3,3,3,3,3,3.435061561946088,5.934910806038285,3.318487167764811,3,3,3,3.180208399425292,3,3,3,4.192789745010902,4.305184685838265,3,3.716003135966583,4.358743211603835,5.417827884802192,3.537765664962601,3,3.537765664962601,3,3.318487167764811,3.318487167764811,8.203980779687726,4.192789745010902,5.579133356897509,3.318487167764811,4.867067833879256,7.330799065679987,3,3,3.180208399425292,3.435061561946088,3,3,3,3.537765664962601,3,3,4.410748322168053,3.318487167764811,3.435061561946088,3,3.318487167764811,5.61036937167653,3,3,3,3,3.795478360796673,3,3.318487167764811,3,4.305184685838265,3.940723896193989,3,3.435061561946088,3,3,3,3.180208399425292,3,3.716003135966583,8.80924655927053,3.180208399425292,3,3.870123123892177,3.318487167764811,3.180208399425292,4.192789745010902,6.692294812474142,4.133575207633986,9.374729026414737,3.940723896193989,3,3,3,5.483420118779979,3.435061561946088,4.133575207633986,3.435061561946088,3,3.537765664962601,3,4.510592891871291,3.630617271520083,3,3.180208399425292,3,3,3,3.318487167764811,3.435061561946088,3.180208399425292,3,4.305184685838265,3.180208399425292,3.716003135966583,3.180208399425292,6.1788311903537,3,3.795478360796673,3,3,3,4.651420391416631,3,3.318487167764811,3,3,3.435061561946088,5.483420118779979,3,3.716003135966583,4.192789745010902,3.940723896193989,5.579133356897509,3,4.07203589747571,3,3,4.987258698294508,3.435061561946088,3,3.940723896193989,3,3,3,3.435061561946088,4.358743211603835,3.795478360796673,3.716003135966583,3,3.630617271520083,3,3,3,3.180208399425292,9.090861867245238,3,5.138797349086906,3,5.547570236667276,4.07203589747571,3,3,3.940723896193989,3,3.716003135966583,3.318487167764811,3.940723896193989,3.630617271520083,3.940723896193989,3,3.180208399425292,3.180208399425292,3.180208399425292,3.180208399425292,4.133575207633986,6.8053940096738,3.318487167764811,20,3,3,3.180208399425292,3.870123123892177,3.870123123892177,3,3.630617271520083,4.00787439973505,10.02469027231711,4.00787439973505,3,3.716003135966583,19.31339597587397,4.07203589747571,3,3.537765664962601,4.907816650382954,3,3.180208399425292,3.716003135966583,3,4.605558044699242,3.180208399425292,3.435061561946088,4.249924622046098,3.630617271520083,3.318487167764811,3,3.716003135966583,4.605558044699242,3.318487167764811,3,4.133575207633986,3,3,3.870123123892177,3.716003135966583,3.940723896193989,5.671899444701964,3.537765664962601,3.180208399425292,3,3,5.211314605432596,3,3,4.00787439973505,3,4.410748322168053,3,3.318487167764811,3,3.180208399425292,3.180208399425292,3,3.537765664962601,3,3,3,3.318487167764811,3.435061561946088,5.316509354334065,3,3,7.290916685632974,3,3.180208399425292,4.410748322168053,3,3,3.537765664962601,4.07203589747571,7.525403451415674,3,8.64024252288614,4.651420391416631,5.138797349086906,3,4.651420391416631,3,3.630617271520083,3.180208399425292,3,3,6.045430933622619,3.940723896193989,3.870123123892177,3,3.180208399425292,3,3.435061561946088,4.510592891871291,3,3.318487167764811,5.761974938452427,13.22172677271563,3,3.795478360796673,3,3.716003135966583,3.537765664962601,3,4.358743211603835,3,3.318487167764811,3.180208399425292,3.435061561946088,3.180208399425292,3,3,11.84511871759328,3.435061561946088,4.651420391416631,3.180208399425292,3,3,4.82558462718661,7.230453919599499,3.180208399425292,4.07203589747571,4.305184685838265,3,3,6.152547985153758,3,3.180208399425292,3.716003135966583,3.870123123892177,3.180208399425292,4.00787439973505,4.696296104986255,3.318487167764811,5.906709704657183,3.537765664962601,3,3,4.192789745010902,3,3,4.740246247784354,3,3,3.180208399425292,4.740246247784354,3,3,3.180208399425292,3.537765664962601,3,3,3,3.180208399425292,6.78301677921819,4.133575207633986,3,4.605558044699242,3.795478360796673,3,4.133575207633986,4.783325832031172,3,3,3.716003135966583,3,5.138797349086906,3,3.318487167764811,3.180208399425292,3,3,3,3,8.336682284778464,3,9.03259352726023,3.180208399425292,3.180208399425292,3,3,3.180208399425292,3,4.133575207633986,3.940723896193989,3.537765664962601,4.07203589747571,3,3.537765664962601,3,4.305184685838265,3.716003135966583,4.133575207633986,6.332682086608409,3.318487167764811,3.940723896193989,3.630617271520083,9.134223961740425,6.692294812474142,3,3,4.192789745010902,3.180208399425292,3.180208399425292,4.133575207633986,6.431850184131735,3,3,3,6.282106052764985,7.448492358924882,4.192789745010902,3.435061561946088,3.180208399425292,3,4.867067833879256,5.175307809730442,3,5.064176835753901,6.692294812474142,3,3,3,3,4.461327820795872,3.716003135966583,3.318487167764811,3,3,4.00787439973505,3,3,4.651420391416631,3.318487167764811,4.461327820795872,3,3.537765664962601,6.480492495568707,3.795478360796673,3.180208399425292,3.940723896193989,3,3,4.249924622046098,3,3.537765664962601,3.180208399425292,3,3,4.305184685838265,9.805805918071947,3,3,4.192789745010902,3.716003135966583,3.940723896193989,3.716003135966583,4.55864097763758,3.435061561946088,3.630617271520083,3.630617271520083,3,3,3,4.133575207633986,3.716003135966583,4.305184685838265,3.716003135966583,7.89333260538477,5.138797349086906,3,4.510592891871291,3,5.641288244910815,4.651420391416631,3.716003135966583,3.940723896193989,5.246838022667934,3,3.716003135966583,3.180208399425292,3.318487167764811,5.906709704657183,4.510592891871291,5.450810361416188,3.870123123892177,3,3.940723896193989,4.696296104986255,5.579133356897509,3,4.461327820795872,3,3.630617271520083,7.803773383824837,3,6.152547985153758,3.180208399425292,5.990616602497289,6.622922537753959,4.358743211603835,3,3,3.180208399425292,3.716003135966583,3,5.671899444701964,3.180208399425292,3.180208399425292,3,3.537765664962601,3.435061561946088,3,3,4.192789745010902,5.175307809730442,3.180208399425292,3,3.435061561946088,3,5.732234417623458,3,3,3.940723896193989,3,3,3.318487167764811,4.192789745010902,3,5.483420118779979,3,6.552343517221249,3,3.180208399425292,3.630617271520083,4.82558462718661,4.249924622046098,3,3.435061561946088,3.180208399425292,3,3,3.630617271520083,5.281897021587314,3.318487167764811,4.249924622046098,4.305184685838265,3,3.630617271520083,3,3,3.318487167764811,3,3,3,3,3,3.318487167764811,3.180208399425292,3,3,3,4.55864097763758,3.180208399425292,3.180208399425292,3,3,3,3,11.92634722745175,3,3.180208399425292,3.630617271520083,5.138797349086906,4.07203589747571,3,6.456247345688668,3.180208399425292,3,4.07203589747571,3,3.870123123892177,3.795478360796673,3.180208399425292,3.435061561946088,3,3,3,7.467833242221873,4.696296104986255,3,3.795478360796673,3.180208399425292,3.795478360796673,3.537765664962601,3.318487167764811,3.630617271520083,3.435061561946088,4.55864097763758,4.305184685838265,3,3,4.07203589747571,3,3.435061561946088,4.305184685838265,3,3.795478360796673],null,null,{\"interactive\":true,\"className\":\"\",\"stroke\":true,\"color\":\"black\",\"weight\":1,\"opacity\":0.5,\"fill\":true,\"fillColor\":[\"#A65628\",\"#FF7F00\",\"#377EB8\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#A65628\",\"#4DAF4A\",\"#A65628\",\"#4DAF4A\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#A65628\",\"#E41A1C\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#E41A1C\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#FF7F00\",\"#E41A1C\",\"#A65628\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#4DAF4A\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#4DAF4A\",\"#4DAF4A\",\"#A65628\",\"#A65628\",\"#4DAF4A\",\"#A65628\",\"#4DAF4A\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#4DAF4A\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#999999\",\"#FF7F00\",\"#984EA3\",\"#4DAF4A\",\"#A65628\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#E41A1C\",\"#A65628\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#4DAF4A\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#E41A1C\",\"#984EA3\",\"#A65628\",\"#E41A1C\",\"#E41A1C\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#999999\",\"#377EB8\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#4DAF4A\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#984EA3\",\"#A65628\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#999999\",\"#984EA3\",\"#4DAF4A\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#4DAF4A\",\"#377EB8\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#4DAF4A\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#984EA3\",\"#A65628\",\"#999999\",\"#984EA3\",\"#A65628\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#E41A1C\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#4DAF4A\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#4DAF4A\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#4DAF4A\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#377EB8\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#4DAF4A\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#4DAF4A\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#4DAF4A\",\"#984EA3\",\"#4DAF4A\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#984EA3\",\"#4DAF4A\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#4DAF4A\",\"#A65628\",\"#A65628\",\"#984EA3\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#4DAF4A\",\"#4DAF4A\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#4DAF4A\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#4DAF4A\",\"#984EA3\",\"#A65628\",\"#984EA3\",\"#4DAF4A\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#984EA3\",\"#4DAF4A\",\"#A65628\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#984EA3\",\"#984EA3\",\"#984EA3\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#A65628\",\"#984EA3\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#984EA3\",\"#FF7F00\"],\"fillOpacity\":0.7},null,null,[\"<b>SW VIRGINIA REG JAIL AUTH-ABG FAC<\\/b><br>VA | Non-Dedicated<br>Peak: 47 (2025-09-01)<br>Mean ADP: 1\",\"<b>ALBUQUERQUE HOLD ROOM<\\/b><br>NM | Hold/Staging<br>Peak: 45 (2025-03-25)<br>Mean ADP: 2\",\"<b>ABRAXAS ACADEMY DETENTION CENTER<\\/b><br>PA | Family/Youth<br>Peak: 1 (2025-08-30)<br>Mean ADP: 0\",\"<b>ADDISON COUNTY JAIL<\\/b><br>VT | Non-Dedicated<br>Peak: 1 (2025-06-07)<br>Mean ADP: 0\",\"<b>ADVENTIST HEALTH BAKERSFIELD<\\/b><br>CA | Medical<br>Peak: 1 (2025-02-04)<br>Mean ADP: 0\",\"<b>ADVENTIST HEALTH CASTLE<\\/b><br>HI | Medical<br>Peak: 1 (2025-05-22)<br>Mean ADP: 0\",\"<b>ADVENTIST HEALTH DELANO<\\/b><br>CA | Medical<br>Peak: 1 (2024-11-10)<br>Mean ADP: 0\",\"<b>GUAM ERO HOLD ROOM<\\/b><br>GU | Hold/Staging<br>Peak: 4 (2025-05-22)<br>Mean ADP: 0\",\"<b>AGUADILLA SPC<\\/b><br>PR | Hold/Staging<br>Peak: 60 (2025-03-20)<br>Mean ADP: 3.3\",\"<b>ANAHEIM GLOBAL MEDICAL CENTER<\\/b><br>CA | Medical<br>Peak: 3 (2025-08-29)<br>Mean ADP: 0.3\",\"<b>ALTRU HOSPITAL GRAND FORKS<\\/b><br>ND | Medical<br>Peak: 1 (2025-06-02)<br>Mean ADP: 0\",\"<b>COOK INLET PRETRIAL, ANCH<\\/b><br>AK | Non-Dedicated<br>Peak: 1 (2025-02-26)<br>Mean ADP: 0\",\"<b>FAIRBANKS CORR CTR<\\/b><br>AK | Non-Dedicated<br>Peak: 1 (2025-08-07)<br>Mean ADP: 0\",\"<b>HIGHLAND MTN COR CTR<\\/b><br>AK | Federal<br>Peak: 2 (2025-07-08)<br>Mean ADP: 0.1\",\"<b>KETCHIKAN REGIONAL CC<\\/b><br>AK | Non-Dedicated<br>Peak: 1 (2025-05-16)<br>Mean ADP: 0\",\"<b>LEMON CREEK, JUNEAU,AK<\\/b><br>AK | Federal<br>Peak: 1 (2025-08-25)<br>Mean ADP: 0\",\"<b>MATSU PRETRIAL, PALMER AK<\\/b><br>AK | Non-Dedicated<br>Peak: 1 (2025-02-01)<br>Mean ADP: 0\",\"<b>ALAMO POLICE DEPT.<\\/b><br>TX | Non-Dedicated<br>Peak: 14 (2025-05-08)<br>Mean ADP: 0.1\",\"<b>ALBANY HOLDROOM<\\/b><br>NY | Hold/Staging<br>Peak: 16 (2025-07-15)<br>Mean ADP: 1.2\",\"<b>ALEXANDRIA CITY JAIL<\\/b><br>VA | Federal<br>Peak: 1 (2025-05-21)<br>Mean ADP: 0\",\"<b>ALAMOSA HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 7 (2025-08-19)<br>Mean ADP: 0.2\",\"<b>AMARILLO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 17 (2025-09-03)<br>Mean ADP: 2.1\",\"<b>ANCHORAGE JAIL<\\/b><br>AK | Federal<br>Peak: 43 (2025-06-09)<br>Mean ADP: 3.3\",\"<b>ANCHORAGE SUB-OFFICE HOLD ROOM<\\/b><br>AK | Hold/Staging<br>Peak: 5 (2025-09-12)<br>Mean ADP: 0\",\"<b>ANSON GENERAL HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2025-06-25)<br>Mean ADP: 0\",\"<b>ALVARADO PARKWAY INSTITUTE<\\/b><br>CA | Medical<br>Peak: 5 (2025-04-22)<br>Mean ADP: 1\",\"<b>ARAPAHOE COUNTY JAIL<\\/b><br>CO | Non-Dedicated<br>Peak: 1 (2025-04-30)<br>Mean ADP: 0\",\"<b>ARROWHEAD REGIONAL MED CENTER<\\/b><br>CA | Medical<br>Peak: 3 (2025-08-29)<br>Mean ADP: 0.1\",\"<b>ATLANTA PRETRIAL DETN CTR<\\/b><br>GA | Federal<br>Peak: 3 (2025-04-27)<br>Mean ADP: 0\",\"<b>ATLANTA DIST. HOLD RM<\\/b><br>GA | Hold/Staging<br>Peak: 168 (2025-06-25)<br>Mean ADP: 42.1\",\"<b>ATHENS, TX HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 14 (2025-09-23)<br>Mean ADP: 0.1\",\"<b>AUSTIN DRO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 48 (2025-09-17)<br>Mean ADP: 15.2\",\"<b>ARIZONA STATE PRISON - YUMA<\\/b><br>AZ | Non-Dedicated<br>Peak: 3 (2025-04-03)<br>Mean ADP: 0\",\"<b>BALDWIN COUNTY COR. CENTER<\\/b><br>AL | Non-Dedicated<br>Peak: 28 (2025-02-07)<br>Mean ADP: 1.4\",\"<b>BALTIMORE HOLD ROOM<\\/b><br>MD | Hold/Staging<br>Peak: 120 (2025-06-13)<br>Mean ADP: 29.3\",\"<b>BANNER UNIVERSITY MEDICAL PHOENIX<\\/b><br>AZ | Medical<br>Peak: 1 (2024-12-31)<br>Mean ADP: 0.2\",\"<b>BARTOW CO JAIL<\\/b><br>GA | Non-Dedicated<br>Peak: 1 (2025-01-16)<br>Mean ADP: 0\",\"<b>BAYAMON HOSPITAL<\\/b><br>PR | Medical<br>Peak: 2 (2025-06-04)<br>Mean ADP: 0.1\",\"<b>BAY COUNTY<\\/b><br>FL | Non-Dedicated<br>Peak: 4 (2025-02-01)<br>Mean ADP: 0.1\",\"<b>BRONSON BATTLE CREEK HOSP<\\/b><br>MI | Medical<br>Peak: 1 (2024-10-22)<br>Mean ADP: 0\",\"<b>BEDFORD CITY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2025-08-16)<br>Mean ADP: 0\",\"<b>BELLEVUE HOSPITAL, MANHAT<\\/b><br>NY | Medical<br>Peak: 1 (2025-06-20)<br>Mean ADP: 0\",\"<b>BELL COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 5 (2025-06-06)<br>Mean ADP: 0.5\",\"<b>BERNALILLO COUNTY DET CTR<\\/b><br>NM | Dedicated<br>Peak: 1 (2025-05-28)<br>Mean ADP: 0\",\"<b>BUFFALO GENERAL HOSPITAL<\\/b><br>NY | Medical<br>Peak: 1 (2025-04-15)<br>Mean ADP: 0.1\",\"<b>BIRMINGHAM HOLD ROOM<\\/b><br>AL | Hold/Staging<br>Peak: 18 (2025-09-10)<br>Mean ADP: 1.2\",\"<b>BETH ISRAEL DEACONESS HOSP<\\/b><br>MA | Medical<br>Peak: 3 (2025-02-14)<br>Mean ADP: 0.4\",\"<b>BI INCORORATED, GEO GROUP COMPANY<\\/b><br>CO | Dedicated<br>Peak: 4 (2025-03-13)<br>Mean ADP: 0.1\",\"<b>BILLINGS HOLD ROOM<\\/b><br>MT | Hold/Staging<br>Peak: 1 (2025-06-21)<br>Mean ADP: 0\",\"<b>BANNER IRONWOOD MED CTR<\\/b><br>AZ | Medical<br>Peak: 3 (2025-02-10)<br>Mean ADP: 0.2\",\"<b>BAKERFIELD HOLD<\\/b><br>CA | Hold/Staging<br>Peak: 49 (2025-04-30)<br>Mean ADP: 7.1\",\"<b>BOWLING GREEN HOLD ROOM<\\/b><br>KY | Hold/Staging<br>Peak: 1 (2024-10-09)<br>Mean ADP: 0\",\"<b>BLACKWELL REGIONAL HOSPITAL<\\/b><br>OK | Medical<br>Peak: 1 (2024-11-22)<br>Mean ADP: 0\",\"<b>BAPTIST MEDICAL CENTER<\\/b><br>TX | Medical<br>Peak: 1 (2024-12-07)<br>Mean ADP: 0.1\",\"<b>BANNER MEDICAL CTR TUCSON<\\/b><br>AZ | Medical<br>Peak: 1 (2025-07-01)<br>Mean ADP: 0.2\",\"<b>BOISE HOLD ROOM<\\/b><br>ID | Hold/Staging<br>Peak: 8 (2025-06-04)<br>Mean ADP: 0.8\",\"<b>USP CANAAN<\\/b><br>PA | Federal<br>Peak: 1 (2025-02-07)<br>Mean ADP: 0\",\"<b>NASHVILLE COMM. CORR.<\\/b><br>TN | Federal<br>Peak: 3 (2025-02-11)<br>Mean ADP: 0\",\"<b>DEVENS FMC<\\/b><br>MA | Federal<br>Peak: 1 (2025-06-20)<br>Mean ADP: 0\",\"<b>GUAYNABO MDC (SAN JUAN)<\\/b><br>PR | Federal<br>Peak: 16 (2024-10-01)<br>Mean ADP: 2.8\",\"<b>LOMPOC FCI<\\/b><br>CA | Federal<br>Peak: 10 (2024-10-11)<br>Mean ADP: 0.2\",\"<b>LOS ANGELES MET.DET.CTR.<\\/b><br>CA | Federal<br>Peak: 1 (2025-05-20)<br>Mean ADP: 0\",\"<b>OAKDALE FED.DET.CENTER<\\/b><br>LA | Federal<br>Peak: 4 (2025-04-01)<br>Mean ADP: 0\",\"<b>PHOENIX FED.CORR.INST.<\\/b><br>AZ | Federal<br>Peak: 1 (2025-04-10)<br>Mean ADP: 0\",\"<b>MCRAE CORRECTIONAL FACILITY, CCA<\\/b><br>GA | Federal<br>Peak: 1 (2025-07-25)<br>Mean ADP: 0\",\"<b>SEATAC FED.DET.CENTER<\\/b><br>WA | Federal<br>Peak: 1 (2025-01-28)<br>Mean ADP: 0\",\"<b>SPRINGFIELD FED.MED.CNTR<\\/b><br>MO | Federal<br>Peak: 2 (2024-10-10)<br>Mean ADP: 0.1\",\"<b>TUCSON FED.CORR.INST.<\\/b><br>AZ | Federal<br>Peak: 1 (2025-03-04)<br>Mean ADP: 0\",\"<b>FCI VICTORVILLE<\\/b><br>CA | Federal<br>Peak: 7 (2024-12-26)<br>Mean ADP: 0\",\"<b>BOSTON HOLDROOM<\\/b><br>MA | Hold/Staging<br>Peak: 206 (2025-05-13)<br>Mean ADP: 18.6\",\"<b>BOSTON SPC<\\/b><br>MA | Dedicated<br>Peak: 2 (2025-09-09)<br>Mean ADP: 0.1\",\"<b>BRADFORD COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-01-14)<br>Mean ADP: 0\",\"<b>BREVARD COUNTY JAIL COMPLEX<\\/b><br>FL | Non-Dedicated<br>Peak: 9 (2025-05-07)<br>Mean ADP: 1.3\",\"<b>BROWARD GENERAL MEDICAL CENTER<\\/b><br>FL | Medical<br>Peak: 3 (2025-04-23)<br>Mean ADP: 0.4\",\"<b>BRONSON METHODIST HOSPITAL<\\/b><br>MI | Medical<br>Peak: 2 (2024-11-23)<br>Mean ADP: 0.2\",\"<b>BROWARD COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 14 (2025-07-26)<br>Mean ADP: 3.4\",\"<b>BROOKS COUNTY JAIL (CONTRACT)<\\/b><br>TX | Federal<br>Peak: 90 (2025-08-19)<br>Mean ADP: 4.5\",\"<b>BROWN COUNTY JAIL<\\/b><br>WI | Non-Dedicated<br>Peak: 13 (2025-06-12)<br>Mean ADP: 0.7\",\"<b>BROADVIEW SERVICE STAGING<\\/b><br>IL | Hold/Staging<br>Peak: 245 (2025-09-20)<br>Mean ADP: 31.7\",\"<b>BIG SPRING HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 10 (2025-04-11)<br>Mean ADP: 0.9\",\"<b>BAYLOR SCOTT WHITE MD CTR<\\/b><br>TX | Medical<br>Peak: 1 (2024-11-16)<br>Mean ADP: 0.1\",\"<b>BAYLOR SCOTT WHITE MED RR<\\/b><br>TX | Medical<br>Peak: 1 (2024-10-28)<br>Mean ADP: 0\",\"<b>COREWELL HLTH GR HOSP-BUTTERWORTH<\\/b><br>MI | Medical<br>Peak: 1 (2025-08-29)<br>Mean ADP: 0\",\"<b>BUFFALO HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 45 (2025-06-16)<br>Mean ADP: 1.6\",\"<b>BURNET COUNTY JAIL<\\/b><br>TX | Federal<br>Peak: 4 (2025-06-23)<br>Mean ADP: 0\",\"<b>CACHE CO. JAIL<\\/b><br>UT | Federal<br>Peak: 13 (2025-09-19)<br>Mean ADP: 0.3\",\"<b>CAMPBELL COUNTY JAIL<\\/b><br>WY | Non-Dedicated<br>Peak: 4 (2025-08-14)<br>Mean ADP: 0.1\",\"<b>CAMERON COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2025-07-03)<br>Mean ADP: 0\",\"<b>CASCADE COUNTY JAIL, MT<\\/b><br>MT | Federal<br>Peak: 5 (2025-08-03)<br>Mean ADP: 0.7\",\"<b>CSP-SACRAMENTO<\\/b><br>CA | Non-Dedicated<br>Peak: 1 (2025-05-22)<br>Mean ADP: 0\",\"<b>BUFFALO USBP HOLD ROOM<\\/b><br>NY | Federal<br>Peak: 20 (2025-09-17)<br>Mean ADP: 0.2\",\"<b>Cabarrus County Jail<\\/b><br>NC | Non-Dedicated<br>Peak: 6 (2025-07-31)<br>Mean ADP: 0.7\",\"<b>CROSS CREEK HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2024-10-25)<br>Mean ADP: 0\",\"<b>CEDAR CREST HOSP TREAT<\\/b><br>TX | Medical<br>Peak: 2 (2025-06-23)<br>Mean ADP: 0\",\"<b>CONTRA COSTA REG MED CTR<\\/b><br>CA | Medical<br>Peak: 1 (2025-05-22)<br>Mean ADP: 0\",\"<b>CENTRACARE RICE MEMORIAL HOSP<\\/b><br>MN | Medical<br>Peak: 1 (2025-01-13)<br>Mean ADP: 0.1\",\"<b>CENTRA HEALTH<\\/b><br>VA | Medical<br>Peak: 1 (2024-10-10)<br>Mean ADP: 0.1\",\"<b>CASA GRANDE REG. MED. CENTER<\\/b><br>AZ | Medical<br>Peak: 3 (2025-05-05)<br>Mean ADP: 0.6\",\"<b>CHARLOTTE AMALIE HOLDROOM<\\/b><br>VI | Hold/Staging<br>Peak: 4 (2025-01-24)<br>Mean ADP: 0.2\",\"<b>CHANDLER REG MED CTR<\\/b><br>AZ | Medical<br>Peak: 2 (2025-01-11)<br>Mean ADP: 0\",\"<b>CHARLESTON COUNTY CORRECT<\\/b><br>SC | Federal<br>Peak: 1 (2025-03-15)<br>Mean ADP: 0\",\"<b>CHAVEZ DET CRT<\\/b><br>NM | Non-Dedicated<br>Peak: 16 (2025-09-17)<br>Mean ADP: 2.1\",\"<b>CHESTERFIELD CO. JAIL<\\/b><br>VA | Non-Dedicated<br>Peak: 2 (2025-07-08)<br>Mean ADP: 0\",\"<b>CHICAGO HOLD ROOM<\\/b><br>IL | Hold/Staging<br>Peak: 7 (2025-09-21)<br>Mean ADP: 0.3\",\"<b>CHI ST LUKE'S HEALTH MEM<\\/b><br>TX | Medical<br>Peak: 2 (2025-07-13)<br>Mean ADP: 0\",\"<b>CHARLESTON, SC HOLD ROOM<\\/b><br>SC | Hold/Staging<br>Peak: 69 (2025-06-01)<br>Mean ADP: 8.7\",\"<b>COURTHOUSE USM CNTL ISLIP<\\/b><br>NY | Other/Unknown<br>Peak: 1 (2025-03-11)<br>Mean ADP: 0\",\"<b>CHAMPLAIN HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 8 (2025-09-18)<br>Mean ADP: 0.2\",\"<b>CHIPPENHAM HOSPITAL - RICHMOND<\\/b><br>VA | Medical<br>Peak: 1 (2025-06-23)<br>Mean ADP: 0.1\",\"<b>CHRISTIAN COUNTY JAIL<\\/b><br>KY | Federal<br>Peak: 1 (2025-09-18)<br>Mean ADP: 0\",\"<b>CHARLOTTE COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-07-22)<br>Mean ADP: 0\",\"<b>CHESAPEAKE CITY JAIL<\\/b><br>VA | Non-Dedicated<br>Peak: 23 (2025-09-24)<br>Mean ADP: 0.7\",\"<b>CHRISTUS SANTA ROSA HOSPITAL - MED<\\/b><br>TX | Medical<br>Peak: 1 (2024-11-30)<br>Mean ADP: 0\",\"<b>CHEYENNE HOLDROOM<\\/b><br>WY | Hold/Staging<br>Peak: 3 (2025-01-27)<br>Mean ADP: 0.3\",\"<b>CIBOLA GENERAL HOSPITAL<\\/b><br>NM | Medical<br>Peak: 1 (2025-03-23)<br>Mean ADP: 0\",\"<b>CIBOLA COUNTY DET CTR<\\/b><br>NM | Non-Dedicated<br>Peak: 1 (2025-05-11)<br>Mean ADP: 0\",\"<b>CINCINNATI HOLDROOM<\\/b><br>OH | Hold/Staging<br>Peak: 4 (2025-02-04)<br>Mean ADP: 0\",\"<b>CENTRAL ISLIP HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 45 (2025-06-05)<br>Mean ADP: 3\",\"<b>CITRUS COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2024-12-14)<br>Mean ADP: 0\",\"<b>HCA FLORIDA KENDALL HOSPITAL<\\/b><br>FL | Medical<br>Peak: 7 (2025-03-12)<br>Mean ADP: 1.6\",\"<b>CLEVELAND HOLD ROOM<\\/b><br>OH | Hold/Staging<br>Peak: 14 (2025-06-04)<br>Mean ADP: 0.3\",\"<b>COLUMBUS HOLDROOM<\\/b><br>OH | Hold/Staging<br>Peak: 10 (2025-03-04)<br>Mean ADP: 0.4\",\"<b>CHARLOTTE HOLD ROOM<\\/b><br>NC | Hold/Staging<br>Peak: 48 (2025-06-29)<br>Mean ADP: 9.7\",\"<b>BATAVIA COMMAND CENTER HOLDROOM<\\/b><br>NY | Hold/Staging<br>Peak: 1 (2024-11-08)<br>Mean ADP: 0\",\"<b>CHATTANOOGA HOLD ROOM<\\/b><br>TN | Hold/Staging<br>Peak: 12 (2025-07-03)<br>Mean ADP: 2.5\",\"<b>CENTEGRA HOSPITAL<\\/b><br>IL | Medical<br>Peak: 1 (2025-09-20)<br>Mean ADP: 0\",\"<b>CENTRAL WASHINGTON HOSPITAL<\\/b><br>WA | Medical<br>Peak: 1 (2025-05-29)<br>Mean ADP: 0\",\"<b>COLUMBIA, SC HOLDROOM<\\/b><br>SC | Hold/Staging<br>Peak: 31 (2025-03-12)<br>Mean ADP: 1.3\",\"<b>COBB CO SHERIFFS OFC ADULT DET CTR<\\/b><br>GA | Non-Dedicated<br>Peak: 4 (2024-12-13)<br>Mean ADP: 0.3\",\"<b>COLO DEPT OF CORRECTIONS<\\/b><br>CO | Non-Dedicated<br>Peak: 1 (2025-04-30)<br>Mean ADP: 0.4\",\"<b>COLUMBIA CARE CENTER<\\/b><br>SC | Medical<br>Peak: 10 (2025-02-24)<br>Mean ADP: 4.4\",\"<b>COLUMBIA COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-01-27)<br>Mean ADP: 0\",\"<b>CONNALLY MEMORIAL MEDICAL CENTER<\\/b><br>TX | Medical<br>Peak: 1 (2025-01-21)<br>Mean ADP: 0\",\"<b>COXHEALTH MEDICAL CENTER SOUTH<\\/b><br>MO | Medical<br>Peak: 1 (2025-03-12)<br>Mean ADP: 0.1\",\"<b>CRAIG HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 4 (2025-09-23)<br>Mean ADP: 0.2\",\"<b>CEDAR RAPIDS HOLD ROOM<\\/b><br>IA | Hold/Staging<br>Peak: 17 (2025-08-23)<br>Mean ADP: 0.7\",\"<b>CORPUS CHRISTI EOR HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 8 (2025-09-09)<br>Mean ADP: 0.8\",\"<b>COLO SPRINGS DEN HSI HOLD<\\/b><br>CO | Hold/Staging<br>Peak: 7 (2025-08-22)<br>Mean ADP: 0.4\",\"<b>CHI ST LUKE'S H M LUFKIN<\\/b><br>TX | Medical<br>Peak: 1 (2025-05-21)<br>Mean ADP: 0\",\"<b>CASPER HOLDROOM<\\/b><br>WY | Hold/Staging<br>Peak: 6 (2025-03-14)<br>Mean ADP: 0.5\",\"<b>CENTRA SOUTHSIDE COMM HOSP<\\/b><br>VA | Medical<br>Peak: 1 (2024-10-23)<br>Mean ADP: 0\",\"<b>CULPEPER CO. ADULT DET. CENTER<\\/b><br>VA | Non-Dedicated<br>Peak: 1 (2025-04-11)<br>Mean ADP: 0\",\"<b>CENTRAL VALLEY ANNEX<\\/b><br>CA | Dedicated<br>Peak: 1 (2025-06-13)<br>Mean ADP: 0.1\",\"<b>CENTRAL VA REGIONAL JAIL<\\/b><br>VA | Non-Dedicated<br>Peak: 2 (2025-09-10)<br>Mean ADP: 0.1\",\"<b>DALLAS F.O. HOLD<\\/b><br>TX | Hold/Staging<br>Peak: 225 (2025-09-18)<br>Mean ADP: 53.1\",\"<b>DEKALB COUNTY DETENTION CENTER<\\/b><br>AL | Federal<br>Peak: 1 (2025-08-09)<br>Mean ADP: 0\",\"<b>DENVER HOLD ROOM<\\/b><br>CO | Hold/Staging<br>Peak: 35 (2025-04-28)<br>Mean ADP: 5\",\"<b>DENVER COUNTY JAIL<\\/b><br>CO | Federal<br>Peak: 1 (2025-04-28)<br>Mean ADP: 0\",\"<b>DETROIT HOLDROOM<\\/b><br>MI | Hold/Staging<br>Peak: 47 (2025-06-19)<br>Mean ADP: 1.2\",\"<b>DEL RIO DRO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 12 (2025-09-06)<br>Mean ADP: 1\",\"<b>DENVER HEALTH MEDICAL CENTER<\\/b><br>CO | Medical<br>Peak: 1 (2025-06-13)<br>Mean ADP: 0\",\"<b>DONA ANA COUNTY DETENTION FACILITY<\\/b><br>NM | Non-Dedicated<br>Peak: 1 (2025-04-24)<br>Mean ADP: 0.4\",\"<b>DORCHESTER CO DET CTR<\\/b><br>SC | Federal<br>Peak: 10 (2025-09-14)<br>Mean ADP: 1.3\",\"<b>DOUGLAS COUNTY DETENTION CENTER<\\/b><br>CO | Non-Dedicated<br>Peak: 1 (2025-08-14)<br>Mean ADP: 0\",\"<b>DSMC - DEL SOL MEDICAL CENTER<\\/b><br>TX | Medical<br>Peak: 7 (2025-03-27)<br>Mean ADP: 1.1\",\"<b>DES MOINES HOLD ROOM<\\/b><br>IA | Hold/Staging<br>Peak: 3 (2025-04-19)<br>Mean ADP: 0.3\",\"<b>DESERT VALLEY HOSPITAL<\\/b><br>CA | Medical<br>Peak: 10 (2025-05-23)<br>Mean ADP: 0.2\",\"<b>DURANGO HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 6 (2025-08-18)<br>Mean ADP: 0.1\",\"<b>DOVER HOLDROOM<\\/b><br>DE | Hold/Staging<br>Peak: 10 (2025-06-12)<br>Mean ADP: 1.4\",\"<b>DESERT VIEW HOSPITAL<\\/b><br>NV | Medical<br>Peak: 1 (2024-10-18)<br>Mean ADP: 0\",\"<b>ERIE COUNTY MEDICAL CENTER<\\/b><br>NY | Medical<br>Peak: 2 (2025-03-06)<br>Mean ADP: 0.2\",\"<b>EL CENTRO REGIONAL MED CTR<\\/b><br>CA | Medical<br>Peak: 2 (2024-12-25)<br>Mean ADP: 0.2\",\"<b>EL PASO COUNTY JAIL (TX)<\\/b><br>TX | Non-Dedicated<br>Peak: 2 (2025-03-12)<br>Mean ADP: 0.1\",\"<b>ENLOE MEDICAL CENTER<\\/b><br>CA | Medical<br>Peak: 2 (2025-05-22)<br>Mean ADP: 0\",\"<b>EL PASO BEHAVIORAL HEALTH SYSTEM<\\/b><br>TX | Medical<br>Peak: 13 (2025-09-03)<br>Mean ADP: 4.7\",\"<b>EL PASO COUNTY DETENTION FACILITY<\\/b><br>TX | Non-Dedicated<br>Peak: 95 (2024-12-30)<br>Mean ADP: 1.4\",\"<b>EL PASO LTAC HOSPITAL<\\/b><br>TX | Medical<br>Peak: 3 (2025-03-28)<br>Mean ADP: 0.8\",\"<b>EL PASO SOFT SIDED FACILITY<\\/b><br>TX | Hold/Staging<br>Peak: 1606 (2025-08-12)<br>Mean ADP: 243.2\",\"<b>ESKENAZI HEALTH<\\/b><br>IN | Medical<br>Peak: 1 (2025-08-19)<br>Mean ADP: 0\",\"<b>ESSEX COUNTY JAIL<\\/b><br>NJ | Non-Dedicated<br>Peak: 1 (2025-02-03)<br>Mean ADP: 0\",\"<b>ETOWAH ERO HOLD ROOM<\\/b><br>AL | Hold/Staging<br>Peak: 2 (2024-10-15)<br>Mean ADP: 0\",\"<b>EUGENE HOLDROOM<\\/b><br>OR | Hold/Staging<br>Peak: 9 (2025-01-27)<br>Mean ADP: 0.4\",\"<b>FAYETTEVILLE HOLD ROOM<\\/b><br>AR | Hold/Staging<br>Peak: 9 (2025-03-05)<br>Mean ADP: 0.3\",\"<b>FACILITY 8 DETENTION FACILITY<\\/b><br>CA | Non-Dedicated<br>Peak: 1 (2025-02-25)<br>Mean ADP: 0\",\"<b>FERNDALE HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 6 (2025-06-10)<br>Mean ADP: 0.5\",\"<b>FINNEY COUNTY JAIL<\\/b><br>KS | Non-Dedicated<br>Peak: 11 (2025-02-26)<br>Mean ADP: 1.9\",\"<b>BAKER C. I.<\\/b><br>FL | Dedicated<br>Peak: 294 (2025-09-24)<br>Mean ADP: 15.7\",\"<b>FT LAUDERDALE BEHAVOR HLTH CTR<\\/b><br>FL | Medical<br>Peak: 11 (2025-05-12)<br>Mean ADP: 4.3\",\"<b>CHARLOTTE CI, PUNTA GORDA<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2024-12-10)<br>Mean ADP: 0\",\"<b>DADE CORRECTIONAL INST<\\/b><br>FL | Dedicated<br>Peak: 7 (2025-08-25)<br>Mean ADP: 0.2\",\"<b>FLORIDA SOFT-SIDED FACILITY-SOUTH<\\/b><br>FL | Dedicated<br>Peak: 1482 (2025-07-30)<br>Mean ADP: 170.3\",\"<b>FLAGLER COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 12 (2025-08-31)<br>Mean ADP: 0.1\",\"<b>FORT LAUDERDALE HOSPITAL<\\/b><br>FL | Medical<br>Peak: 1 (2025-02-20)<br>Mean ADP: 0\",\"<b>FLORENCE HOSPITAL<\\/b><br>AZ | Medical<br>Peak: 5 (2025-01-06)<br>Mean ADP: 0.8\",\"<b>FORT MYERS ERO HOLDROOM<\\/b><br>FL | Hold/Staging<br>Peak: 29 (2025-06-21)<br>Mean ADP: 5\",\"<b>FOND DU LAC COUNTY SHERIFF/JAIL<\\/b><br>WI | Non-Dedicated<br>Peak: 1 (2025-06-19)<br>Mean ADP: 0\",\"<b>FRANKLIN COUNTY JAIL<\\/b><br>PA | Federal<br>Peak: 2 (2025-06-20)<br>Mean ADP: 0.1\",\"<b>FREDERICK HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 7 (2025-07-29)<br>Mean ADP: 1.3\",\"<b>FREDERICK COUNTY DET. CEN<\\/b><br>MD | Non-Dedicated<br>Peak: 1 (2024-11-30)<br>Mean ADP: 0\",\"<b>FRESNO HOLDROOM<\\/b><br>CA | Hold/Staging<br>Peak: 22 (2025-08-29)<br>Mean ADP: 4.9\",\"<b>FRIO REGIONAL HOSPITAL<\\/b><br>TX | Medical<br>Peak: 2 (2025-05-08)<br>Mean ADP: 0.2\",\"<b>FORT SMITH HOLDROOM<\\/b><br>AR | Hold/Staging<br>Peak: 4 (2025-02-25)<br>Mean ADP: 0.1\",\"<b>GARVIN COUNTY JAIL<\\/b><br>OK | Non-Dedicated<br>Peak: 15 (2025-09-15)<br>Mean ADP: 0.6\",\"<b>GASTON COUNTY JAIL<\\/b><br>NC | Non-Dedicated<br>Peak: 6 (2025-03-19)<br>Mean ADP: 0.6\",\"<b>GARDEN CITY PROCESSING @ FINNEY CO<\\/b><br>KS | Other/Unknown<br>Peak: 3 (2025-07-22)<br>Mean ADP: 0\",\"<b>GRAND FORKS CO. JUVENILE<\\/b><br>ND | Family/Youth<br>Peak: 1 (2025-07-29)<br>Mean ADP: 0.2\",\"<b>GRAND JUNCTION HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 7 (2025-06-03)<br>Mean ADP: 0.7\",\"<b>GLENDALE POLICE DEPT<\\/b><br>CA | Non-Dedicated<br>Peak: 22 (2025-06-03)<br>Mean ADP: 0.8\",\"<b>GRADY MEMORIAL HOSPITAL<\\/b><br>GA | Medical<br>Peak: 3 (2025-06-27)<br>Mean ADP: 0.2\",\"<b>FRANKLIN HOUSE OF CORRECTIONS<\\/b><br>MA | Federal<br>Peak: 1 (2025-08-09)<br>Mean ADP: 0\",\"<b>GRAND FORKS HOLD ROOM<\\/b><br>ND | Hold/Staging<br>Peak: 13 (2025-07-08)<br>Mean ADP: 0.5\",\"<b>GEORGETOWN BEHAVIORAL HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2024-11-05)<br>Mean ADP: 0.1\",\"<b>GRAND ISLAND HOLD ROOM<\\/b><br>NE | Hold/Staging<br>Peak: 1 (2025-06-25)<br>Mean ADP: 0\",\"<b>GRAND RAPIDS HOLDROOM<\\/b><br>MI | Hold/Staging<br>Peak: 9 (2025-06-24)<br>Mean ADP: 0.8\",\"<b>GREER HOLD ROOM<\\/b><br>SC | Hold/Staging<br>Peak: 7 (2025-06-25)<br>Mean ADP: 1\",\"<b>GLENWOOD SPRINGS HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 10 (2025-05-22)<br>Mean ADP: 0.2\",\"<b>MIGRANT OPS CENTER MAIN AV622<\\/b><br>CU | Federal<br>Peak: 51 (2025-05-20)<br>Mean ADP: 10.9\",\"<b>GUAM MEMORIAL HOSPITAL<\\/b><br>GU | Medical<br>Peak: 5 (2025-05-22)<br>Mean ADP: 0\",\"<b>HAILE DET. CENTER<\\/b><br>ID | Non-Dedicated<br>Peak: 2 (2025-03-03)<br>Mean ADP: 0.1\",\"<b>HAMILTON CO. JAIL (TENN)<\\/b><br>TN | Non-Dedicated<br>Peak: 1 (2025-07-13)<br>Mean ADP: 0\",\"<b>HARTFORD CORR CENTER<\\/b><br>CT | Non-Dedicated<br>Peak: 1 (2025-03-13)<br>Mean ADP: 0\",\"<b>HARTFORD OFFICE<\\/b><br>CT | Hold/Staging<br>Peak: 37 (2025-05-29)<br>Mean ADP: 4.6\",\"<b>HARRISON DETENTION CENTER<\\/b><br>MS | Non-Dedicated<br>Peak: 1 (2025-08-27)<br>Mean ADP: 0\",\"<b>ROLLING PLAINS DETENTION CENTER<\\/b><br>TX | Federal<br>Peak: 1 (2024-11-21)<br>Mean ADP: 0\",\"<b>HARRISONBURG HOLD ROOM<\\/b><br>VA | Hold/Staging<br>Peak: 11 (2025-06-03)<br>Mean ADP: 1.1\",\"<b>HCA FLORIDA MEMORIAL HOSPITAL<\\/b><br>FL | Medical<br>Peak: 1 (2025-02-20)<br>Mean ADP: 0.1\",\"<b>HCA HOUSTON HC CONROE<\\/b><br>TX | Medical<br>Peak: 18 (2025-03-20)<br>Mean ADP: 3.3\",\"<b>HENNEPIN COUNTY MED CTR<\\/b><br>MN | Medical<br>Peak: 1 (2025-08-02)<br>Mean ADP: 0\",\"<b>HARRIS COUNTY PSYCHIATRIC CENTER<\\/b><br>TX | Medical<br>Peak: 3 (2025-05-09)<br>Mean ADP: 0.7\",\"<b>HENDERSON HOSPITAL<\\/b><br>NV | Medical<br>Peak: 1 (2025-05-20)<br>Mean ADP: 0\",\"<b>HEL DISTRICT CUSTODY<\\/b><br>MT | Hold/Staging<br>Peak: 2 (2025-08-19)<br>Mean ADP: 0\",\"<b>HENDERSON COUNTY DET. FAC.<\\/b><br>NC | Non-Dedicated<br>Peak: 2 (2025-02-19)<br>Mean ADP: 0.1\",\"<b>HENDRY COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2024-10-15)<br>Mean ADP: 0\",\"<b>HENDERSONVILLE HOLD ROOM<\\/b><br>NC | Hold/Staging<br>Peak: 5 (2025-05-29)<br>Mean ADP: 0.1\",\"<b>HENRICO COUNTY JAIL<\\/b><br>VA | Non-Dedicated<br>Peak: 1 (2025-07-28)<br>Mean ADP: 0\",\"<b>HIGHLANDS BEHAVIORAL HEALTH<\\/b><br>CO | Medical<br>Peak: 1 (2025-01-11)<br>Mean ADP: 0.1\",\"<b>HARRIS HEALTH BEN TAUB HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2025-04-16)<br>Mean ADP: 0.2\",\"<b>HOUSTON HEALTHCARE HOSP<\\/b><br>TX | Medical<br>Peak: 3 (2025-02-25)<br>Mean ADP: 0.3\",\"<b>ERO HONOLULU SUB-OFFICE HOLD ROOM<\\/b><br>HI | Hold/Staging<br>Peak: 4 (2025-03-06)<br>Mean ADP: 0.1\",\"<b>HILLSBOROUGH COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 40 (2025-07-03)<br>Mean ADP: 0.5\",\"<b>HIDALGO COUNTY SHERIFF'S JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2024-12-11)<br>Mean ADP: 0\",\"<b>B.R.R.J. HALIFAX<\\/b><br>VA | Non-Dedicated<br>Peak: 1 (2025-07-13)<br>Mean ADP: 0\",\"<b>HARLINGEN HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 118 (2025-06-04)<br>Mean ADP: 15.4\",\"<b>HARLINGEN MEDICAL CENTER<\\/b><br>TX | Medical<br>Peak: 1 (2025-07-12)<br>Mean ADP: 0\",\"<b>HENDRICK MEDICAL CENTER<\\/b><br>TX | Medical<br>Peak: 2 (2025-02-14)<br>Mean ADP: 0.2\",\"<b>HOUSTON FO HOLDROOM<\\/b><br>TX | Hold/Staging<br>Peak: 18 (2024-12-10)<br>Mean ADP: 1.7\",\"<b>HARLINGEN POLICE DEPT.<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2025-01-10)<br>Mean ADP: 0\",\"<b>MIAMI BORDER PATROL<\\/b><br>FL | Hold/Staging<br>Peak: 1 (2025-07-02)<br>Mean ADP: 0\",\"<b>IDAHO FALLS HOLD ROOM<\\/b><br>ID | Hold/Staging<br>Peak: 5 (2025-04-03)<br>Mean ADP: 0.2\",\"<b>IMPERIAL SUB OFFICE HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 12 (2025-09-03)<br>Mean ADP: 1.2\",\"<b>INDIANAPOLIS HOLD ROOM<\\/b><br>IN | Hold/Staging<br>Peak: 130 (2025-09-19)<br>Mean ADP: 12.3\",\"<b>INTEGRIS HEALTH BAPTIST MEDICAL<\\/b><br>OK | Medical<br>Peak: 1 (2025-06-26)<br>Mean ADP: 0\",\"<b>AZ REM OP COORD CENTER (AROCC)<\\/b><br>AZ | Hold/Staging<br>Peak: 195 (2025-04-30)<br>Mean ADP: 37.4\",\"<b>JACKSON MS HOLD ROOM<\\/b><br>MS | Hold/Staging<br>Peak: 23 (2025-08-29)<br>Mean ADP: 4.2\",\"<b>JACKSONVILLE SUB-OFFICE<\\/b><br>FL | Hold/Staging<br>Peak: 35 (2025-04-25)<br>Mean ADP: 5.4\",\"<b>JEFFERSON COUNTY JAIL<\\/b><br>IL | Non-Dedicated<br>Peak: 1 (2024-11-15)<br>Mean ADP: 0\",\"<b>JFK INTERNATIONAL AP - T7<\\/b><br>NY | Other/Unknown<br>Peak: 23 (2025-04-01)<br>Mean ADP: 5.3\",\"<b>Jamaica Hospital Med Ctr<\\/b><br>NY | Medical<br>Peak: 1 (2025-02-18)<br>Mean ADP: 0\",\"<b>JACK HARWELL DETENTION CENTER<\\/b><br>TX | Federal<br>Peak: 6 (2025-05-15)<br>Mean ADP: 0.3\",\"<b>JACKSON MEMORIAL HOSPITAL<\\/b><br>FL | Medical<br>Peak: 2 (2025-05-03)<br>Mean ADP: 0.1\",\"<b>JOHNSTON MEMORIAL HOSPITAL<\\/b><br>VA | Medical<br>Peak: 1 (2025-08-17)<br>Mean ADP: 0\",\"<b>JOHN PETER SMITH HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2025-09-01)<br>Mean ADP: 0\",\"<b>KANSAS CITY HOLDROOM<\\/b><br>MO | Hold/Staging<br>Peak: 64 (2025-05-09)<br>Mean ADP: 6.1\",\"<b>KARNES CTY CORR CTR<\\/b><br>TX | Federal<br>Peak: 10 (2025-02-25)<br>Mean ADP: 1.5\",\"<b>KARNES COUNTY CIVIL DET. FACILITY<\\/b><br>TX | Family/Youth<br>Peak: 9 (2025-04-23)<br>Mean ADP: 0.3\",\"<b>KENMORE MERCY HOSPITAL<\\/b><br>NY | Medical<br>Peak: 1 (2025-05-03)<br>Mean ADP: 0\",\"<b>KERN COUNTY JAIL (LERDO)<\\/b><br>CA | Non-Dedicated<br>Peak: 2 (2025-05-22)<br>Mean ADP: 0\",\"<b>KERN MEDICAL HOSPITAL<\\/b><br>CA | Medical<br>Peak: 1 (2025-02-07)<br>Mean ADP: 0\",\"<b>KINNEY COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 4 (2025-01-14)<br>Mean ADP: 0.1\",\"<b>KNOXVILLE HOLD ROOM<\\/b><br>TN | Hold/Staging<br>Peak: 20 (2025-08-22)<br>Mean ADP: 3.3\",\"<b>KODIAK CITY JAIL<\\/b><br>AK | Non-Dedicated<br>Peak: 1 (2025-06-06)<br>Mean ADP: 0\",\"<b>PROMISE HOSPITAL<\\/b><br>AZ | Medical<br>Peak: 3 (2025-05-23)<br>Mean ADP: 1\",\"<b>KROME/MIAMI HUB<\\/b><br>FL | Hold/Staging<br>Peak: 54 (2025-05-24)<br>Mean ADP: 5.8\",\"<b>KROME HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 600 (2025-02-17)<br>Mean ADP: 36.5\",\"<b>LACKAWANA CNTY JAIL, PA<\\/b><br>PA | Federal<br>Peak: 1 (2025-08-13)<br>Mean ADP: 0\",\"<b>LARAMIE COUNTY JAIL<\\/b><br>WY | Federal<br>Peak: 8 (2025-09-13)<br>Mean ADP: 0.2\",\"<b>LASALLE COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2025-06-23)<br>Mean ADP: 0\",\"<b>LAS CRUCES HOLD ROOM<\\/b><br>NM | Hold/Staging<br>Peak: 7 (2025-08-05)<br>Mean ADP: 0.4\",\"<b>LAWRENCE CO. JAIL, SD<\\/b><br>SD | Non-Dedicated<br>Peak: 5 (2025-09-24)<br>Mean ADP: 0.2\",\"<b>HARRIS HEALTH LBJ HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2024-10-05)<br>Mean ADP: 0\",\"<b>LUBBOCK HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 17 (2025-09-10)<br>Mean ADP: 2.5\",\"<b>LEVY COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2024-12-03)<br>Mean ADP: 0\",\"<b>LEXINGTON PROCESSING @ FAYETTE CO<\\/b><br>KY | Federal<br>Peak: 3 (2024-10-07)<br>Mean ADP: 0.1\",\"<b>LAHEY HOSPITAL & MED CTR<\\/b><br>MA | Medical<br>Peak: 2 (2025-05-21)<br>Mean ADP: 0\",\"<b>LINCOLN COUNTY SHERIFF'S<\\/b><br>MO | Non-Dedicated<br>Peak: 4 (2024-10-05)<br>Mean ADP: 0.3\",\"<b>LIRS - LFSRM FORT COLLINS LTFC CO<\\/b><br>CO | Other/Unknown<br>Peak: 2 (2025-08-18)<br>Mean ADP: 0.3\",\"<b>LOCKPORT MEMORIAL HOSPITAL<\\/b><br>NY | Medical<br>Peak: 1 (2025-08-20)<br>Mean ADP: 0\",\"<b>LOS ANGELES COUNTY JAIL-TWIN TOWER<\\/b><br>CA | Non-Dedicated<br>Peak: 1 (2025-05-30)<br>Mean ADP: 0\",\"<b>LOS CUST CASE<\\/b><br>CA | Hold/Staging<br>Peak: 455 (2025-07-11)<br>Mean ADP: 58.7\",\"<b>LOUDOUN COUNTY<\\/b><br>VA | Federal<br>Peak: 4 (2025-09-10)<br>Mean ADP: 0.1\",\"<b>LOUISVILLE HOLD ROOM<\\/b><br>KY | Hold/Staging<br>Peak: 23 (2025-03-12)<br>Mean ADP: 0.6\",\"<b>LA PALMA CORR CTR APSO<\\/b><br>AZ | Dedicated<br>Peak: 2 (2025-03-19)<br>Mean ADP: 0\",\"<b>LOS ANGELES POLICE PD 77TH DIV.<\\/b><br>CA | Non-Dedicated<br>Peak: 1 (2025-03-20)<br>Mean ADP: 0\",\"<b>LA PAZ REGIONAL HOSPITAL<\\/b><br>AZ | Medical<br>Peak: 1 (2025-01-24)<br>Mean ADP: 0\",\"<b>LITTLE ROCK HOLD ROOM<\\/b><br>AR | Hold/Staging<br>Peak: 27 (2025-02-25)<br>Mean ADP: 4.2\",\"<b>LAREDO DETENTION CENTER HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 115 (2024-12-31)<br>Mean ADP: 3.8\",\"<b>LAREDO MEDICAL CENTER<\\/b><br>TX | Medical<br>Peak: 2 (2025-01-31)<br>Mean ADP: 0.3\",\"<b>LARKIN BEHAVIORAL HEALTH SVCS<\\/b><br>FL | Medical<br>Peak: 12 (2025-07-19)<br>Mean ADP: 8.4\",\"<b>LARKIN HOSPITAL<\\/b><br>FL | Medical<br>Peak: 16 (2025-04-29)<br>Mean ADP: 6.5\",\"<b>LOS FRESNOS HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 1 (2024-11-11)<br>Mean ADP: 0\",\"<b>LEMUEL SHATTUCK HOSPITAL<\\/b><br>MA | Medical<br>Peak: 1 (2025-03-12)<br>Mean ADP: 0.1\",\"<b>LAS VEGAS HOLD ROOM<\\/b><br>NV | Hold/Staging<br>Peak: 68 (2025-04-18)<br>Mean ADP: 4.2\",\"<b>LEHIGH VALLEY HOSPITAL - POCONO<\\/b><br>PA | Medical<br>Peak: 1 (2024-10-01)<br>Mean ADP: 0\",\"<b>LOYOLA CENTER FOR HEALTH<\\/b><br>IL | Medical<br>Peak: 2 (2025-06-09)<br>Mean ADP: 0.1\",\"<b>MANATEE COUNTY DETENTION-ANNEX<\\/b><br>FL | Non-Dedicated<br>Peak: 7 (2025-08-13)<br>Mean ADP: 0.8\",\"<b>MANCHESTER HOLDROOM<\\/b><br>NH | Hold/Staging<br>Peak: 9 (2025-02-18)<br>Mean ADP: 0.5\",\"<b>MARION CO JAIL<\\/b><br>OR | Non-Dedicated<br>Peak: 2 (2025-08-22)<br>Mean ADP: 0\",\"<b>MARION COUNTY JAIL<\\/b><br>FL | Federal<br>Peak: 11 (2025-02-18)<br>Mean ADP: 1.2\",\"<b>MARTIN COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 24 (2025-09-05)<br>Mean ADP: 1.5\",\"<b>MAVERICK COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 3 (2025-01-17)<br>Mean ADP: 0.1\",\"<b>MCALLEN HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 59 (2025-02-26)<br>Mean ADP: 9.7\",\"<b>MCLENNAN COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 5 (2025-02-24)<br>Mean ADP: 0.3\",\"<b>MAYO CLINIC HEALTH SYS ALBERT LEA<\\/b><br>MN | Medical<br>Peak: 1 (2024-10-17)<br>Mean ADP: 0\",\"<b>CHI HEALTH MIDLANDS HOSPITAL<\\/b><br>NE | Medical<br>Peak: 1 (2025-08-20)<br>Mean ADP: 0\",\"<b>MEDFORD SUB-OFFICE<\\/b><br>OR | Hold/Staging<br>Peak: 14 (2025-07-30)<br>Mean ADP: 0.2\",\"<b>MERCY HOSP DOWNTOWN BAKERSFIELD<\\/b><br>CA | Medical<br>Peak: 1 (2025-01-18)<br>Mean ADP: 0\",\"<b>MERCY MEDICAL CTR REDDING<\\/b><br>CA | Medical<br>Peak: 1 (2024-10-07)<br>Mean ADP: 0\",\"<b>MEMPHIS HOLD ROOM<\\/b><br>TN | Hold/Staging<br>Peak: 25 (2025-08-15)<br>Mean ADP: 5.2\",\"<b>MEMORIAL REGIONAL HOSP.<\\/b><br>FL | Medical<br>Peak: 1 (2025-07-05)<br>Mean ADP: 0\",\"<b>MESA COUNTY JAIL<\\/b><br>CO | Federal<br>Peak: 1 (2025-01-24)<br>Mean ADP: 0\",\"<b>METHODIST HOSPITAL<\\/b><br>TX | Medical<br>Peak: 2 (2024-11-03)<br>Mean ADP: 0.3\",\"<b>METRO DADE JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 25 (2025-06-24)<br>Mean ADP: 0.4\",\"<b>MUNSON HEALTHCARE CADILLAC HOSP<\\/b><br>MI | Medical<br>Peak: 1 (2025-09-18)<br>Mean ADP: 0\",\"<b>M HEALTH FAIRVIEW SOUTHDALE HOSP<\\/b><br>MN | Medical<br>Peak: 1 (2024-10-29)<br>Mean ADP: 0\",\"<b>METHODIST HOSPITAL METROPOLITAN<\\/b><br>TX | Medical<br>Peak: 2 (2024-10-18)<br>Mean ADP: 0.2\",\"<b>MEMORIAL HERMANN NE HOSP<\\/b><br>TX | Medical<br>Peak: 5 (2025-09-01)<br>Mean ADP: 1.3\",\"<b>METHODIST HOSPITAL NORTHEAST<\\/b><br>TX | Medical<br>Peak: 1 (2024-11-01)<br>Mean ADP: 0.1\",\"<b>MILTON S. HERSHEY MEDICAL CENTER<\\/b><br>PA | Medical<br>Peak: 1 (2024-11-16)<br>Mean ADP: 0\",\"<b>METHODIST HOSPITAL STONE OAK<\\/b><br>TX | Medical<br>Peak: 1 (2025-06-12)<br>Mean ADP: 0\",\"<b>METHODIST HOSPITAL TEXSAN<\\/b><br>TX | Medical<br>Peak: 2 (2024-12-23)<br>Mean ADP: 0.1\",\"<b>MIAMI (MIRAMAR) HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 94 (2025-09-10)<br>Mean ADP: 12.6\",\"<b>MIDLAND DETENTION CENTER<\\/b><br>TX | Federal<br>Peak: 13 (2025-05-26)<br>Mean ADP: 1.1\",\"<b>MIDLAND MEMORIAL HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2025-07-27)<br>Mean ADP: 0\",\"<b>MILWAUKEE HOLDROOM<\\/b><br>WI | Hold/Staging<br>Peak: 22 (2025-06-03)<br>Mean ADP: 1.4\",\"<b>MINICASSIA DET. CENTER<\\/b><br>ID | Non-Dedicated<br>Peak: 8 (2025-06-25)<br>Mean ADP: 0.7\",\"<b>MIRIAM HOSPITAL<\\/b><br>RI | Medical<br>Peak: 1 (2024-12-11)<br>Mean ADP: 0\",\"<b>MIDLAND, TX ERO HOLDROOM<\\/b><br>TX | Hold/Staging<br>Peak: 13 (2025-06-04)<br>Mean ADP: 2.1\",\"<b>MOUNT LAUREL HOLD ROOM<\\/b><br>NJ | Hold/Staging<br>Peak: 26 (2025-06-03)<br>Mean ADP: 5.5\",\"<b>MCLAREN PORT HURON HOSP<\\/b><br>MI | Medical<br>Peak: 1 (2025-04-28)<br>Mean ADP: 0\",\"<b>MERCY MED CTR CEDAR RAPID<\\/b><br>IA | Medical<br>Peak: 1 (2025-09-18)<br>Mean ADP: 0\",\"<b>MONROE COUNTY SHERIFF/JAIL-MAIN<\\/b><br>MI | Non-Dedicated<br>Peak: 7 (2025-01-26)<br>Mean ADP: 0.1\",\"<b>MONTGOMERY CITY JAIL<\\/b><br>AL | Non-Dedicated<br>Peak: 1 (2025-01-07)<br>Mean ADP: 0\",\"<b>MOBILE HOLDROOM<\\/b><br>AL | Hold/Staging<br>Peak: 35 (2025-06-24)<br>Mean ADP: 2.7\",\"<b>MONMOUTH COUNTY JAIL<\\/b><br>NJ | Non-Dedicated<br>Peak: 1 (2025-04-28)<br>Mean ADP: 0\",\"<b>MONROE COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 3 (2025-01-27)<br>Mean ADP: 0.2\",\"<b>MONTGOMERY CO MAC SIM BUTLER D.F.<\\/b><br>AL | Federal<br>Peak: 2 (2024-11-20)<br>Mean ADP: 0.3\",\"<b>MARIAN REGIONAL MEDICAL CENTER<\\/b><br>CA | Medical<br>Peak: 1 (2025-08-18)<br>Mean ADP: 0\",\"<b>MIDDLE RIVER REGIONAL JAIL<\\/b><br>VA | Non-Dedicated<br>Peak: 1 (2024-10-24)<br>Mean ADP: 0\",\"<b>MERCY HOSPITAL SOUTH<\\/b><br>MO | Medical<br>Peak: 1 (2025-04-08)<br>Mean ADP: 0\",\"<b>MERCY HOSPITAL<\\/b><br>MN | Medical<br>Peak: 1 (2025-07-02)<br>Mean ADP: 0\",\"<b>MIAMI STAGING FACILITY<\\/b><br>FL | Hold/Staging<br>Peak: 176 (2025-01-31)<br>Mean ADP: 16.5\",\"<b>METHODIST SPECIALTY TRANSPLANT HOS<\\/b><br>TX | Medical<br>Peak: 1 (2025-01-22)<br>Mean ADP: 0\",\"<b>MONTGOMERY HOLD RM<\\/b><br>TX | Hold/Staging<br>Peak: 221 (2025-08-21)<br>Mean ADP: 50\",\"<b>MOUNT NITTANY MEDICAL CENTER<\\/b><br>PA | Medical<br>Peak: 2 (2025-09-12)<br>Mean ADP: 0.1\",\"<b>MOUNTAIN VISTA MED CTR<\\/b><br>AZ | Medical<br>Peak: 2 (2025-01-07)<br>Mean ADP: 0.2\",\"<b>PENN HIGHLANDS CLEARFIELD<\\/b><br>PA | Medical<br>Peak: 1 (2024-10-08)<br>Mean ADP: 0.1\",\"<b>MARY WASHINGTON HOSPITAL<\\/b><br>VA | Medical<br>Peak: 1 (2024-10-15)<br>Mean ADP: 0\",\"<b>MAYO CLINIC HEALTH SYS - MANKATO<\\/b><br>MN | Medical<br>Peak: 2 (2025-07-10)<br>Mean ADP: 0.1\",\"<b>NASSAU COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2024-10-15)<br>Mean ADP: 0\",\"<b>NASSAU COUNTY ICE TRAILER<\\/b><br>NY | Non-Dedicated<br>Peak: 13 (2025-09-17)<br>Mean ADP: 0.7\",\"<b>NEWBURGH HOLDING<\\/b><br>NY | Hold/Staging<br>Peak: 10 (2025-07-29)<br>Mean ADP: 1.5\",\"<b>NORTH BROWARD MEDICAL CENTER<\\/b><br>FL | Medical<br>Peak: 5 (2025-05-15)<br>Mean ADP: 0.7\",\"<b>NEW/INS OS HOLD ROOM<\\/b><br>NJ | Hold/Staging<br>Peak: 12 (2024-11-21)<br>Mean ADP: 0.8\",\"<b>NORTHERN NEVADA MED CTR<\\/b><br>NV | Medical<br>Peak: 1 (2025-05-08)<br>Mean ADP: 0\",\"<b>NEW ORLEANS HOLD ROOM<\\/b><br>LA | Hold/Staging<br>Peak: 5 (2025-06-11)<br>Mean ADP: 0.4\",\"<b>NORFOLK CITY JAIL<\\/b><br>VA | Federal<br>Peak: 1 (2025-06-19)<br>Mean ADP: 0\",\"<b>NORFOLK SUB-OFFICE HOLD<\\/b><br>VA | Hold/Staging<br>Peak: 16 (2025-08-21)<br>Mean ADP: 2\",\"<b>NW REG JUV DET CTR<\\/b><br>VA | Family/Youth<br>Peak: 7 (2025-07-30)<br>Mean ADP: 3.3\",\"<b>NORTH PLATTE HOLD ROOM<\\/b><br>NE | Hold/Staging<br>Peak: 13 (2025-03-08)<br>Mean ADP: 0.1\",\"<b>NASHVILLE HOLD ROOM<\\/b><br>TN | Hold/Staging<br>Peak: 75 (2025-05-04)<br>Mean ADP: 0.7\",\"<b>NASSAU UNIV MED CTR<\\/b><br>NY | Medical<br>Peak: 3 (2025-06-06)<br>Mean ADP: 0.2\",\"<b>NEW HANOVER CO DET CENTER<\\/b><br>NC | Non-Dedicated<br>Peak: 10 (2025-07-18)<br>Mean ADP: 2.7\",\"<b>NORTHWEST REG. ADULT DET.<\\/b><br>VA | Non-Dedicated<br>Peak: 6 (2025-06-03)<br>Mean ADP: 0.2\",\"<b>NYC HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 228 (2025-06-05)<br>Mean ADP: 40.9\",\"<b>NYE COUNTY SHERIFF-PAHRUMP<\\/b><br>NV | Non-Dedicated<br>Peak: 90 (2024-10-08)<br>Mean ADP: 7.1\",\"<b>GREAT MEADOW C.F.<\\/b><br>NY | Non-Dedicated<br>Peak: 1 (2025-07-04)<br>Mean ADP: 0\",\"<b>WASHINGTON CORRECTIONAL<\\/b><br>NY | Non-Dedicated<br>Peak: 1 (2025-06-18)<br>Mean ADP: 0\",\"<b>OAKDALE HOLDING ROOM<\\/b><br>LA | Hold/Staging<br>Peak: 14 (2025-09-12)<br>Mean ADP: 0.1\",\"<b>ORANGE CO GLOBAL MEDICAL CENTER<\\/b><br>CA | Medical<br>Peak: 2 (2025-07-10)<br>Mean ADP: 0.1\",\"<b>ORANGE REGIONAL MED CTR<\\/b><br>NY | Medical<br>Peak: 2 (2024-12-13)<br>Mean ADP: 0.2\",\"<b>OGDEN HOLD ROOM<\\/b><br>UT | Hold/Staging<br>Peak: 13 (2025-09-23)<br>Mean ADP: 1.3\",\"<b>OKLAHOMA CITY HOLD ROOM.<\\/b><br>OK | Hold/Staging<br>Peak: 79 (2025-09-24)<br>Mean ADP: 8.5\",\"<b>OTTO KAISER MEMORIAL HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2024-11-07)<br>Mean ADP: 0\",\"<b>OKMULGEE COUNTY JAIL<\\/b><br>OK | Non-Dedicated<br>Peak: 1 (2025-09-23)<br>Mean ADP: 0\",\"<b>LASALLE CORR CTR OLLA<\\/b><br>LA | Non-Dedicated<br>Peak: 1 (2025-02-22)<br>Mean ADP: 0\",\"<b>OMAHA FO HOLD<\\/b><br>NE | Hold/Staging<br>Peak: 73 (2025-06-11)<br>Mean ADP: 7.2\",\"<b>ORLANDO HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 126 (2025-06-04)<br>Mean ADP: 19.6\",\"<b>OSCEOLA COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 14 (2025-06-21)<br>Mean ADP: 3.3\",\"<b>PALM BEACH COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 4 (2025-07-27)<br>Mean ADP: 0\",\"<b>PAM HEALTH SPECIALTY HOSPITAL 1<\\/b><br>TX | Medical<br>Peak: 2 (2025-05-09)<br>Mean ADP: 0.2\",\"<b>PIEDMOUNT COLUMBUS REG MIDTOWN MC<\\/b><br>GA | Medical<br>Peak: 1 (2025-06-18)<br>Mean ADP: 0\",\"<b>PECOS HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 28 (2025-08-01)<br>Mean ADP: 1.8\",\"<b>PDN HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 36 (2025-06-13)<br>Mean ADP: 0.1\",\"<b>PHELPS HEALTH HOSPITAL<\\/b><br>MO | Medical<br>Peak: 1 (2025-04-07)<br>Mean ADP: 0\",\"<b>PHI DISTRICT OFFICE<\\/b><br>PA | Hold/Staging<br>Peak: 33 (2025-06-05)<br>Mean ADP: 6.7\",\"<b>PHOENIX DIST OFFICE<\\/b><br>AZ | Hold/Staging<br>Peak: 90 (2025-05-21)<br>Mean ADP: 25.7\",\"<b>PHOEBE PUTNEY MEMORIAL HOSP<\\/b><br>GA | Medical<br>Peak: 1 (2025-03-09)<br>Mean ADP: 0\",\"<b>PLAZA HEALTHCARE REHAB CENTER<\\/b><br>NJ | Medical<br>Peak: 1 (2025-09-05)<br>Mean ADP: 0\",\"<b>PIERCE COUNTY JAIL<\\/b><br>ND | Non-Dedicated<br>Peak: 1 (2024-12-29)<br>Mean ADP: 0\",\"<b>PINAL COUNTY JAIL<\\/b><br>AZ | Non-Dedicated<br>Peak: 1 (2025-02-05)<br>Mean ADP: 0\",\"<b>PITTSBURGH HOLDROOM<\\/b><br>PA | Hold/Staging<br>Peak: 19 (2025-06-03)<br>Mean ADP: 2.4\",\"<b>PIKE COUNTY ERO HOLD ROOM<\\/b><br>PA | Hold/Staging<br>Peak: 7 (2025-06-05)<br>Mean ADP: 1.4\",\"<b>PARKLAND HOSPITAL<\\/b><br>TX | Medical<br>Peak: 3 (2025-09-24)<br>Mean ADP: 0\",\"<b>PARKVIEW REGIONAL MEDICAL CENTER<\\/b><br>IN | Medical<br>Peak: 1 (2025-03-29)<br>Mean ADP: 0\",\"<b>PLATTE COUNTY JAIL<\\/b><br>MO | Non-Dedicated<br>Peak: 1 (2025-03-07)<br>Mean ADP: 0\",\"<b>PLATTE COUNTY JAIL<\\/b><br>WY | Federal<br>Peak: 11 (2025-07-11)<br>Mean ADP: 3\",\"<b>PALMDALE REGIONAL MEDICAL CENTER<\\/b><br>CA | Medical<br>Peak: 1 (2024-12-19)<br>Mean ADP: 0\",\"<b>PROMEDICA MONROE REG HOSP<\\/b><br>MI | Medical<br>Peak: 1 (2025-09-11)<br>Mean ADP: 0\",\"<b>POLK COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 23 (2025-09-22)<br>Mean ADP: 0.1\",\"<b>PORTLAND, ME HOLDROOM<\\/b><br>ME | Hold/Staging<br>Peak: 3 (2025-06-05)<br>Mean ADP: 0.1\",\"<b>PORTLAND DISTRICT OFFICE<\\/b><br>OR | Hold/Staging<br>Peak: 19 (2025-01-26)<br>Mean ADP: 2\",\"<b>POTTER COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2025-04-06)<br>Mean ADP: 0\",\"<b>NEW YORK PRESBYTERIAN HOSPITAL<\\/b><br>NY | Medical<br>Peak: 5 (2025-08-30)<br>Mean ADP: 0.7\",\"<b>PRAIRIELAND SUBOFFICE HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 81 (2025-09-20)<br>Mean ADP: 0.9\",\"<b>PROHOLD<\\/b><br>RI | Hold/Staging<br>Peak: 8 (2025-04-11)<br>Mean ADP: 1.3\",\"<b>PRESBYTERIAN HOSP ABQ<\\/b><br>NM | Medical<br>Peak: 2 (2025-03-26)<br>Mean ADP: 0.1\",\"<b>PROVO HOLD ROOM<\\/b><br>UT | Hold/Staging<br>Peak: 10 (2025-08-22)<br>Mean ADP: 1.3\",\"<b>PROVIDENCE MEDICAL GROUP<\\/b><br>KS | Medical<br>Peak: 1 (2025-07-04)<br>Mean ADP: 0\",\"<b>PUEBLO COUNTY JAIL<\\/b><br>CO | Federal<br>Peak: 1 (2025-05-14)<br>Mean ADP: 0\",\"<b>PUEBLO HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 15 (2025-04-27)<br>Mean ADP: 1.1\",\"<b>PARKVIEW HOSPITAL RANDALLIA<\\/b><br>IN | Medical<br>Peak: 1 (2025-09-06)<br>Mean ADP: 0\",\"<b>PARADISE VALLEY HOSPITAL<\\/b><br>CA | Medical<br>Peak: 5 (2025-02-12)<br>Mean ADP: 1\",\"<b>PALMS WEST HOSPITAL<\\/b><br>FL | Medical<br>Peak: 2 (2025-05-22)<br>Mean ADP: 0\",\"<b>PRINCE WILLIAM<\\/b><br>VA | Federal<br>Peak: 1 (2025-01-04)<br>Mean ADP: 0\",\"<b>QUEEN'S MEDICAL CENTER<\\/b><br>HI | Medical<br>Peak: 1 (2025-08-11)<br>Mean ADP: 0.1\",\"<b>RAPP SEC CENTER<\\/b><br>VA | Federal<br>Peak: 16 (2025-02-25)<br>Mean ADP: 2\",\"<b>RICHMOND SUB-OFFICE HOLD<\\/b><br>VA | Hold/Staging<br>Peak: 277 (2025-09-07)<br>Mean ADP: 16.2\",\"<b>READING HOSPITAL<\\/b><br>PA | Medical<br>Peak: 1 (2025-06-15)<br>Mean ADP: 0\",\"<b>RED RIVER HOSPITAL<\\/b><br>TX | Medical<br>Peak: 1 (2024-11-25)<br>Mean ADP: 0.2\",\"<b>RALEIGH HOLD ROOM<\\/b><br>NC | Hold/Staging<br>Peak: 14 (2025-07-11)<br>Mean ADP: 3.7\",\"<b>REDDING HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 7 (2025-08-26)<br>Mean ADP: 0.6\",\"<b>RENO HOLD ROOM<\\/b><br>NV | Hold/Staging<br>Peak: 10 (2025-05-05)<br>Mean ADP: 0.2\",\"<b>RIO GRANDE ST.HOSPITAL<\\/b><br>TX | Medical<br>Peak: 7 (2025-09-04)<br>Mean ADP: 0\",\"<b>RIO GRANDE VALLEY STAGING<\\/b><br>TX | Hold/Staging<br>Peak: 21 (2025-02-06)<br>Mean ADP: 0.6\",\"<b>RICHLAND HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 4 (2025-02-05)<br>Mean ADP: 0.3\",\"<b>ROCK ISLAND HOLD ROOM<\\/b><br>IL | Hold/Staging<br>Peak: 6 (2025-03-07)<br>Mean ADP: 0.8\",\"<b>ROANOKE SUB-OFFICE HOLD ROOM<\\/b><br>VA | Hold/Staging<br>Peak: 6 (2025-05-13)<br>Mean ADP: 0.7\",\"<b>RANDALL COUNTY JAIL<\\/b><br>TX | Federal<br>Peak: 1 (2025-04-26)<br>Mean ADP: 0\",\"<b>ROCHESTER GENERAL HOSPITAL<\\/b><br>NY | Medical<br>Peak: 1 (2025-02-18)<br>Mean ADP: 0\",\"<b>ROCK ISLAND COUNTY JAIL<\\/b><br>IL | Federal<br>Peak: 1 (2025-08-15)<br>Mean ADP: 0\",\"<b>ROANOKE CITY JAIL<\\/b><br>VA | Federal<br>Peak: 13 (2025-09-08)<br>Mean ADP: 1.4\",\"<b>RAPID CITY HOLD ROOM<\\/b><br>SD | Hold/Staging<br>Peak: 7 (2025-08-06)<br>Mean ADP: 0.3\",\"<b>ROSWELL HOLD ROOM<\\/b><br>NM | Hold/Staging<br>Peak: 16 (2025-09-17)<br>Mean ADP: 2.1\",\"<b>RIO VISTA BEHV HLTH HSP<\\/b><br>TX | Medical<br>Peak: 7 (2025-09-08)<br>Mean ADP: 0.7\",\"<b>SANTA ANA DRO HOLDROOM<\\/b><br>CA | Hold/Staging<br>Peak: 150 (2025-06-11)<br>Mean ADP: 11.3\",\"<b>SACRAMENTO HOLD<\\/b><br>CA | Hold/Staging<br>Peak: 35 (2025-07-27)<br>Mean ADP: 3.3\",\"<b>SANTA ANA CITY JAIL<\\/b><br>CA | Non-Dedicated<br>Peak: 1 (2025-05-08)<br>Mean ADP: 0\",\"<b>SAN ANGELO HOLDROOM<\\/b><br>TX | Hold/Staging<br>Peak: 20 (2025-01-21)<br>Mean ADP: 3.3\",\"<b>SAIPAIN HOLD<\\/b><br>MP | Hold/Staging<br>Peak: 1 (2024-11-15)<br>Mean ADP: 0\",\"<b>SAN JUAN SUB-OFFICE HOLD ROOM<\\/b><br>PR | Hold/Staging<br>Peak: 50 (2025-06-04)<br>Mean ADP: 3.1\",\"<b>SALISBURY HOLD ROOM<\\/b><br>MD | Hold/Staging<br>Peak: 23 (2025-08-05)<br>Mean ADP: 2.1\",\"<b>SALINE COUNTY JAIL<\\/b><br>NE | Non-Dedicated<br>Peak: 7 (2025-09-09)<br>Mean ADP: 0\",\"<b>SARASOTA COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 10 (2025-05-13)<br>Mean ADP: 1.3\",\"<b>SAN BERNARDINO HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 38 (2025-06-20)<br>Mean ADP: 5.6\",\"<b>SAN BERNARDINO CO. JAIL<\\/b><br>CA | Federal<br>Peak: 1 (2025-08-09)<br>Mean ADP: 0\",\"<b>SCOTT COUNTY JAIL<\\/b><br>IA | Federal<br>Peak: 7 (2025-07-28)<br>Mean ADP: 1.1\",\"<b>SCOTTS BLUFF CO JAIL<\\/b><br>NE | Federal<br>Peak: 2 (2025-04-21)<br>Mean ADP: 0.1\",\"<b>SHARP CHULA VISTA MEDICAL CENTER<\\/b><br>CA | Medical<br>Peak: 3 (2025-03-14)<br>Mean ADP: 0.3\",\"<b>SEATTLE FIELD OFFICE HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 59 (2025-06-05)<br>Mean ADP: 4.7\",\"<b>SIOUX FALLS HOLD ROOM<\\/b><br>SD | Hold/Staging<br>Peak: 20 (2025-08-29)<br>Mean ADP: 0.5\",\"<b>SFR HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 44 (2025-06-04)<br>Mean ADP: 4.8\",\"<b>ST. GEORGE, UT HOLDROOM<\\/b><br>UT | Hold/Staging<br>Peak: 9 (2025-01-26)<br>Mean ADP: 0.7\",\"<b>SUMMERLIN HOSPITAL MEDICAL CENTER<\\/b><br>NV | Medical<br>Peak: 1 (2025-07-23)<br>Mean ADP: 0\",\"<b>SIOUX COUNTY JAIL<\\/b><br>IA | Federal<br>Peak: 10 (2025-09-08)<br>Mean ADP: 0.5\",\"<b>SAN JUAN AIRPORT HOLD ROOM<\\/b><br>PR | Hold/Staging<br>Peak: 24 (2024-12-22)<br>Mean ADP: 1.6\",\"<b>SALT LAKE CITY HOLD ROOM<\\/b><br>UT | Hold/Staging<br>Peak: 48 (2025-07-09)<br>Mean ADP: 10.8\",\"<b>ST LUKE'S HEALTH - THE WOODLANDS<\\/b><br>TX | Medical<br>Peak: 1 (2025-02-05)<br>Mean ADP: 0\",\"<b>SANTA MARIA SUB OFFICE ERO<\\/b><br>CA | Hold/Staging<br>Peak: 19 (2025-09-12)<br>Mean ADP: 3.4\",\"<b>ST. MARY'S CO DET CNTR<\\/b><br>MD | Non-Dedicated<br>Peak: 1 (2025-09-08)<br>Mean ADP: 0\",\"<b>SEMINOLE COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 6 (2025-07-16)<br>Mean ADP: 1.1\",\"<b>SAN ANTONIO DRO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 145 (2025-06-04)<br>Mean ADP: 19.6\",\"<b>SAN DIEGO COUNTY JAIL<\\/b><br>CA | Non-Dedicated<br>Peak: 1 (2025-07-07)<br>Mean ADP: 0.2\",\"<b>SND DISTRICT STAGING<\\/b><br>CA | Hold/Staging<br>Peak: 68 (2025-09-19)<br>Mean ADP: 15.7\",\"<b>SNJ HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 2 (2024-12-03)<br>Mean ADP: 0\",\"<b>ERO HOLD ROOM (SPRINGFIELD MO)<\\/b><br>MO | Hold/Staging<br>Peak: 62 (2025-09-24)<br>Mean ADP: 1.2\",\"<b>BISHOP HENRY WHIPPLE FED BLDG<\\/b><br>MN | Hold/Staging<br>Peak: 87 (2025-02-12)<br>Mean ADP: 11.5\",\"<b>SPOKANE HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 17 (2025-04-28)<br>Mean ADP: 1.7\",\"<b>SPOTSYLVANIA REG MED CTR<\\/b><br>VA | Medical<br>Peak: 1 (2024-10-01)<br>Mean ADP: 0\",\"<b>SANTA ROSA COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-02-17)<br>Mean ADP: 0\",\"<b>SOUTHSIDE HOSP NORTHWELL HLTH<\\/b><br>NY | Medical<br>Peak: 2 (2025-06-06)<br>Mean ADP: 0\",\"<b>SAINT ALBANS HOLD ROOM<\\/b><br>VT | Hold/Staging<br>Peak: 7 (2024-11-12)<br>Mean ADP: 0.4\",\"<b>ST CHARLES PARISH JAIL<\\/b><br>LA | Non-Dedicated<br>Peak: 1 (2025-08-23)<br>Mean ADP: 0\",\"<b>SOUTH TEXAS/PEARSALL HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 51 (2025-07-03)<br>Mean ADP: 4.8\",\"<b>ST ELIZABETH YOUNGSTOWN HOSPITAL<\\/b><br>OH | Medical<br>Peak: 2 (2025-09-16)<br>Mean ADP: 0.1\",\"<b>ST FRANCIS HOSPITAL<\\/b><br>GA | Medical<br>Peak: 2 (2024-11-10)<br>Mean ADP: 0\",\"<b>ST JOHN'S HOSPITAL CAMARILLO<\\/b><br>CA | Medical<br>Peak: 1 (2025-08-04)<br>Mean ADP: 0\",\"<b>ST JOSEPH MEDICAL CENTER<\\/b><br>WA | Medical<br>Peak: 5 (2025-03-18)<br>Mean ADP: 0.9\",\"<b>ST. JOHN'S COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 4 (2025-02-21)<br>Mean ADP: 0.2\",\"<b>ST. JOSEPH'S HOSPITAL & MED. CEN.<\\/b><br>AZ | Medical<br>Peak: 1 (2025-04-05)<br>Mean ADP: 0.1\",\"<b>SAINT JOSEPH HOSPITAL<\\/b><br>CO | Medical<br>Peak: 1 (2024-10-04)<br>Mean ADP: 0.1\",\"<b>STOCKTON STAGING FACILITY<\\/b><br>CA | Hold/Staging<br>Peak: 14 (2025-07-17)<br>Mean ADP: 2.1\",\"<b>ST. LOUIS HOLDROOM<\\/b><br>MO | Hold/Staging<br>Peak: 36 (2025-09-02)<br>Mean ADP: 3.8\",\"<b>ST. LUCIE COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 2 (2025-07-03)<br>Mean ADP: 0\",\"<b>ST MARY'S HOSPITAL<\\/b><br>AZ | Medical<br>Peak: 1 (2025-07-02)<br>Mean ADP: 0\",\"<b>ST MARY MEDICAL CENTER<\\/b><br>CA | Medical<br>Peak: 4 (2025-06-19)<br>Mean ADP: 0.5\",\"<b>STRONG MEMORIAL HOSPITAL<\\/b><br>NY | Medical<br>Peak: 1 (2024-10-13)<br>Mean ADP: 0.1\",\"<b>STUART HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 53 (2025-09-18)<br>Mean ADP: 3\",\"<b>SUFFOLK CO.CORREC FAC<\\/b><br>NY | Federal<br>Peak: 1 (2025-09-14)<br>Mean ADP: 0\",\"<b>SUMMIT COUNTY JAIL<\\/b><br>UT | Non-Dedicated<br>Peak: 1 (2025-01-07)<br>Mean ADP: 0\",\"<b>SUMTER COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 10 (2025-03-26)<br>Mean ADP: 0.8\",\"<b>SUTTER MED CTR SACRAMENTO<\\/b><br>CA | Medical<br>Peak: 1 (2025-07-18)<br>Mean ADP: 0\",\"<b>SUWANNEE COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-05-22)<br>Mean ADP: 0\",\"<b>SIOUX CITY HOLD ROOM<\\/b><br>IA | Hold/Staging<br>Peak: 3 (2024-11-04)<br>Mean ADP: 0.1\",\"<b>SYRACUSE HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 14 (2025-09-15)<br>Mean ADP: 0.6\",\"<b>TACOMA GENERAL HOSPITAL<\\/b><br>WA | Medical<br>Peak: 1 (2024-11-25)<br>Mean ADP: 0\",\"<b>TALLAHASSEE HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 45 (2025-08-20)<br>Mean ADP: 6.5\",\"<b>TALLAHATCHIE CO CORR FACILITY<\\/b><br>MS | Federal<br>Peak: 1 (2025-05-07)<br>Mean ADP: 0\",\"<b>TAMPA HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 84 (2025-08-08)<br>Mean ADP: 16.5\",\"<b>TAYLOR COUNTY ADULT DET.<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2025-02-24)<br>Mean ADP: 0\",\"<b>TELLER COUNTY JAIL<\\/b><br>CO | Non-Dedicated<br>Peak: 2 (2025-02-02)<br>Mean ADP: 0\",\"<b>TWIN FALLS HOLD ROOM<\\/b><br>ID | Hold/Staging<br>Peak: 6 (2025-01-15)<br>Mean ADP: 0.4\",\"<b>TURNER GUIFORD KNIGHT (TGK) JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 27 (2025-08-22)<br>Mean ADP: 3.8\",\"<b>TOM GREEN CTY JAIL<\\/b><br>TX | Federal<br>Peak: 15 (2025-03-21)<br>Mean ADP: 1.9\",\"<b>TX HEALTH METH HOSP HEB<\\/b><br>TX | Medical<br>Peak: 1 (2025-05-23)<br>Mean ADP: 0\",\"<b>TEX HEALTH HUGULEY HOSP<\\/b><br>TX | Medical<br>Peak: 4 (2025-07-16)<br>Mean ADP: 0.5\",\"<b>TX HLTH HARRIS METH HOSP<\\/b><br>TX | Medical<br>Peak: 2 (2025-08-07)<br>Mean ADP: 0.1\",\"<b>THOP MEMORIAL CAMPUS ELP<\\/b><br>TX | Medical<br>Peak: 1 (2025-07-04)<br>Mean ADP: 0\",\"<b>THOP SIERRA CAMPUS ELP<\\/b><br>TX | Medical<br>Peak: 1 (2025-04-25)<br>Mean ADP: 0\",\"<b>TITUS COUNTY JAIL<\\/b><br>TX | Federal<br>Peak: 6 (2025-03-28)<br>Mean ADP: 0.9\",\"<b>WESTERN TENNESSEE DET. FAC.<\\/b><br>TN | Federal<br>Peak: 39 (2025-09-12)<br>Mean ADP: 1.6\",\"<b>TRINITAS REGIONAL MED CTR<\\/b><br>NJ | Medical<br>Peak: 3 (2025-04-13)<br>Mean ADP: 0.8\",\"<b>TUCSON INS HOLD ROOM<\\/b><br>AZ | Hold/Staging<br>Peak: 15 (2025-06-06)<br>Mean ADP: 3.2\",\"<b>TULSA HOLD ROOM<\\/b><br>OK | Hold/Staging<br>Peak: 16 (2025-09-17)<br>Mean ADP: 1.7\",\"<b>TEXAS VISTA MEDICAL CENTER<\\/b><br>TX | Medical<br>Peak: 1 (2025-05-08)<br>Mean ADP: 0\",\"<b>TEXARKANA HOLDROOM<\\/b><br>AR | Hold/Staging<br>Peak: 6 (2025-05-21)<br>Mean ADP: 0.6\",\"<b>UCHICAGO MEDICINE HOSPITAL CHICAGO<\\/b><br>IL | Medical<br>Peak: 1 (2025-05-27)<br>Mean ADP: 0\",\"<b>UCHICAGO MEDICINE INGALLS MEMORIAL<\\/b><br>IL | Medical<br>Peak: 1 (2025-06-04)<br>Mean ADP: 0.1\",\"<b>UCHEALTH UNV HOSP OF CO<\\/b><br>CO | Medical<br>Peak: 3 (2025-06-08)<br>Mean ADP: 0.6\",\"<b>UNV CALIFORNIA SAN DIEGO HOSPITAL<\\/b><br>CA | Medical<br>Peak: 1 (2025-08-12)<br>Mean ADP: 0\",\"<b>UNIV HOSP GEAUGA MED CTR<\\/b><br>OH | Medical<br>Peak: 1 (2024-11-02)<br>Mean ADP: 0.1\",\"<b>UNION HOSPITAL<\\/b><br>IN | Medical<br>Peak: 1 (2025-04-29)<br>Mean ADP: 0\",\"<b>UHS WILSON MEDICAL CENTER<\\/b><br>NY | Medical<br>Peak: 1 (2025-09-22)<br>Mean ADP: 0\",\"<b>UMASS MEMORIAL MEDICAL CENTER<\\/b><br>MA | Medical<br>Peak: 1 (2025-03-31)<br>Mean ADP: 0\",\"<b>UNIVERSITY MED CENTER OF EL PASO<\\/b><br>TX | Medical<br>Peak: 3 (2025-01-29)<br>Mean ADP: 0.4\",\"<b>UNIVERSITY MEDICAL CENTER<\\/b><br>NV | Medical<br>Peak: 2 (2025-08-05)<br>Mean ADP: 0\",\"<b>UNITED MEMORIAL MED CTR<\\/b><br>NY | Medical<br>Peak: 1 (2024-11-26)<br>Mean ADP: 0.2\",\"<b>UNIVERSITY OF MIAMI HOSPITAL<\\/b><br>FL | Medical<br>Peak: 1 (2024-10-15)<br>Mean ADP: 0\",\"<b>UNITY HOSPITAL<\\/b><br>NY | Medical<br>Peak: 1 (2025-08-18)<br>Mean ADP: 0\",\"<b>UNION COUNTY JAIL<\\/b><br>SD | Federal<br>Peak: 21 (2025-02-06)<br>Mean ADP: 0.6\",\"<b>UNIVERSITY HOSPITAL<\\/b><br>NJ | Medical<br>Peak: 2 (2025-09-10)<br>Mean ADP: 0.2\",\"<b>UNIV OF MARYLAND MEDICAL CENTER<\\/b><br>MD | Medical<br>Peak: 2 (2025-02-28)<br>Mean ADP: 0.2\",\"<b>UNIVERSITY OF NEW MEXICO HOSPITAL<\\/b><br>NM | Medical<br>Peak: 1 (2025-03-27)<br>Mean ADP: 0.1\",\"<b>UPMC PRESBYTERIAN HOSPITAL<\\/b><br>PA | Medical<br>Peak: 1 (2025-06-19)<br>Mean ADP: 0.1\",\"<b>UNITY POINT HLTH ST LUKES HOSP<\\/b><br>IA | Medical<br>Peak: 1 (2025-09-04)<br>Mean ADP: 0.1\",\"<b>UNITYPOINT HLTH ST LUKES HOSP SXC<\\/b><br>IA | Medical<br>Peak: 1 (2025-06-02)<br>Mean ADP: 0\",\"<b>URSULA CENTRALIZED PROCESSING CNTR<\\/b><br>TX | Federal<br>Peak: 463 (2025-07-11)<br>Mean ADP: 31.6\",\"<b>UVA UNIV Hospital Center<\\/b><br>VA | Medical<br>Peak: 1 (2025-07-10)<br>Mean ADP: 0\",\"<b>UVALDE COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 2 (2025-07-11)<br>Mean ADP: 0\",\"<b>UNIVERSITY HOSPITAL<\\/b><br>TX | Medical<br>Peak: 6 (2025-01-20)<br>Mean ADP: 1.3\",\"<b>VAL VERDE DETENTION CENTER<\\/b><br>TX | Federal<br>Peak: 35 (2025-06-17)<br>Mean ADP: 3.6\",\"<b>VALLEY BAPTIST HOSPITAL<\\/b><br>TX | Medical<br>Peak: 12 (2025-06-21)<br>Mean ADP: 5.4\",\"<b>VCU HEALTH TAPPAHANNOCK HOSPITAL<\\/b><br>VA | Medical<br>Peak: 1 (2025-05-06)<br>Mean ADP: 0\",\"<b>VENTURA CUSTODY CASE<\\/b><br>CA | Hold/Staging<br>Peak: 80 (2025-07-11)<br>Mean ADP: 5.9\",\"<b>VIRGINIA BEACH<\\/b><br>VA | Non-Dedicated<br>Peak: 2 (2025-08-15)<br>Mean ADP: 0.1\",\"<b>VIRGINIA PENINSULA REG. JAIL<\\/b><br>VA | Federal<br>Peak: 1 (2025-07-11)<br>Mean ADP: 0\",\"<b>VRK PRCS<\\/b><br>NY | Hold/Staging<br>Peak: 12 (2025-09-23)<br>Mean ADP: 0.2\",\"<b>VT. DEPT. OF CORRECTIONS<\\/b><br>VT | Non-Dedicated<br>Peak: 1 (2025-05-31)<br>Mean ADP: 0\",\"<b>VICTOR VALLEY GLOBAL MED CENTER<\\/b><br>CA | Medical<br>Peak: 9 (2025-08-29)<br>Mean ADP: 1.7\",\"<b>SHREVEPORT HOLD ROOM<\\/b><br>LA | Hold/Staging<br>Peak: 8 (2025-08-28)<br>Mean ADP: 1.1\",\"<b>VALLEYWISE HEALTH MED CTR<\\/b><br>AZ | Medical<br>Peak: 2 (2024-10-26)<br>Mean ADP: 0.4\",\"<b>WASHINGTON COUNTY JAIL<\\/b><br>MN | Federal<br>Peak: 4 (2025-02-07)<br>Mean ADP: 0.2\",\"<b>WAKULLA COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-05-07)<br>Mean ADP: 0\",\"<b>WALTON COUNTY D.O.C.<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-06-09)<br>Mean ADP: 0\",\"<b>WASHINGTON CO. DETENTION<\\/b><br>MD | Non-Dedicated<br>Peak: 1 (2025-07-10)<br>Mean ADP: 0\",\"<b>WASHINGTON FIELD OFFICE<\\/b><br>VA | Hold/Staging<br>Peak: 127 (2025-08-23)<br>Mean ADP: 17.3\",\"<b>WACO DRO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 24 (2025-06-30)<br>Mean ADP: 4.9\",\"<b>WEBB COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2025-08-18)<br>Mean ADP: 0\",\"<b>WESTMINSTER CUSTODY<\\/b><br>CA | Hold/Staging<br>Peak: 8 (2025-07-04)<br>Mean ADP: 1.6\",\"<b>WICHITA HOLDROOM<\\/b><br>KS | Hold/Staging<br>Peak: 2 (2025-05-31)<br>Mean ADP: 0\",\"<b>WILSON COUNTY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 8 (2025-06-16)<br>Mean ADP: 0.1\",\"<b>WEST KENDALL BAPTIST HOSP<\\/b><br>FL | Medical<br>Peak: 5 (2025-02-16)<br>Mean ADP: 0.7\",\"<b>WEST MIAMI DADE BAPT HEALTH EMERG<\\/b><br>FL | Medical<br>Peak: 3 (2025-03-03)<br>Mean ADP: 0.3\",\"<b>WHITE MEMORIAL HOSPITAL<\\/b><br>CA | Medical<br>Peak: 6 (2025-07-11)<br>Mean ADP: 0.7\",\"<b>WENATCHEE HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 4 (2024-11-04)<br>Mean ADP: 0.2\",\"<b>WILLIAMSPORT HOLD ROOM<\\/b><br>PA | Hold/Staging<br>Peak: 21 (2025-08-19)<br>Mean ADP: 0.5\",\"<b>EASTERN REGIONAL JAIL<\\/b><br>WV | Federal<br>Peak: 16 (2025-03-11)<br>Mean ADP: 1.1\",\"<b>POTOMAC HIGHLANDS REGIONAL JAIL<\\/b><br>WV | Non-Dedicated<br>Peak: 1 (2025-08-28)<br>Mean ADP: 0\",\"<b>WENTWORTH DOUGLAS HOSPITAL<\\/b><br>NH | Medical<br>Peak: 1 (2024-10-06)<br>Mean ADP: 0.1\",\"<b>YAKIMA SUB-OFFICE<\\/b><br>WA | Hold/Staging<br>Peak: 12 (2025-06-04)<br>Mean ADP: 1.2\",\"<b>YORK COUNTY JAIL, PA<\\/b><br>PA | Non-Dedicated<br>Peak: 1 (2024-10-01)<br>Mean ADP: 1\",\"<b>YORK COUNTY DETENTION CENTER<\\/b><br>SC | Federal<br>Peak: 4 (2025-05-11)<br>Mean ADP: 0.5\",\"<b>YORK HOLD ROOM<\\/b><br>PA | Hold/Staging<br>Peak: 16 (2025-04-23)<br>Mean ADP: 3\",\"<b>YUMA REGIONAL MED CTR<\\/b><br>AZ | Medical<br>Peak: 1 (2025-05-09)<br>Mean ADP: 0\",\"<b>YUMA HOLDROOM<\\/b><br>AZ | Hold/Staging<br>Peak: 8 (2025-07-31)<br>Mean ADP: 1\"],null,[\"SW VIRGINIA REG JAIL AUTH-ABG FAC (VA: peak 47)\",\"ALBUQUERQUE HOLD ROOM (NM: peak 45)\",\"ABRAXAS ACADEMY DETENTION CENTER (PA: peak 1)\",\"ADDISON COUNTY JAIL (VT: peak 1)\",\"ADVENTIST HEALTH BAKERSFIELD (CA: peak 1)\",\"ADVENTIST HEALTH CASTLE (HI: peak 1)\",\"ADVENTIST HEALTH DELANO (CA: peak 1)\",\"GUAM ERO HOLD ROOM (GU: peak 4)\",\"AGUADILLA SPC (PR: peak 60)\",\"ANAHEIM GLOBAL MEDICAL CENTER (CA: peak 3)\",\"ALTRU HOSPITAL GRAND FORKS (ND: peak 1)\",\"COOK INLET PRETRIAL, ANCH (AK: peak 1)\",\"FAIRBANKS CORR CTR (AK: peak 1)\",\"HIGHLAND MTN COR CTR (AK: peak 2)\",\"KETCHIKAN REGIONAL CC (AK: peak 1)\",\"LEMON CREEK, JUNEAU,AK (AK: peak 1)\",\"MATSU PRETRIAL, PALMER AK (AK: peak 1)\",\"ALAMO POLICE DEPT. (TX: peak 14)\",\"ALBANY HOLDROOM (NY: peak 16)\",\"ALEXANDRIA CITY JAIL (VA: peak 1)\",\"ALAMOSA HOLDROOM (CO: peak 7)\",\"AMARILLO HOLD ROOM (TX: peak 17)\",\"ANCHORAGE JAIL (AK: peak 43)\",\"ANCHORAGE SUB-OFFICE HOLD ROOM (AK: peak 5)\",\"ANSON GENERAL HOSPITAL (TX: peak 1)\",\"ALVARADO PARKWAY INSTITUTE (CA: peak 5)\",\"ARAPAHOE COUNTY JAIL (CO: peak 1)\",\"ARROWHEAD REGIONAL MED CENTER (CA: peak 3)\",\"ATLANTA PRETRIAL DETN CTR (GA: peak 3)\",\"ATLANTA DIST. HOLD RM (GA: peak 168)\",\"ATHENS, TX HOLD ROOM (TX: peak 14)\",\"AUSTIN DRO HOLD ROOM (TX: peak 48)\",\"ARIZONA STATE PRISON - YUMA (AZ: peak 3)\",\"BALDWIN COUNTY COR. CENTER (AL: peak 28)\",\"BALTIMORE HOLD ROOM (MD: peak 120)\",\"BANNER UNIVERSITY MEDICAL PHOENIX (AZ: peak 1)\",\"BARTOW CO JAIL (GA: peak 1)\",\"BAYAMON HOSPITAL (PR: peak 2)\",\"BAY COUNTY (FL: peak 4)\",\"BRONSON BATTLE CREEK HOSP (MI: peak 1)\",\"BEDFORD CITY JAIL (TX: peak 1)\",\"BELLEVUE HOSPITAL, MANHAT (NY: peak 1)\",\"BELL COUNTY JAIL (TX: peak 5)\",\"BERNALILLO COUNTY DET CTR (NM: peak 1)\",\"BUFFALO GENERAL HOSPITAL (NY: peak 1)\",\"BIRMINGHAM HOLD ROOM (AL: peak 18)\",\"BETH ISRAEL DEACONESS HOSP (MA: peak 3)\",\"BI INCORORATED, GEO GROUP COMPANY (CO: peak 4)\",\"BILLINGS HOLD ROOM (MT: peak 1)\",\"BANNER IRONWOOD MED CTR (AZ: peak 3)\",\"BAKERFIELD HOLD (CA: peak 49)\",\"BOWLING GREEN HOLD ROOM (KY: peak 1)\",\"BLACKWELL REGIONAL HOSPITAL (OK: peak 1)\",\"BAPTIST MEDICAL CENTER (TX: peak 1)\",\"BANNER MEDICAL CTR TUCSON (AZ: peak 1)\",\"BOISE HOLD ROOM (ID: peak 8)\",\"USP CANAAN (PA: peak 1)\",\"NASHVILLE COMM. CORR. (TN: peak 3)\",\"DEVENS FMC (MA: peak 1)\",\"GUAYNABO MDC (SAN JUAN) (PR: peak 16)\",\"LOMPOC FCI (CA: peak 10)\",\"LOS ANGELES MET.DET.CTR. (CA: peak 1)\",\"OAKDALE FED.DET.CENTER (LA: peak 4)\",\"PHOENIX FED.CORR.INST. (AZ: peak 1)\",\"MCRAE CORRECTIONAL FACILITY, CCA (GA: peak 1)\",\"SEATAC FED.DET.CENTER (WA: peak 1)\",\"SPRINGFIELD FED.MED.CNTR (MO: peak 2)\",\"TUCSON FED.CORR.INST. (AZ: peak 1)\",\"FCI VICTORVILLE (CA: peak 7)\",\"BOSTON HOLDROOM (MA: peak 206)\",\"BOSTON SPC (MA: peak 2)\",\"BRADFORD COUNTY JAIL (FL: peak 1)\",\"BREVARD COUNTY JAIL COMPLEX (FL: peak 9)\",\"BROWARD GENERAL MEDICAL CENTER (FL: peak 3)\",\"BRONSON METHODIST HOSPITAL (MI: peak 2)\",\"BROWARD COUNTY JAIL (FL: peak 14)\",\"BROOKS COUNTY JAIL (CONTRACT) (TX: peak 90)\",\"BROWN COUNTY JAIL (WI: peak 13)\",\"BROADVIEW SERVICE STAGING (IL: peak 245)\",\"BIG SPRING HOLD ROOM (TX: peak 10)\",\"BAYLOR SCOTT WHITE MD CTR (TX: peak 1)\",\"BAYLOR SCOTT WHITE MED RR (TX: peak 1)\",\"COREWELL HLTH GR HOSP-BUTTERWORTH (MI: peak 1)\",\"BUFFALO HOLD ROOM (NY: peak 45)\",\"BURNET COUNTY JAIL (TX: peak 4)\",\"CACHE CO. JAIL (UT: peak 13)\",\"CAMPBELL COUNTY JAIL (WY: peak 4)\",\"CAMERON COUNTY JAIL (TX: peak 1)\",\"CASCADE COUNTY JAIL, MT (MT: peak 5)\",\"CSP-SACRAMENTO (CA: peak 1)\",\"BUFFALO USBP HOLD ROOM (NY: peak 20)\",\"Cabarrus County Jail (NC: peak 6)\",\"CROSS CREEK HOSPITAL (TX: peak 1)\",\"CEDAR CREST HOSP TREAT (TX: peak 2)\",\"CONTRA COSTA REG MED CTR (CA: peak 1)\",\"CENTRACARE RICE MEMORIAL HOSP (MN: peak 1)\",\"CENTRA HEALTH (VA: peak 1)\",\"CASA GRANDE REG. MED. CENTER (AZ: peak 3)\",\"CHARLOTTE AMALIE HOLDROOM (VI: peak 4)\",\"CHANDLER REG MED CTR (AZ: peak 2)\",\"CHARLESTON COUNTY CORRECT (SC: peak 1)\",\"CHAVEZ DET CRT (NM: peak 16)\",\"CHESTERFIELD CO. JAIL (VA: peak 2)\",\"CHICAGO HOLD ROOM (IL: peak 7)\",\"CHI ST LUKE'S HEALTH MEM (TX: peak 2)\",\"CHARLESTON, SC HOLD ROOM (SC: peak 69)\",\"COURTHOUSE USM CNTL ISLIP (NY: peak 1)\",\"CHAMPLAIN HOLD ROOM (NY: peak 8)\",\"CHIPPENHAM HOSPITAL - RICHMOND (VA: peak 1)\",\"CHRISTIAN COUNTY JAIL (KY: peak 1)\",\"CHARLOTTE COUNTY JAIL (FL: peak 1)\",\"CHESAPEAKE CITY JAIL (VA: peak 23)\",\"CHRISTUS SANTA ROSA HOSPITAL - MED (TX: peak 1)\",\"CHEYENNE HOLDROOM (WY: peak 3)\",\"CIBOLA GENERAL HOSPITAL (NM: peak 1)\",\"CIBOLA COUNTY DET CTR (NM: peak 1)\",\"CINCINNATI HOLDROOM (OH: peak 4)\",\"CENTRAL ISLIP HOLD ROOM (NY: peak 45)\",\"CITRUS COUNTY JAIL (FL: peak 1)\",\"HCA FLORIDA KENDALL HOSPITAL (FL: peak 7)\",\"CLEVELAND HOLD ROOM (OH: peak 14)\",\"COLUMBUS HOLDROOM (OH: peak 10)\",\"CHARLOTTE HOLD ROOM (NC: peak 48)\",\"BATAVIA COMMAND CENTER HOLDROOM (NY: peak 1)\",\"CHATTANOOGA HOLD ROOM (TN: peak 12)\",\"CENTEGRA HOSPITAL (IL: peak 1)\",\"CENTRAL WASHINGTON HOSPITAL (WA: peak 1)\",\"COLUMBIA, SC HOLDROOM (SC: peak 31)\",\"COBB CO SHERIFFS OFC ADULT DET CTR (GA: peak 4)\",\"COLO DEPT OF CORRECTIONS (CO: peak 1)\",\"COLUMBIA CARE CENTER (SC: peak 10)\",\"COLUMBIA COUNTY JAIL (FL: peak 1)\",\"CONNALLY MEMORIAL MEDICAL CENTER (TX: peak 1)\",\"COXHEALTH MEDICAL CENTER SOUTH (MO: peak 1)\",\"CRAIG HOLDROOM (CO: peak 4)\",\"CEDAR RAPIDS HOLD ROOM (IA: peak 17)\",\"CORPUS CHRISTI EOR HOLD ROOM (TX: peak 8)\",\"COLO SPRINGS DEN HSI HOLD (CO: peak 7)\",\"CHI ST LUKE'S H M LUFKIN (TX: peak 1)\",\"CASPER HOLDROOM (WY: peak 6)\",\"CENTRA SOUTHSIDE COMM HOSP (VA: peak 1)\",\"CULPEPER CO. ADULT DET. CENTER (VA: peak 1)\",\"CENTRAL VALLEY ANNEX (CA: peak 1)\",\"CENTRAL VA REGIONAL JAIL (VA: peak 2)\",\"DALLAS F.O. HOLD (TX: peak 225)\",\"DEKALB COUNTY DETENTION CENTER (AL: peak 1)\",\"DENVER HOLD ROOM (CO: peak 35)\",\"DENVER COUNTY JAIL (CO: peak 1)\",\"DETROIT HOLDROOM (MI: peak 47)\",\"DEL RIO DRO HOLD ROOM (TX: peak 12)\",\"DENVER HEALTH MEDICAL CENTER (CO: peak 1)\",\"DONA ANA COUNTY DETENTION FACILITY (NM: peak 1)\",\"DORCHESTER CO DET CTR (SC: peak 10)\",\"DOUGLAS COUNTY DETENTION CENTER (CO: peak 1)\",\"DSMC - DEL SOL MEDICAL CENTER (TX: peak 7)\",\"DES MOINES HOLD ROOM (IA: peak 3)\",\"DESERT VALLEY HOSPITAL (CA: peak 10)\",\"DURANGO HOLDROOM (CO: peak 6)\",\"DOVER HOLDROOM (DE: peak 10)\",\"DESERT VIEW HOSPITAL (NV: peak 1)\",\"ERIE COUNTY MEDICAL CENTER (NY: peak 2)\",\"EL CENTRO REGIONAL MED CTR (CA: peak 2)\",\"EL PASO COUNTY JAIL (TX) (TX: peak 2)\",\"ENLOE MEDICAL CENTER (CA: peak 2)\",\"EL PASO BEHAVIORAL HEALTH SYSTEM (TX: peak 13)\",\"EL PASO COUNTY DETENTION FACILITY (TX: peak 95)\",\"EL PASO LTAC HOSPITAL (TX: peak 3)\",\"EL PASO SOFT SIDED FACILITY (TX: peak 1606)\",\"ESKENAZI HEALTH (IN: peak 1)\",\"ESSEX COUNTY JAIL (NJ: peak 1)\",\"ETOWAH ERO HOLD ROOM (AL: peak 2)\",\"EUGENE HOLDROOM (OR: peak 9)\",\"FAYETTEVILLE HOLD ROOM (AR: peak 9)\",\"FACILITY 8 DETENTION FACILITY (CA: peak 1)\",\"FERNDALE HOLD ROOM (WA: peak 6)\",\"FINNEY COUNTY JAIL (KS: peak 11)\",\"BAKER C. I. (FL: peak 294)\",\"FT LAUDERDALE BEHAVOR HLTH CTR (FL: peak 11)\",\"CHARLOTTE CI, PUNTA GORDA (FL: peak 1)\",\"DADE CORRECTIONAL INST (FL: peak 7)\",\"FLORIDA SOFT-SIDED FACILITY-SOUTH (FL: peak 1482)\",\"FLAGLER COUNTY JAIL (FL: peak 12)\",\"FORT LAUDERDALE HOSPITAL (FL: peak 1)\",\"FLORENCE HOSPITAL (AZ: peak 5)\",\"FORT MYERS ERO HOLDROOM (FL: peak 29)\",\"FOND DU LAC COUNTY SHERIFF/JAIL (WI: peak 1)\",\"FRANKLIN COUNTY JAIL (PA: peak 2)\",\"FREDERICK HOLDROOM (CO: peak 7)\",\"FREDERICK COUNTY DET. CEN (MD: peak 1)\",\"FRESNO HOLDROOM (CA: peak 22)\",\"FRIO REGIONAL HOSPITAL (TX: peak 2)\",\"FORT SMITH HOLDROOM (AR: peak 4)\",\"GARVIN COUNTY JAIL (OK: peak 15)\",\"GASTON COUNTY JAIL (NC: peak 6)\",\"GARDEN CITY PROCESSING @ FINNEY CO (KS: peak 3)\",\"GRAND FORKS CO. JUVENILE (ND: peak 1)\",\"GRAND JUNCTION HOLDROOM (CO: peak 7)\",\"GLENDALE POLICE DEPT (CA: peak 22)\",\"GRADY MEMORIAL HOSPITAL (GA: peak 3)\",\"FRANKLIN HOUSE OF CORRECTIONS (MA: peak 1)\",\"GRAND FORKS HOLD ROOM (ND: peak 13)\",\"GEORGETOWN BEHAVIORAL HOSPITAL (TX: peak 1)\",\"GRAND ISLAND HOLD ROOM (NE: peak 1)\",\"GRAND RAPIDS HOLDROOM (MI: peak 9)\",\"GREER HOLD ROOM (SC: peak 7)\",\"GLENWOOD SPRINGS HOLDROOM (CO: peak 10)\",\"MIGRANT OPS CENTER MAIN AV622 (CU: peak 51)\",\"GUAM MEMORIAL HOSPITAL (GU: peak 5)\",\"HAILE DET. CENTER (ID: peak 2)\",\"HAMILTON CO. JAIL (TENN) (TN: peak 1)\",\"HARTFORD CORR CENTER (CT: peak 1)\",\"HARTFORD OFFICE (CT: peak 37)\",\"HARRISON DETENTION CENTER (MS: peak 1)\",\"ROLLING PLAINS DETENTION CENTER (TX: peak 1)\",\"HARRISONBURG HOLD ROOM (VA: peak 11)\",\"HCA FLORIDA MEMORIAL HOSPITAL (FL: peak 1)\",\"HCA HOUSTON HC CONROE (TX: peak 18)\",\"HENNEPIN COUNTY MED CTR (MN: peak 1)\",\"HARRIS COUNTY PSYCHIATRIC CENTER (TX: peak 3)\",\"HENDERSON HOSPITAL (NV: peak 1)\",\"HEL DISTRICT CUSTODY (MT: peak 2)\",\"HENDERSON COUNTY DET. FAC. (NC: peak 2)\",\"HENDRY COUNTY JAIL (FL: peak 1)\",\"HENDERSONVILLE HOLD ROOM (NC: peak 5)\",\"HENRICO COUNTY JAIL (VA: peak 1)\",\"HIGHLANDS BEHAVIORAL HEALTH (CO: peak 1)\",\"HARRIS HEALTH BEN TAUB HOSPITAL (TX: peak 1)\",\"HOUSTON HEALTHCARE HOSP (TX: peak 3)\",\"ERO HONOLULU SUB-OFFICE HOLD ROOM (HI: peak 4)\",\"HILLSBOROUGH COUNTY JAIL (FL: peak 40)\",\"HIDALGO COUNTY SHERIFF'S JAIL (TX: peak 1)\",\"B.R.R.J. HALIFAX (VA: peak 1)\",\"HARLINGEN HOLD ROOM (TX: peak 118)\",\"HARLINGEN MEDICAL CENTER (TX: peak 1)\",\"HENDRICK MEDICAL CENTER (TX: peak 2)\",\"HOUSTON FO HOLDROOM (TX: peak 18)\",\"HARLINGEN POLICE DEPT. (TX: peak 1)\",\"MIAMI BORDER PATROL (FL: peak 1)\",\"IDAHO FALLS HOLD ROOM (ID: peak 5)\",\"IMPERIAL SUB OFFICE HOLD ROOM (CA: peak 12)\",\"INDIANAPOLIS HOLD ROOM (IN: peak 130)\",\"INTEGRIS HEALTH BAPTIST MEDICAL (OK: peak 1)\",\"AZ REM OP COORD CENTER (AROCC) (AZ: peak 195)\",\"JACKSON MS HOLD ROOM (MS: peak 23)\",\"JACKSONVILLE SUB-OFFICE (FL: peak 35)\",\"JEFFERSON COUNTY JAIL (IL: peak 1)\",\"JFK INTERNATIONAL AP - T7 (NY: peak 23)\",\"Jamaica Hospital Med Ctr (NY: peak 1)\",\"JACK HARWELL DETENTION CENTER (TX: peak 6)\",\"JACKSON MEMORIAL HOSPITAL (FL: peak 2)\",\"JOHNSTON MEMORIAL HOSPITAL (VA: peak 1)\",\"JOHN PETER SMITH HOSPITAL (TX: peak 1)\",\"KANSAS CITY HOLDROOM (MO: peak 64)\",\"KARNES CTY CORR CTR (TX: peak 10)\",\"KARNES COUNTY CIVIL DET. FACILITY (TX: peak 9)\",\"KENMORE MERCY HOSPITAL (NY: peak 1)\",\"KERN COUNTY JAIL (LERDO) (CA: peak 2)\",\"KERN MEDICAL HOSPITAL (CA: peak 1)\",\"KINNEY COUNTY JAIL (TX: peak 4)\",\"KNOXVILLE HOLD ROOM (TN: peak 20)\",\"KODIAK CITY JAIL (AK: peak 1)\",\"PROMISE HOSPITAL (AZ: peak 3)\",\"KROME/MIAMI HUB (FL: peak 54)\",\"KROME HOLD ROOM (FL: peak 600)\",\"LACKAWANA CNTY JAIL, PA (PA: peak 1)\",\"LARAMIE COUNTY JAIL (WY: peak 8)\",\"LASALLE COUNTY JAIL (TX: peak 1)\",\"LAS CRUCES HOLD ROOM (NM: peak 7)\",\"LAWRENCE CO. JAIL, SD (SD: peak 5)\",\"HARRIS HEALTH LBJ HOSPITAL (TX: peak 1)\",\"LUBBOCK HOLD ROOM (TX: peak 17)\",\"LEVY COUNTY JAIL (FL: peak 1)\",\"LEXINGTON PROCESSING @ FAYETTE CO (KY: peak 3)\",\"LAHEY HOSPITAL &amp; MED CTR (MA: peak 2)\",\"LINCOLN COUNTY SHERIFF'S (MO: peak 4)\",\"LIRS - LFSRM FORT COLLINS LTFC CO (CO: peak 2)\",\"LOCKPORT MEMORIAL HOSPITAL (NY: peak 1)\",\"LOS ANGELES COUNTY JAIL-TWIN TOWER (CA: peak 1)\",\"LOS CUST CASE (CA: peak 455)\",\"LOUDOUN COUNTY (VA: peak 4)\",\"LOUISVILLE HOLD ROOM (KY: peak 23)\",\"LA PALMA CORR CTR APSO (AZ: peak 2)\",\"LOS ANGELES POLICE PD 77TH DIV. (CA: peak 1)\",\"LA PAZ REGIONAL HOSPITAL (AZ: peak 1)\",\"LITTLE ROCK HOLD ROOM (AR: peak 27)\",\"LAREDO DETENTION CENTER HOLD ROOM (TX: peak 115)\",\"LAREDO MEDICAL CENTER (TX: peak 2)\",\"LARKIN BEHAVIORAL HEALTH SVCS (FL: peak 12)\",\"LARKIN HOSPITAL (FL: peak 16)\",\"LOS FRESNOS HOLD ROOM (TX: peak 1)\",\"LEMUEL SHATTUCK HOSPITAL (MA: peak 1)\",\"LAS VEGAS HOLD ROOM (NV: peak 68)\",\"LEHIGH VALLEY HOSPITAL - POCONO (PA: peak 1)\",\"LOYOLA CENTER FOR HEALTH (IL: peak 2)\",\"MANATEE COUNTY DETENTION-ANNEX (FL: peak 7)\",\"MANCHESTER HOLDROOM (NH: peak 9)\",\"MARION CO JAIL (OR: peak 2)\",\"MARION COUNTY JAIL (FL: peak 11)\",\"MARTIN COUNTY JAIL (FL: peak 24)\",\"MAVERICK COUNTY JAIL (TX: peak 3)\",\"MCALLEN HOLD ROOM (TX: peak 59)\",\"MCLENNAN COUNTY JAIL (TX: peak 5)\",\"MAYO CLINIC HEALTH SYS ALBERT LEA (MN: peak 1)\",\"CHI HEALTH MIDLANDS HOSPITAL (NE: peak 1)\",\"MEDFORD SUB-OFFICE (OR: peak 14)\",\"MERCY HOSP DOWNTOWN BAKERSFIELD (CA: peak 1)\",\"MERCY MEDICAL CTR REDDING (CA: peak 1)\",\"MEMPHIS HOLD ROOM (TN: peak 25)\",\"MEMORIAL REGIONAL HOSP. (FL: peak 1)\",\"MESA COUNTY JAIL (CO: peak 1)\",\"METHODIST HOSPITAL (TX: peak 2)\",\"METRO DADE JAIL (FL: peak 25)\",\"MUNSON HEALTHCARE CADILLAC HOSP (MI: peak 1)\",\"M HEALTH FAIRVIEW SOUTHDALE HOSP (MN: peak 1)\",\"METHODIST HOSPITAL METROPOLITAN (TX: peak 2)\",\"MEMORIAL HERMANN NE HOSP (TX: peak 5)\",\"METHODIST HOSPITAL NORTHEAST (TX: peak 1)\",\"MILTON S. HERSHEY MEDICAL CENTER (PA: peak 1)\",\"METHODIST HOSPITAL STONE OAK (TX: peak 1)\",\"METHODIST HOSPITAL TEXSAN (TX: peak 2)\",\"MIAMI (MIRAMAR) HOLD ROOM (FL: peak 94)\",\"MIDLAND DETENTION CENTER (TX: peak 13)\",\"MIDLAND MEMORIAL HOSPITAL (TX: peak 1)\",\"MILWAUKEE HOLDROOM (WI: peak 22)\",\"MINICASSIA DET. CENTER (ID: peak 8)\",\"MIRIAM HOSPITAL (RI: peak 1)\",\"MIDLAND, TX ERO HOLDROOM (TX: peak 13)\",\"MOUNT LAUREL HOLD ROOM (NJ: peak 26)\",\"MCLAREN PORT HURON HOSP (MI: peak 1)\",\"MERCY MED CTR CEDAR RAPID (IA: peak 1)\",\"MONROE COUNTY SHERIFF/JAIL-MAIN (MI: peak 7)\",\"MONTGOMERY CITY JAIL (AL: peak 1)\",\"MOBILE HOLDROOM (AL: peak 35)\",\"MONMOUTH COUNTY JAIL (NJ: peak 1)\",\"MONROE COUNTY JAIL (FL: peak 3)\",\"MONTGOMERY CO MAC SIM BUTLER D.F. (AL: peak 2)\",\"MARIAN REGIONAL MEDICAL CENTER (CA: peak 1)\",\"MIDDLE RIVER REGIONAL JAIL (VA: peak 1)\",\"MERCY HOSPITAL SOUTH (MO: peak 1)\",\"MERCY HOSPITAL (MN: peak 1)\",\"MIAMI STAGING FACILITY (FL: peak 176)\",\"METHODIST SPECIALTY TRANSPLANT HOS (TX: peak 1)\",\"MONTGOMERY HOLD RM (TX: peak 221)\",\"MOUNT NITTANY MEDICAL CENTER (PA: peak 2)\",\"MOUNTAIN VISTA MED CTR (AZ: peak 2)\",\"PENN HIGHLANDS CLEARFIELD (PA: peak 1)\",\"MARY WASHINGTON HOSPITAL (VA: peak 1)\",\"MAYO CLINIC HEALTH SYS - MANKATO (MN: peak 2)\",\"NASSAU COUNTY JAIL (FL: peak 1)\",\"NASSAU COUNTY ICE TRAILER (NY: peak 13)\",\"NEWBURGH HOLDING (NY: peak 10)\",\"NORTH BROWARD MEDICAL CENTER (FL: peak 5)\",\"NEW/INS OS HOLD ROOM (NJ: peak 12)\",\"NORTHERN NEVADA MED CTR (NV: peak 1)\",\"NEW ORLEANS HOLD ROOM (LA: peak 5)\",\"NORFOLK CITY JAIL (VA: peak 1)\",\"NORFOLK SUB-OFFICE HOLD (VA: peak 16)\",\"NW REG JUV DET CTR (VA: peak 7)\",\"NORTH PLATTE HOLD ROOM (NE: peak 13)\",\"NASHVILLE HOLD ROOM (TN: peak 75)\",\"NASSAU UNIV MED CTR (NY: peak 3)\",\"NEW HANOVER CO DET CENTER (NC: peak 10)\",\"NORTHWEST REG. ADULT DET. (VA: peak 6)\",\"NYC HOLD ROOM (NY: peak 228)\",\"NYE COUNTY SHERIFF-PAHRUMP (NV: peak 90)\",\"GREAT MEADOW C.F. (NY: peak 1)\",\"WASHINGTON CORRECTIONAL (NY: peak 1)\",\"OAKDALE HOLDING ROOM (LA: peak 14)\",\"ORANGE CO GLOBAL MEDICAL CENTER (CA: peak 2)\",\"ORANGE REGIONAL MED CTR (NY: peak 2)\",\"OGDEN HOLD ROOM (UT: peak 13)\",\"OKLAHOMA CITY HOLD ROOM. (OK: peak 79)\",\"OTTO KAISER MEMORIAL HOSPITAL (TX: peak 1)\",\"OKMULGEE COUNTY JAIL (OK: peak 1)\",\"LASALLE CORR CTR OLLA (LA: peak 1)\",\"OMAHA FO HOLD (NE: peak 73)\",\"ORLANDO HOLD ROOM (FL: peak 126)\",\"OSCEOLA COUNTY JAIL (FL: peak 14)\",\"PALM BEACH COUNTY JAIL (FL: peak 4)\",\"PAM HEALTH SPECIALTY HOSPITAL 1 (TX: peak 2)\",\"PIEDMOUNT COLUMBUS REG MIDTOWN MC (GA: peak 1)\",\"PECOS HOLD ROOM (TX: peak 28)\",\"PDN HOLD ROOM (TX: peak 36)\",\"PHELPS HEALTH HOSPITAL (MO: peak 1)\",\"PHI DISTRICT OFFICE (PA: peak 33)\",\"PHOENIX DIST OFFICE (AZ: peak 90)\",\"PHOEBE PUTNEY MEMORIAL HOSP (GA: peak 1)\",\"PLAZA HEALTHCARE REHAB CENTER (NJ: peak 1)\",\"PIERCE COUNTY JAIL (ND: peak 1)\",\"PINAL COUNTY JAIL (AZ: peak 1)\",\"PITTSBURGH HOLDROOM (PA: peak 19)\",\"PIKE COUNTY ERO HOLD ROOM (PA: peak 7)\",\"PARKLAND HOSPITAL (TX: peak 3)\",\"PARKVIEW REGIONAL MEDICAL CENTER (IN: peak 1)\",\"PLATTE COUNTY JAIL (MO: peak 1)\",\"PLATTE COUNTY JAIL (WY: peak 11)\",\"PALMDALE REGIONAL MEDICAL CENTER (CA: peak 1)\",\"PROMEDICA MONROE REG HOSP (MI: peak 1)\",\"POLK COUNTY JAIL (FL: peak 23)\",\"PORTLAND, ME HOLDROOM (ME: peak 3)\",\"PORTLAND DISTRICT OFFICE (OR: peak 19)\",\"POTTER COUNTY JAIL (TX: peak 1)\",\"NEW YORK PRESBYTERIAN HOSPITAL (NY: peak 5)\",\"PRAIRIELAND SUBOFFICE HOLD ROOM (TX: peak 81)\",\"PROHOLD (RI: peak 8)\",\"PRESBYTERIAN HOSP ABQ (NM: peak 2)\",\"PROVO HOLD ROOM (UT: peak 10)\",\"PROVIDENCE MEDICAL GROUP (KS: peak 1)\",\"PUEBLO COUNTY JAIL (CO: peak 1)\",\"PUEBLO HOLDROOM (CO: peak 15)\",\"PARKVIEW HOSPITAL RANDALLIA (IN: peak 1)\",\"PARADISE VALLEY HOSPITAL (CA: peak 5)\",\"PALMS WEST HOSPITAL (FL: peak 2)\",\"PRINCE WILLIAM (VA: peak 1)\",\"QUEEN'S MEDICAL CENTER (HI: peak 1)\",\"RAPP SEC CENTER (VA: peak 16)\",\"RICHMOND SUB-OFFICE HOLD (VA: peak 277)\",\"READING HOSPITAL (PA: peak 1)\",\"RED RIVER HOSPITAL (TX: peak 1)\",\"RALEIGH HOLD ROOM (NC: peak 14)\",\"REDDING HOLD ROOM (CA: peak 7)\",\"RENO HOLD ROOM (NV: peak 10)\",\"RIO GRANDE ST.HOSPITAL (TX: peak 7)\",\"RIO GRANDE VALLEY STAGING (TX: peak 21)\",\"RICHLAND HOLD ROOM (WA: peak 4)\",\"ROCK ISLAND HOLD ROOM (IL: peak 6)\",\"ROANOKE SUB-OFFICE HOLD ROOM (VA: peak 6)\",\"RANDALL COUNTY JAIL (TX: peak 1)\",\"ROCHESTER GENERAL HOSPITAL (NY: peak 1)\",\"ROCK ISLAND COUNTY JAIL (IL: peak 1)\",\"ROANOKE CITY JAIL (VA: peak 13)\",\"RAPID CITY HOLD ROOM (SD: peak 7)\",\"ROSWELL HOLD ROOM (NM: peak 16)\",\"RIO VISTA BEHV HLTH HSP (TX: peak 7)\",\"SANTA ANA DRO HOLDROOM (CA: peak 150)\",\"SACRAMENTO HOLD (CA: peak 35)\",\"SANTA ANA CITY JAIL (CA: peak 1)\",\"SAN ANGELO HOLDROOM (TX: peak 20)\",\"SAIPAIN HOLD (MP: peak 1)\",\"SAN JUAN SUB-OFFICE HOLD ROOM (PR: peak 50)\",\"SALISBURY HOLD ROOM (MD: peak 23)\",\"SALINE COUNTY JAIL (NE: peak 7)\",\"SARASOTA COUNTY JAIL (FL: peak 10)\",\"SAN BERNARDINO HOLD ROOM (CA: peak 38)\",\"SAN BERNARDINO CO. JAIL (CA: peak 1)\",\"SCOTT COUNTY JAIL (IA: peak 7)\",\"SCOTTS BLUFF CO JAIL (NE: peak 2)\",\"SHARP CHULA VISTA MEDICAL CENTER (CA: peak 3)\",\"SEATTLE FIELD OFFICE HOLD ROOM (WA: peak 59)\",\"SIOUX FALLS HOLD ROOM (SD: peak 20)\",\"SFR HOLD ROOM (CA: peak 44)\",\"ST. GEORGE, UT HOLDROOM (UT: peak 9)\",\"SUMMERLIN HOSPITAL MEDICAL CENTER (NV: peak 1)\",\"SIOUX COUNTY JAIL (IA: peak 10)\",\"SAN JUAN AIRPORT HOLD ROOM (PR: peak 24)\",\"SALT LAKE CITY HOLD ROOM (UT: peak 48)\",\"ST LUKE'S HEALTH - THE WOODLANDS (TX: peak 1)\",\"SANTA MARIA SUB OFFICE ERO (CA: peak 19)\",\"ST. MARY'S CO DET CNTR (MD: peak 1)\",\"SEMINOLE COUNTY JAIL (FL: peak 6)\",\"SAN ANTONIO DRO HOLD ROOM (TX: peak 145)\",\"SAN DIEGO COUNTY JAIL (CA: peak 1)\",\"SND DISTRICT STAGING (CA: peak 68)\",\"SNJ HOLD ROOM (CA: peak 2)\",\"ERO HOLD ROOM (SPRINGFIELD MO) (MO: peak 62)\",\"BISHOP HENRY WHIPPLE FED BLDG (MN: peak 87)\",\"SPOKANE HOLD ROOM (WA: peak 17)\",\"SPOTSYLVANIA REG MED CTR (VA: peak 1)\",\"SANTA ROSA COUNTY JAIL (FL: peak 1)\",\"SOUTHSIDE HOSP NORTHWELL HLTH (NY: peak 2)\",\"SAINT ALBANS HOLD ROOM (VT: peak 7)\",\"ST CHARLES PARISH JAIL (LA: peak 1)\",\"SOUTH TEXAS/PEARSALL HOLD ROOM (TX: peak 51)\",\"ST ELIZABETH YOUNGSTOWN HOSPITAL (OH: peak 2)\",\"ST FRANCIS HOSPITAL (GA: peak 2)\",\"ST JOHN'S HOSPITAL CAMARILLO (CA: peak 1)\",\"ST JOSEPH MEDICAL CENTER (WA: peak 5)\",\"ST. JOHN'S COUNTY JAIL (FL: peak 4)\",\"ST. JOSEPH'S HOSPITAL &amp; MED. CEN. (AZ: peak 1)\",\"SAINT JOSEPH HOSPITAL (CO: peak 1)\",\"STOCKTON STAGING FACILITY (CA: peak 14)\",\"ST. LOUIS HOLDROOM (MO: peak 36)\",\"ST. LUCIE COUNTY JAIL (FL: peak 2)\",\"ST MARY'S HOSPITAL (AZ: peak 1)\",\"ST MARY MEDICAL CENTER (CA: peak 4)\",\"STRONG MEMORIAL HOSPITAL (NY: peak 1)\",\"STUART HOLD ROOM (FL: peak 53)\",\"SUFFOLK CO.CORREC FAC (NY: peak 1)\",\"SUMMIT COUNTY JAIL (UT: peak 1)\",\"SUMTER COUNTY JAIL (FL: peak 10)\",\"SUTTER MED CTR SACRAMENTO (CA: peak 1)\",\"SUWANNEE COUNTY JAIL (FL: peak 1)\",\"SIOUX CITY HOLD ROOM (IA: peak 3)\",\"SYRACUSE HOLD ROOM (NY: peak 14)\",\"TACOMA GENERAL HOSPITAL (WA: peak 1)\",\"TALLAHASSEE HOLD ROOM (FL: peak 45)\",\"TALLAHATCHIE CO CORR FACILITY (MS: peak 1)\",\"TAMPA HOLD ROOM (FL: peak 84)\",\"TAYLOR COUNTY ADULT DET. (TX: peak 1)\",\"TELLER COUNTY JAIL (CO: peak 2)\",\"TWIN FALLS HOLD ROOM (ID: peak 6)\",\"TURNER GUIFORD KNIGHT (TGK) JAIL (FL: peak 27)\",\"TOM GREEN CTY JAIL (TX: peak 15)\",\"TX HEALTH METH HOSP HEB (TX: peak 1)\",\"TEX HEALTH HUGULEY HOSP (TX: peak 4)\",\"TX HLTH HARRIS METH HOSP (TX: peak 2)\",\"THOP MEMORIAL CAMPUS ELP (TX: peak 1)\",\"THOP SIERRA CAMPUS ELP (TX: peak 1)\",\"TITUS COUNTY JAIL (TX: peak 6)\",\"WESTERN TENNESSEE DET. FAC. (TN: peak 39)\",\"TRINITAS REGIONAL MED CTR (NJ: peak 3)\",\"TUCSON INS HOLD ROOM (AZ: peak 15)\",\"TULSA HOLD ROOM (OK: peak 16)\",\"TEXAS VISTA MEDICAL CENTER (TX: peak 1)\",\"TEXARKANA HOLDROOM (AR: peak 6)\",\"UCHICAGO MEDICINE HOSPITAL CHICAGO (IL: peak 1)\",\"UCHICAGO MEDICINE INGALLS MEMORIAL (IL: peak 1)\",\"UCHEALTH UNV HOSP OF CO (CO: peak 3)\",\"UNV CALIFORNIA SAN DIEGO HOSPITAL (CA: peak 1)\",\"UNIV HOSP GEAUGA MED CTR (OH: peak 1)\",\"UNION HOSPITAL (IN: peak 1)\",\"UHS WILSON MEDICAL CENTER (NY: peak 1)\",\"UMASS MEMORIAL MEDICAL CENTER (MA: peak 1)\",\"UNIVERSITY MED CENTER OF EL PASO (TX: peak 3)\",\"UNIVERSITY MEDICAL CENTER (NV: peak 2)\",\"UNITED MEMORIAL MED CTR (NY: peak 1)\",\"UNIVERSITY OF MIAMI HOSPITAL (FL: peak 1)\",\"UNITY HOSPITAL (NY: peak 1)\",\"UNION COUNTY JAIL (SD: peak 21)\",\"UNIVERSITY HOSPITAL (NJ: peak 2)\",\"UNIV OF MARYLAND MEDICAL CENTER (MD: peak 2)\",\"UNIVERSITY OF NEW MEXICO HOSPITAL (NM: peak 1)\",\"UPMC PRESBYTERIAN HOSPITAL (PA: peak 1)\",\"UNITY POINT HLTH ST LUKES HOSP (IA: peak 1)\",\"UNITYPOINT HLTH ST LUKES HOSP SXC (IA: peak 1)\",\"URSULA CENTRALIZED PROCESSING CNTR (TX: peak 463)\",\"UVA UNIV Hospital Center (VA: peak 1)\",\"UVALDE COUNTY JAIL (TX: peak 2)\",\"UNIVERSITY HOSPITAL (TX: peak 6)\",\"VAL VERDE DETENTION CENTER (TX: peak 35)\",\"VALLEY BAPTIST HOSPITAL (TX: peak 12)\",\"VCU HEALTH TAPPAHANNOCK HOSPITAL (VA: peak 1)\",\"VENTURA CUSTODY CASE (CA: peak 80)\",\"VIRGINIA BEACH (VA: peak 2)\",\"VIRGINIA PENINSULA REG. JAIL (VA: peak 1)\",\"VRK PRCS (NY: peak 12)\",\"VT. DEPT. OF CORRECTIONS (VT: peak 1)\",\"VICTOR VALLEY GLOBAL MED CENTER (CA: peak 9)\",\"SHREVEPORT HOLD ROOM (LA: peak 8)\",\"VALLEYWISE HEALTH MED CTR (AZ: peak 2)\",\"WASHINGTON COUNTY JAIL (MN: peak 4)\",\"WAKULLA COUNTY JAIL (FL: peak 1)\",\"WALTON COUNTY D.O.C. (FL: peak 1)\",\"WASHINGTON CO. DETENTION (MD: peak 1)\",\"WASHINGTON FIELD OFFICE (VA: peak 127)\",\"WACO DRO HOLD ROOM (TX: peak 24)\",\"WEBB COUNTY JAIL (TX: peak 1)\",\"WESTMINSTER CUSTODY (CA: peak 8)\",\"WICHITA HOLDROOM (KS: peak 2)\",\"WILSON COUNTY JAIL (TX: peak 8)\",\"WEST KENDALL BAPTIST HOSP (FL: peak 5)\",\"WEST MIAMI DADE BAPT HEALTH EMERG (FL: peak 3)\",\"WHITE MEMORIAL HOSPITAL (CA: peak 6)\",\"WENATCHEE HOLD ROOM (WA: peak 4)\",\"WILLIAMSPORT HOLD ROOM (PA: peak 21)\",\"EASTERN REGIONAL JAIL (WV: peak 16)\",\"POTOMAC HIGHLANDS REGIONAL JAIL (WV: peak 1)\",\"WENTWORTH DOUGLAS HOSPITAL (NH: peak 1)\",\"YAKIMA SUB-OFFICE (WA: peak 12)\",\"YORK COUNTY JAIL, PA (PA: peak 1)\",\"YORK COUNTY DETENTION CENTER (SC: peak 4)\",\"YORK HOLD ROOM (PA: peak 16)\",\"YUMA REGIONAL MED CTR (AZ: peak 1)\",\"YUMA HOLDROOM (AZ: peak 8)\"],{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},null]},{\"method\":\"addLegend\",\"args\":[{\"colors\":[\"#E41A1C\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#377EB8\",\"#984EA3\",\"#999999\"],\"labels\":[\"Dedicated\",\"Non-Dedicated\",\"Federal\",\"Hold/Staging\",\"Family/Youth\",\"Medical\",\"Other/Unknown\"],\"na_color\":null,\"na_label\":\"NA\",\"opacity\":0.5,\"position\":\"bottomright\",\"type\":\"factor\",\"title\":\"Facility type\",\"extra\":null,\"layerId\":null,\"className\":\"info legend\",\"group\":null}]}],\"limits\":{\"lat\":[13.476607,64.834574],\"lng\":[-157.863124,145.703679]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nDDP facilities not in ICE FY25 annual statistics, sized by FY25 peak population\n:::\n:::\n\n\n## Unreported detention: Final Biden quarter vs recent Trump quarter {#sec-period-comparison}\n\nThe preceding sections establish which DDP facilities are absent from the ICE FY25 annual statistics. Here we compare the **unreported population**---detainees held at those unmatched facilities---during the final three months of the Biden administration versus a comparable window under the Trump administration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiden_from <- as.Date(\"2024-10-20\")\nbiden_to   <- as.Date(\"2025-01-19\")\ntrump_from <- as.Date(\"2025-07-01\")\ntrump_to   <- as.Date(\"2025-09-30\")\n```\n:::\n\n\n-   **Biden final quarter**: 2024-10-20 to 2025-01-19 (92 days)\n-   **Trump recent quarter**: 2025-07-01 to 2025-09-30 (92 days)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summarise the unmatched facilities in each period\nbiden_unmatched <- ddp_facility_summary(ddp_raw,\n                                         from = biden_from, to = biden_to,\n                                         codes = unmatched_codes) |>\n  left_join(vera_type_lookup |> select(detloc, type_grouped),\n            by = c(\"detention_facility_code\" = \"detloc\")) |>\n  mutate(\n    type_grouped = if_else(is.na(type_grouped), \"Unclassified\", type_grouped),\n    adp_class = if_else(mean_pop >= 2, \"ADP \\u2265 2\", \"ADP < 2\"),\n    peak_class = dplyr::if_else(peak_pop >= 2, \"Peak \\u2265 2\", \"Peak < 2\"),\n    period = \"Biden\"\n  )\n\ntrump_unmatched <- ddp_facility_summary(ddp_raw,\n                                         from = trump_from, to = trump_to,\n                                         codes = unmatched_codes) |>\n  left_join(vera_type_lookup |> select(detloc, type_grouped),\n            by = c(\"detention_facility_code\" = \"detloc\")) |>\n  mutate(\n    type_grouped = if_else(is.na(type_grouped), \"Unclassified\", type_grouped),\n    adp_class = if_else(mean_pop >= 2, \"ADP \\u2265 2\", \"ADP < 2\"),\n    peak_class = dplyr::if_else(peak_pop >= 2, \"Peak \\u2265 2\", \"Peak < 2\"),\n    period = \"Trump\"\n  )\n```\n:::\n\n\n### Aggregate unreported population\n\n\n::: {#tbl-period-totals .cell tbl-cap='Unreported DDP population by period (facilities not in ICE FY25)'}\n\n```{.r .cell-code}\nbind_rows(biden_unmatched, trump_unmatched) |>\n  filter(peak_pop > 0) |>\n  group_by(period, peak_class) |>\n  summarise(\n    Facilities = n(),\n    `Total ADP` = round(sum(mean_pop)),\n    .groups = \"drop\"\n  ) |>\n  arrange(peak_class, period) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|period |peak_class | Facilities| Total ADP|\n|:------|:----------|----------:|---------:|\n|Biden  |Peak < 2   |        109|         8|\n|Trump  |Peak < 2   |        146|        15|\n|Biden  |Peak ≥ 2   |        206|       396|\n|Trump  |Peak ≥ 2   |        298|      3183|\n\n\n:::\n:::\n\n\n\n::: {#tbl-period-headline .cell tbl-cap='Unreported population totals (Peak ≥ 2 facilities only)'}\n\n```{.r .cell-code}\nbind_rows(biden_unmatched, trump_unmatched) |>\n  filter(peak_pop > 0, peak_class == \"Peak \\u2265 2\") |>\n  group_by(period) |>\n  summarise(\n    Facilities = n(),\n    `Total ADP` = round(sum(mean_pop)),\n    `Mean ADP per facility` = round(sum(mean_pop) / n(), 1),\n    .groups = \"drop\"\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|period | Facilities| Total ADP| Mean ADP per facility|\n|:------|----------:|---------:|---------------------:|\n|Biden  |        206|       396|                   1.9|\n|Trump  |        298|      3183|                  10.7|\n\n\n:::\n:::\n\n\n### By facility type\n\n\n::: {#tbl-period-type-composition .cell tbl-cap='Unreported facilities by type and period (ADP ≥ 2 only)'}\n\n```{.r .cell-code}\ntype_comp <- bind_rows(biden_unmatched, trump_unmatched) |>\n  filter(peak_pop > 0, adp_class == \"ADP \\u2265 2\") |>\n  group_by(period, type_grouped) |>\n  summarise(\n    Facilities = n(),\n    ADP = round(sum(mean_pop)),\n    .groups = \"drop\"\n  )\n\ntype_comp |>\n  pivot_wider(names_from = period,\n              values_from = c(Facilities, ADP),\n              values_fill = 0,\n              names_glue = \"{period} {.value}\") |>\n  mutate(\n    `ADP change` = `Trump ADP` - `Biden ADP`,\n    `% change` = if_else(\n      `Biden ADP` == 0, NA_real_,\n      round((`Trump ADP` / `Biden ADP` - 1) * 100, 1)\n    )\n  ) |>\n  arrange(desc(`Trump ADP`)) |>\n  kable(col.names = c(\"Facility type\",\n                       \"Biden fac.\", \"Trump fac.\",\n                       \"Biden ADP\", \"Trump ADP\",\n                       \"ADP change\", \"% change\"))\n```\n\n::: {.cell-output-display}\n\n\n|Facility type | Biden fac.| Trump fac.| Biden ADP| Trump ADP| ADP change| % change|\n|:-------------|----------:|----------:|---------:|---------:|----------:|--------:|\n|Hold/Staging  |         37|         91|       258|      1955|       1697|    657.8|\n|Dedicated     |          0|          2|         0|       814|        814|       NA|\n|Federal       |          1|         13|         7|       182|        175|   2500.0|\n|Non-Dedicated |          2|         13|        14|        58|         44|    314.3|\n|Medical       |          6|         11|        26|        56|         30|    115.4|\n|Other/Unknown |          1|          1|         3|         7|          4|    133.3|\n|Family/Youth  |          1|          1|         2|         4|          2|    100.0|\n\n\n:::\n:::\n\n\n\n::: {#tbl-period-type-transient .cell tbl-cap='Transient facilities (Peak < 2) by type and period'}\n\n```{.r .cell-code}\nbind_rows(biden_unmatched, trump_unmatched) |>\n  filter(peak_pop > 0, peak_class == \"Peak < 2\") |>\n  group_by(period, type_grouped) |>\n  summarise(\n    Facilities = n(),\n    ADP = round(sum(mean_pop), 1),\n    .groups = \"drop\"\n  ) |>\n  pivot_wider(names_from = period,\n              values_from = c(Facilities, ADP),\n              values_fill = 0,\n              names_glue = \"{period} {.value}\") |>\n  arrange(desc(`Trump Facilities`)) |>\n  kable(col.names = c(\"Facility type\",\n                       \"Biden fac.\", \"Trump fac.\",\n                       \"Biden ADP\", \"Trump ADP\"))\n```\n\n::: {.cell-output-display}\n\n\n|Facility type | Biden fac.| Trump fac.| Biden ADP| Trump ADP|\n|:-------------|----------:|----------:|---------:|---------:|\n|Medical       |         57|         79|       4.7|       8.2|\n|Non-Dedicated |         27|         35|       2.1|       4.6|\n|Federal       |          6|         22|       0.2|       0.8|\n|Hold/Staging  |         17|          7|       0.5|       0.5|\n|Family/Youth  |          0|          2|       0.0|       0.7|\n|Dedicated     |          1|          1|       0.0|       0.4|\n|Other/Unknown |          1|          0|       0.0|       0.0|\n\n\n:::\n:::\n\n\n### Facilities active in only one period\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiden_active <- biden_unmatched |> filter(peak_pop > 0, peak_class == \"Peak \\u2265 2\")\ntrump_active <- trump_unmatched |> filter(peak_pop > 0, peak_class == \"Peak \\u2265 2\")\n\nbiden_only_codes <- setdiff(biden_active$detention_facility_code,\n                             trump_active$detention_facility_code)\ntrump_only_codes <- setdiff(trump_active$detention_facility_code,\n                             biden_active$detention_facility_code)\n```\n:::\n\n\n\n::: {#tbl-biden-only .cell tbl-cap='Unreported facilities with Peak ≥ 2 active under Biden but not Trump'}\n\n```{.r .cell-code}\nif (length(biden_only_codes) > 0) {\n  biden_unmatched |>\n    filter(detention_facility_code %in% biden_only_codes) |>\n    arrange(desc(mean_pop)) |>\n    select(detention_facility, state, type_grouped, mean_pop, peak_pop) |>\n    mutate(mean_pop = round(mean_pop, 1)) |>\n    kable(col.names = c(\"Facility\", \"State\", \"Type\", \"Biden ADP\", \"Biden peak\")) \n}\n```\n\n::: {.cell-output-display}\n\n\n|Facility                           |State |Type          | Biden ADP| Biden peak|\n|:----------------------------------|:-----|:-------------|---------:|----------:|\n|NYE COUNTY SHERIFF-PAHRUMP         |NV    |Non-Dedicated |      12.0|         69|\n|GUAYNABO MDC (SAN JUAN)            |PR    |Federal       |       6.6|         12|\n|MONTGOMERY CO MAC SIM BUTLER D.F.  |AL    |Federal       |       0.9|          2|\n|BRONSON METHODIST HOSPITAL         |MI    |Medical       |       0.8|          2|\n|COBB CO SHERIFFS OFC ADULT DET CTR |GA    |Non-Dedicated |       0.6|          4|\n|SAINT ALBANS HOLD ROOM             |VT    |Hold/Staging  |       0.5|          7|\n|LINCOLN COUNTY SHERIFF'S           |MO    |Non-Dedicated |       0.4|          3|\n|ST. JOHN'S COUNTY JAIL             |FL    |Non-Dedicated |       0.4|          2|\n|METHODIST HOSPITAL TEXSAN          |TX    |Medical       |       0.4|          2|\n|WASHINGTON COUNTY JAIL             |MN    |Federal       |       0.4|          3|\n|VALLEYWISE HEALTH MED CTR          |AZ    |Medical       |       0.3|          2|\n|RENO HOLD ROOM                     |NV    |Hold/Staging  |       0.2|          3|\n|ORANGE REGIONAL MED CTR            |NY    |Medical       |       0.2|          2|\n|LOMPOC FCI                         |CA    |Federal       |       0.2|          6|\n|COLUMBUS HOLDROOM                  |OH    |Hold/Staging  |       0.2|          9|\n|KARNES COUNTY CIVIL DET. FACILITY  |TX    |Family/Youth  |       0.1|          2|\n|KINNEY COUNTY JAIL                 |TX    |Non-Dedicated |       0.1|          4|\n|SIOUX CITY HOLD ROOM               |IA    |Hold/Staging  |       0.1|          3|\n|EL CENTRO REGIONAL MED CTR         |CA    |Medical       |       0.1|          2|\n|MAVERICK COUNTY JAIL               |TX    |Non-Dedicated |       0.1|          3|\n|SPRINGFIELD FED.MED.CNTR           |MO    |Federal       |       0.1|          2|\n|FCI VICTORVILLE                    |CA    |Federal       |       0.1|          7|\n|ST FRANCIS HOSPITAL                |GA    |Medical       |       0.1|          2|\n|CHANDLER REG MED CTR               |AZ    |Medical       |       0.1|          2|\n|SNJ HOLD ROOM                      |CA    |Hold/Staging  |       0.0|          2|\n\n\n:::\n:::\n\n\n25 unreported facilities (Peak ≥ 2) were active in the Biden period but fell below the threshold or had zero population in the Trump period. Of these, 2 had ADP ≥ 2 under Biden, contributing 19 ADP in total.\n\n\n::: {#tbl-trump-only .cell tbl-cap='Unreported facilities with Peak ≥ 2 active under Trump but not Biden (scroll for full list)'}\n\n```{.r .cell-code}\nif (length(trump_only_codes) > 0) {\n  trump_unmatched |>\n    filter(detention_facility_code %in% trump_only_codes) |>\n    arrange(desc(mean_pop)) |>\n    select(detention_facility, state, type_grouped, mean_pop, peak_pop) |>\n    mutate(mean_pop = round(mean_pop, 1)) |>\n    kable(col.names = c(\"Facility\", \"State\", \"Type\", \"Trump ADP\", \"Trump peak\")) |> \n    scroll_box(height = \"630px\")\n}\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:630px; \"><table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> Facility </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> State </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> Type </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> Trump ADP </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> Trump peak </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> FLORIDA SOFT-SIDED FACILITY-SOUTH </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Dedicated </td>\n   <td style=\"text-align:right;\"> 732.7 </td>\n   <td style=\"text-align:right;\"> 1482 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EL PASO SOFT SIDED FACILITY </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 457.7 </td>\n   <td style=\"text-align:right;\"> 1606 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> URSULA CENTRALIZED PROCESSING CNTR </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 121.3 </td>\n   <td style=\"text-align:right;\"> 463 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BAKER C. I. </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Dedicated </td>\n   <td style=\"text-align:right;\"> 81.7 </td>\n   <td style=\"text-align:right;\"> 339 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BROOKS COUNTY JAIL (CONTRACT) </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 17.8 </td>\n   <td style=\"text-align:right;\"> 90 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TURNER GUIFORD KNIGHT (TGK) JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 14.5 </td>\n   <td style=\"text-align:right;\"> 27 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WESTERN TENNESSEE DET. FAC. </td>\n   <td style=\"text-align:left;\"> TN </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 7.2 </td>\n   <td style=\"text-align:right;\"> 39 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MARTIN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 6.8 </td>\n   <td style=\"text-align:right;\"> 24 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WESTMINSTER CUSTODY </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 6.1 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MIGRANT OPS CENTER MAIN AV622 </td>\n   <td style=\"text-align:left;\"> CU </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 5.3 </td>\n   <td style=\"text-align:right;\"> 21 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> OSCEOLA COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 4.9 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ERO HOLD ROOM (SPRINGFIELD MO) </td>\n   <td style=\"text-align:left;\"> MO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 4.1 </td>\n   <td style=\"text-align:right;\"> 62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SW VIRGINIA REG JAIL AUTH-ABG FAC </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 3.9 </td>\n   <td style=\"text-align:right;\"> 47 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHAVEZ DET CRT </td>\n   <td style=\"text-align:left;\"> NM </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 3.6 </td>\n   <td style=\"text-align:right;\"> 16 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EASTERN REGIONAL JAIL </td>\n   <td style=\"text-align:left;\"> WV </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 3.2 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> RIO VISTA BEHV HLTH HSP </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 3.2 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TOM GREEN CTY JAIL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 3.0 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHESAPEAKE CITY JAIL </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 2.7 </td>\n   <td style=\"text-align:right;\"> 25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BUFFALO HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 2.6 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GRAND RAPIDS HOLDROOM </td>\n   <td style=\"text-align:left;\"> MI </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 2.6 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HILLSBOROUGH COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 2.5 </td>\n   <td style=\"text-align:right;\"> 40 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SIOUX COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> IA </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 2.4 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CASCADE COUNTY JAIL, MT </td>\n   <td style=\"text-align:left;\"> MT </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 2.2 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NEW YORK PRESBYTERIAN HOSPITAL </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 2.2 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CEDAR RAPIDS HOLD ROOM </td>\n   <td style=\"text-align:left;\"> IA </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 2.0 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SEMINOLE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 2.0 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WHITE MEMORIAL HOSPITAL </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 2.0 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MARION COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 1.9 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AGUADILLA SPC </td>\n   <td style=\"text-align:left;\"> PR </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.8 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SCOTT COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> IA </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 1.8 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MINICASSIA DET. CENTER </td>\n   <td style=\"text-align:left;\"> ID </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 1.7 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SYRACUSE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.6 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BREVARD COUNTY JAIL COMPLEX </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 1.6 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CACHE CO. JAIL </td>\n   <td style=\"text-align:left;\"> UT </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 1.6 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TEX HEALTH HUGULEY HOSP </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 1.5 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ST JOSEPH MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> WA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 1.3 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ALVARADO PARKWAY INSTITUTE </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 1.3 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> COLO SPRINGS DEN HSI HOLD </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.3 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LAWRENCE CO. JAIL, SD </td>\n   <td style=\"text-align:left;\"> SD </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 1.1 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LIRS - LFSRM FORT COLLINS LTFC CO </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Other/Unknown </td>\n   <td style=\"text-align:right;\"> 1.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NASSAU COUNTY ICE TRAILER </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 1.1 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EL PASO LTAC HOSPITAL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 1.0 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> RIO GRANDE VALLEY STAGING </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.0 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HARRIS COUNTY PSYCHIATRIC CENTER </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 1.0 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROMISE HOSPITAL </td>\n   <td style=\"text-align:left;\"> AZ </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 1.0 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UCHEALTH UNV HOSP OF CO </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNIVERSITY MED CENTER OF EL PASO </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ANAHEIM GLOBAL MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LARAMIE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> WY </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DADE CORRECTIONAL INST </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Dedicated </td>\n   <td style=\"text-align:right;\"> 0.8 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BROWN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> WI </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.7 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MANATEE COUNTY DETENTION-ANNEX </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.7 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> VRK PRCS </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.7 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BUFFALO USBP HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.7 </td>\n   <td style=\"text-align:right;\"> 20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LOUISVILLE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> KY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.6 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CBP MOVEMENT COORDINATION AREA </td>\n   <td style=\"text-align:left;\"> NA </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.6 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> POLK COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.6 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NORTHWEST REG. ADULT DET. </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.6 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BROWARD GENERAL MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHAMPLAIN HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> RAPID CITY HOLD ROOM </td>\n   <td style=\"text-align:left;\"> SD </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SUMTER COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GRADY MEMORIAL HOSPITAL </td>\n   <td style=\"text-align:left;\"> GA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHRISTIAN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> KY </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 19 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FRANKLIN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> PA </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNION COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> SD </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ALAMOSA HOLDROOM </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CLEVELAND HOLD ROOM </td>\n   <td style=\"text-align:left;\"> OH </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GLENWOOD SPRINGS HOLDROOM </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EUGENE HOLDROOM </td>\n   <td style=\"text-align:left;\"> OR </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MEDFORD SUB-OFFICE </td>\n   <td style=\"text-align:left;\"> OR </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LOUDOUN COUNTY </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MONROE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LAREDO MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MAYO CLINIC HEALTH SYS - MANKATO </td>\n   <td style=\"text-align:left;\"> MN </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NASSAU UNIV MED CTR </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HIGHLAND MTN COR CTR </td>\n   <td style=\"text-align:left;\"> AK </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FRIO REGIONAL HOSPITAL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TX HLTH HARRIS METH HOSP </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MCLENNAN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNIVERSITY HOSPITAL </td>\n   <td style=\"text-align:left;\"> NJ </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BOSTON SPC </td>\n   <td style=\"text-align:left;\"> MA </td>\n   <td style=\"text-align:left;\"> Dedicated </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FLAGLER COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HOUSTON HEALTHCARE HOSP </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CAMPBELL COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> WY </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DURANGO HOLDROOM </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> VIRGINIA BEACH </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CENTRAL VA REGIONAL JAIL </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BANNER IRONWOOD MED CTR </td>\n   <td style=\"text-align:left;\"> AZ </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ST ELIZABETH YOUNGSTOWN HOSPITAL </td>\n   <td style=\"text-align:left;\"> OH </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DAVIS CO. JAIL </td>\n   <td style=\"text-align:left;\"> UT </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CRAIG HOLDROOM </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SHARP CHULA VISTA MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EL PASO COUNTY JAIL (TX) </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PARKLAND HOSPITAL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ARROWHEAD REGIONAL MED CENTER </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SALINE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> NE </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNIVERSITY MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> NV </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MOUNT NITTANY MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> PA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ORANGE CO GLOBAL MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WEST MIAMI DADE BAPT HEALTH EMERG </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PALM BEACH COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> RIO GRANDE ST.HOSPITAL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NASHVILLE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> TN </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ST. LUCIE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHARLESTON COUNTY CORRECT </td>\n   <td style=\"text-align:left;\"> SC </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ANCHORAGE SUB-OFFICE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> AK </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GARDEN CITY PROCESSING @ FINNEY CO </td>\n   <td style=\"text-align:left;\"> KS </td>\n   <td style=\"text-align:left;\"> Other/Unknown </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> METRO DADE JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HEL DISTRICT CUSTODY </td>\n   <td style=\"text-align:left;\"> MT </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UVALDE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WICHITA HOLDROOM </td>\n   <td style=\"text-align:left;\"> KS </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHI ST LUKE'S HEALTH MEM </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FORT SMITH HOLDROOM </td>\n   <td style=\"text-align:left;\"> AR </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HENDERSONVILLE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NC </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHESTERFIELD CO. JAIL </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MARION CO JAIL </td>\n   <td style=\"text-align:left;\"> OR </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n:::\n:::\n\n\n117 unreported facilities (Peak ≥ 2) were active in the Trump period but not the Biden period. Of these, 26 had ADP < 2 under Trump, contributing 1498 ADP in total.\n\n\n\n\n::: {#tbl-trump-only-by-type .cell tbl-cap='New unreported facilities under Trump (ADP ≥ 2), by type'}\n\n```{.r .cell-code}\nif (length(trump_only_codes) > 0) {\n  trump_unmatched |>\n    filter(detention_facility_code %in% trump_only_codes) |>\n    group_by(type_grouped) |>\n    summarise(\n      Facilities = n(),\n      `Total ADP` = round(sum(mean_pop)),\n      .groups = \"drop\"\n    ) |>\n    arrange(desc(`Total ADP`)) |>\n    kable(col.names = c(\"Facility type\", \"Facilities\", \"Total ADP\"))\n}\n```\n\n::: {.cell-output-display}\n\n\n|Facility type | Facilities| Total ADP|\n|:-------------|----------:|---------:|\n|Dedicated     |          4|       815|\n|Hold/Staging  |         27|       486|\n|Federal       |         20|       172|\n|Non-Dedicated |         32|        52|\n|Medical       |         32|        22|\n|Other/Unknown |          2|         1|\n\n\n:::\n:::\n\n\n### Facilities active in both periods\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboth_codes <- intersect(biden_active$detention_facility_code,\n                         trump_active$detention_facility_code)\n\nboth_compare <- biden_unmatched |>\n  filter(detention_facility_code %in% both_codes) |>\n  select(detention_facility_code, detention_facility, state, type_grouped,\n         biden_adp = mean_pop, biden_peak = peak_pop) |>\n  inner_join(\n    trump_unmatched |>\n      filter(detention_facility_code %in% both_codes) |>\n      select(detention_facility_code,\n             trump_adp = mean_pop, trump_peak = peak_pop),\n    by = \"detention_facility_code\"\n  ) |>\n  mutate(\n    adp_change = trump_adp - biden_adp,\n    adp_pct_change = if_else(biden_adp == 0, NA_real_,\n                             (trump_adp / biden_adp - 1) * 100)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(both_compare, aes(x = biden_adp, y = trump_adp, color = type_grouped)) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  geom_point(alpha = 0.7) +\n  scale_x_log10(labels = comma) +\n  scale_y_log10(labels = comma) +\n  labs(x = \"Biden final quarter ADP\", y = \"Trump recent quarter ADP\",\n       color = \"Facility type\")\n```\n\n::: {.cell-output-display}\n![Mean ADP at unreported facilities: Biden vs Trump (facilities with ADP ≥ 2 in both periods, log scale)](ddp-comparison_files/figure-html/fig-scatter-periods-1.png){#fig-scatter-periods width=672}\n:::\n:::\n\n\n\n::: {#tbl-top-increases .cell tbl-cap='Top 15 unreported facilities by ADP increase (Biden → Trump)'}\n\n```{.r .cell-code}\nboth_compare |>\n  arrange(desc(adp_change)) |>\n  head(15) |>\n  transmute(\n    Facility = detention_facility, State = state, Type = type_grouped,\n    `Biden ADP` = round(biden_adp),\n    `Trump ADP` = round(trump_adp),\n    Change = round(adp_change)\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Facility                       |State |Type         | Biden ADP| Trump ADP| Change|\n|:------------------------------|:-----|:------------|---------:|---------:|------:|\n|LOS CUST CASE                  |CA    |Hold/Staging |         7|       120|    112|\n|NYC HOLD ROOM                  |NY    |Hold/Staging |         5|        89|     83|\n|ATLANTA DIST. HOLD RM          |GA    |Hold/Staging |         9|        89|     80|\n|DALLAS F.O. HOLD               |TX    |Hold/Staging |        16|        96|     80|\n|MONTGOMERY HOLD RM             |TX    |Hold/Staging |        30|        91|     61|\n|BROADVIEW SERVICE STAGING      |IL    |Hold/Staging |         9|        65|     56|\n|AZ REM OP COORD CENTER (AROCC) |AZ    |Hold/Staging |        16|        67|     50|\n|BALTIMORE HOLD ROOM            |MD    |Hold/Staging |         2|        48|     46|\n|WASHINGTON FIELD OFFICE        |VA    |Hold/Staging |         7|        39|     32|\n|MIAMI (MIRAMAR) HOLD ROOM      |FL    |Hold/Staging |         0|        31|     31|\n|ORLANDO HOLD ROOM              |FL    |Hold/Staging |         6|        37|     31|\n|SAN ANTONIO DRO HOLD ROOM      |TX    |Hold/Staging |         5|        35|     29|\n|RICHMOND SUB-OFFICE HOLD       |VA    |Hold/Staging |         5|        32|     27|\n|SND DISTRICT STAGING           |CA    |Hold/Staging |         9|        34|     25|\n|TAMPA HOLD ROOM                |FL    |Hold/Staging |         5|        30|     25|\n\n\n:::\n:::\n\n\n\n::: {#tbl-top-decreases .cell tbl-cap='Top 15 unreported facilities by ADP decrease (Biden → Trump)'}\n\n```{.r .cell-code}\nboth_compare |>\n  arrange(adp_change) |>\n  head(15) |>\n  transmute(\n    Facility = detention_facility, State = state, Type = type_grouped,\n    `Biden ADP` = round(biden_adp),\n    `Trump ADP` = round(trump_adp),\n    Change = round(adp_change)\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Facility                   |State |Type          | Biden ADP| Trump ADP| Change|\n|:--------------------------|:-----|:-------------|---------:|---------:|------:|\n|KROME HOLD ROOM            |FL    |Hold/Staging  |        21|         2|    -20|\n|MCALLEN HOLD ROOM          |TX    |Hold/Staging  |        13|         4|     -9|\n|MIAMI STAGING FACILITY     |FL    |Hold/Staging  |        11|         9|     -2|\n|BALDWIN COUNTY COR. CENTER |AL    |Non-Dedicated |         2|         0|     -2|\n|PECOS HOLD ROOM            |TX    |Hold/Staging  |         3|         2|     -1|\n|NEW/INS OS HOLD ROOM       |NJ    |Hold/Staging  |         1|         0|     -1|\n|SAN JUAN AIRPORT HOLD ROOM |PR    |Hold/Staging  |         1|         1|      0|\n|CASPER HOLDROOM            |WY    |Hold/Staging  |         0|         0|      0|\n|CHARLOTTE AMALIE HOLDROOM  |VI    |Hold/Staging  |         0|         0|      0|\n|LAS CRUCES HOLD ROOM       |NM    |Hold/Staging  |         0|         0|      0|\n|FAYETTEVILLE HOLD ROOM     |AR    |Hold/Staging  |         0|         0|      0|\n|TWIN FALLS HOLD ROOM       |ID    |Hold/Staging  |         0|         0|      0|\n|ROCK ISLAND HOLD ROOM      |IL    |Hold/Staging  |         1|         1|      0|\n|SPOKANE HOLD ROOM          |WA    |Hold/Staging  |         1|         1|      0|\n|METHODIST HOSPITAL         |TX    |Medical       |         0|         0|      0|\n\n\n:::\n:::\n\n\n### Daily unreported population by period\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Facility codes with ADP >= 2 in at least one period\nsubstantive_codes <- union(biden_active$detention_facility_code,\n                            trump_active$detention_facility_code)\n\ndaily_unreported <- ddp_raw |>\n  filter(\n    detention_facility_code %in% substantive_codes,\n    (date >= biden_from & date <= biden_to) |\n      (date >= trump_from & date <= trump_to)\n  ) |>\n  left_join(vera_type_lookup |> select(detloc, type_grouped),\n            by = c(\"detention_facility_code\" = \"detloc\")) |>\n  mutate(\n    type_grouped = if_else(is.na(type_grouped), \"Unclassified\", type_grouped),\n    period = case_when(\n      date >= biden_from & date <= biden_to ~ \"Biden final quarter\",\n      date >= trump_from & date <= trump_to ~ \"Trump recent quarter\"\n    )\n  ) |>\n  group_by(period, date, type_grouped) |>\n  summarise(total_pop = sum(n_detained, na.rm = TRUE), .groups = \"drop\")\n\nggplot(daily_unreported, aes(x = date, y = total_pop, fill = type_grouped)) +\n  geom_col() +\n  facet_wrap(~period, scales = \"free_x\") +\n  scale_y_continuous(labels = comma) +\n  scale_x_date(date_labels = \"%b %d\") +\n  labs(x = NULL, y = \"Unreported detained population\", fill = \"Facility type\")\n```\n\n::: {.cell-output-display}\n![Daily unreported detention population during both comparison periods, by facility type (ADP ≥ 2 facilities only)](ddp-comparison_files/figure-html/fig-daily-unreported-periods-1.png){#fig-daily-unreported-periods width=672}\n:::\n:::\n\n",
    "supporting": [
      "ddp-comparison_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"site_libs/leaflet-1.3.1/leaflet.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/leaflet-1.3.1/leaflet.js\"></script>\n<link href=\"site_libs/leafletfix-1.0.0/leafletfix.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/proj4-2.6.2/proj4.min.js\"></script>\n<script src=\"site_libs/Proj4Leaflet-1.0.1/proj4leaflet.js\"></script>\n<link href=\"site_libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/leaflet-binding-2.2.3/leaflet.js\"></script>\n<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}